"""
Build script: Lean 4 PGD Cython FFI extension.

Usage (from foundations/optimization-proofs/):
    uv run python ffi/setup_ffi.py build_ext --inplace

Prerequisites:
  - lake build must have run in foundations/optimization-proofs/ (generates C IR)
  - lean must be on PATH (managed by elan)
  - cython must be installed (add via uv add cython numpy)
"""

import os
import subprocess
import sys
from pathlib import Path

from Cython.Build import cythonize
from setuptools import Extension, setup


def lean_prefix() -> Path:
    try:
        r = subprocess.run(
            ["lean", "--print-prefix"],
            capture_output=True,
            text=True,
            check=True,
            cwd=Path(__file__).parent.parent,  # foundations/optimization-proofs/
        )
        return Path(r.stdout.strip())
    except (subprocess.CalledProcessError, FileNotFoundError) as e:
        sys.exit(f"ERROR: lean not found on PATH ({e})")


def main() -> None:
    repo_root = Path(__file__).parent.parent  # foundations/optimization-proofs/
    prefix = lean_prefix()

    lean_include = str(prefix / "include")
    lean_lib_dir = str(prefix / "lib" / "lean")

    ir_root = repo_root / ".lake" / "build" / "ir" / "OptimizationProofs"
    if not ir_root.is_dir():
        sys.exit(f"ERROR: Lake IR not found at {ir_root}\nRun `lake build` first.")

    # C files generated by lake build for our two modules
    c_sources = [
        str(ir_root / "PGD.c"),
        str(ir_root / "PGDFlat.c"),
        str(ir_root / "FFI.c"),
    ]
    for src in c_sources:
        if not os.path.isfile(src):
            sys.exit(f"ERROR: missing C IR: {src}")

    import numpy as np

    numpy_include = np.get_include()

    pyx = str(Path(__file__).parent / "pgd_ffi.pyx")

    ext = Extension(
        name="pgd_ffi",
        sources=[pyx] + c_sources,
        include_dirs=[lean_include, numpy_include],
        library_dirs=[lean_lib_dir],
        libraries=["leanshared"],
        runtime_library_dirs=[lean_lib_dir],
        extra_compile_args=[
            "-Wno-unused-parameter",
            "-Wno-unused-label",
            "-O2",
        ],
        language="c",
    )

    setup(
        name="pgd-ffi",
        ext_modules=cythonize(
            [ext],
            compiler_directives={
                "language_level": "3",
                "boundscheck": False,
                "wraparound": False,
                "cdivision": True,
            },
        ),
    )


if __name__ == "__main__":
    main()
