<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Akhil Karra">
<meta name="dcterms.date" content="2026-05-23">
<meta name="keywords" content="quantitative finance, formal verification, Lean 4, delta hedging, options">

<title>Lean 4 Proof-Checked Delta-Hedging: Accounting Invariants with Empirical Validation Across Four Historical Regimes</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="backtest-proofs_files/libs/clipboard/clipboard.min.js"></script>
<script src="backtest-proofs_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="backtest-proofs_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="backtest-proofs_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="backtest-proofs_files/libs/quarto-html/popper.min.js"></script>
<script src="backtest-proofs_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="backtest-proofs_files/libs/quarto-html/anchor.min.js"></script>
<link href="backtest-proofs_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="backtest-proofs_files/libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="backtest-proofs_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="backtest-proofs_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="backtest-proofs_files/libs/bootstrap/bootstrap-a74871fe4945b66d259aafc266475145.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script>window.backupDefine = window.define; window.define = undefined;</script><script src="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.js"></script>
  <script>document.addEventListener("DOMContentLoaded", function () {
 var mathElements = document.getElementsByClassName("math");
 var macros = [];
 for (var i = 0; i < mathElements.length; i++) {
  var texText = mathElements[i].firstChild;
  if (mathElements[i].tagName == "SPAN") {
   katex.render(texText.data, mathElements[i], {
    displayMode: mathElements[i].classList.contains('display'),
    throwOnError: false,
    macros: macros,
    fleqn: false
   });
}}});
  </script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.css">

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#sec-intro" id="toc-sec-intro" class="nav-link active" data-scroll-target="#sec-intro"><span class="header-section-number">1</span> Introduction</a>
  <ul class="collapse">
  <li><a href="#sec-related" id="toc-sec-related" class="nav-link" data-scroll-target="#sec-related"><span class="header-section-number">1.1</span> Related Work</a></li>
  </ul></li>
  <li><a href="#sec-setup" id="toc-sec-setup" class="nav-link" data-scroll-target="#sec-setup"><span class="header-section-number">2</span> The Backtesting System</a>
  <ul class="collapse">
  <li><a href="#sec-model" id="toc-sec-model" class="nav-link" data-scroll-target="#sec-model"><span class="header-section-number">2.1</span> Discrete-time delta-hedging model</a></li>
  <li><a href="#sec-primitives" id="toc-sec-primitives" class="nav-link" data-scroll-target="#sec-primitives"><span class="header-section-number">2.2</span> The accounting kernel</a></li>
  <li><a href="#sec-bpints" id="toc-sec-bpints" class="nav-link" data-scroll-target="#sec-bpints"><span class="header-section-number">2.3</span> Integer basis-point representation</a></li>
  <li><a href="#sec-strategy" id="toc-sec-strategy" class="nav-link" data-scroll-target="#sec-strategy"><span class="header-section-number">2.4</span> The <code>StepCertificate</code></a></li>
  </ul></li>
  <li><a href="#sec-main-results" id="toc-sec-main-results" class="nav-link" data-scroll-target="#sec-main-results"><span class="header-section-number">3</span> What the Proof Guarantees</a></li>
  <li><a href="#sec-formalization" id="toc-sec-formalization" class="nav-link" data-scroll-target="#sec-formalization"><span class="header-section-number">4</span> The Proof Catches What Testing Cannot</a>
  <ul class="collapse">
  <li><a href="#sec-artifacts" id="toc-sec-artifacts" class="nav-link" data-scroll-target="#sec-artifacts"><span class="header-section-number">4.1</span> Lean 4 artifacts</a></li>
  <li><a href="#sec-scope" id="toc-sec-scope" class="nav-link" data-scroll-target="#sec-scope"><span class="header-section-number">4.2</span> Scope of formalization</a></li>
  <li><a href="#sec-falsification" id="toc-sec-falsification" class="nav-link" data-scroll-target="#sec-falsification"><span class="header-section-number">4.3</span> Falsification exhibit</a></li>
  </ul></li>
  <li><a href="#sec-data" id="toc-sec-data" class="nav-link" data-scroll-target="#sec-data"><span class="header-section-number">5</span> Empirical Setup</a>
  <ul class="collapse">
  <li><a href="#main-sample" id="toc-main-sample" class="nav-link" data-scroll-target="#main-sample"><span class="header-section-number">5.1</span> Main sample</a></li>
  <li><a href="#stress-period-samples" id="toc-stress-period-samples" class="nav-link" data-scroll-target="#stress-period-samples"><span class="header-section-number">5.2</span> Stress-period samples</a></li>
  <li><a href="#synthetic-gbm-and-deterministic-paths" id="toc-synthetic-gbm-and-deterministic-paths" class="nav-link" data-scroll-target="#synthetic-gbm-and-deterministic-paths"><span class="header-section-number">5.3</span> Synthetic GBM and deterministic paths</a></li>
  </ul></li>
  <li><a href="#sec-results" id="toc-sec-results" class="nav-link" data-scroll-target="#sec-results"><span class="header-section-number">6</span> Does the Backtester Work?</a>
  <ul class="collapse">
  <li><a href="#sec-mc" id="toc-sec-mc" class="nav-link" data-scroll-target="#sec-mc"><span class="header-section-number">6.1</span> Monte Carlo convergence</a></li>
  <li><a href="#sec-bkl" id="toc-sec-bkl" class="nav-link" data-scroll-target="#sec-bkl"><span class="header-section-number">6.2</span> BKL variance scaling</a></li>
  <li><a href="#sec-carr-madan" id="toc-sec-carr-madan" class="nav-link" data-scroll-target="#sec-carr-madan"><span class="header-section-number">6.3</span> Carr-Madan gamma attribution</a></li>
  <li><a href="#sec-error-decomp" id="toc-sec-error-decomp" class="nav-link" data-scroll-target="#sec-error-decomp"><span class="header-section-number">6.4</span> Error decomposition</a></li>
  <li><a href="#sec-hull" id="toc-sec-hull" class="nav-link" data-scroll-target="#sec-hull"><span class="header-section-number">6.5</span> Hull Table 19.2 / 19.3 replication</a></li>
  <li><a href="#sec-quantlib" id="toc-sec-quantlib" class="nav-link" data-scroll-target="#sec-quantlib"><span class="header-section-number">6.6</span> QuantLib A-B comparison</a></li>
  <li><a href="#sec-multi-leg" id="toc-sec-multi-leg" class="nav-link" data-scroll-target="#sec-multi-leg"><span class="header-section-number">6.7</span> Multi-leg portfolios</a>
  <ul class="collapse">
  <li><a href="#sec-straddle-settlement" id="toc-sec-straddle-settlement" class="nav-link" data-scroll-target="#sec-straddle-settlement"><span class="header-section-number">6.7.1</span> Short straddle: settlement decomposition</a></li>
  <li><a href="#sec-bull-spread" id="toc-sec-bull-spread" class="nav-link" data-scroll-target="#sec-bull-spread"><span class="header-section-number">6.7.2</span> Bull call spread</a></li>
  </ul></li>
  <li><a href="#sec-equity" id="toc-sec-equity" class="nav-link" data-scroll-target="#sec-equity"><span class="header-section-number">6.8</span> Equity long/short and covered-call demo</a></li>
  <li><a href="#sec-wrds" id="toc-sec-wrds" class="nav-link" data-scroll-target="#sec-wrds"><span class="header-section-number">6.9</span> WRDS 2019–2024 holdout</a></li>
  </ul></li>
  <li><a href="#sec-robustness" id="toc-sec-robustness" class="nav-link" data-scroll-target="#sec-robustness"><span class="header-section-number">7</span> Does It Hold Under Stress?</a>
  <ul class="collapse">
  <li><a href="#sec-stress" id="toc-sec-stress" class="nav-link" data-scroll-target="#sec-stress"><span class="header-section-number">7.1</span> Four historical stress regimes</a></li>
  <li><a href="#sec-variance-theory" id="toc-sec-variance-theory" class="nav-link" data-scroll-target="#sec-variance-theory"><span class="header-section-number">7.2</span> Variance scaling and bias convergence</a></li>
  </ul></li>
  <li><a href="#sec-discussion" id="toc-sec-discussion" class="nav-link" data-scroll-target="#sec-discussion"><span class="header-section-number">8</span> Discussion</a>
  <ul class="collapse">
  <li><a href="#sec-proof-scope" id="toc-sec-proof-scope" class="nav-link" data-scroll-target="#sec-proof-scope"><span class="header-section-number">8.1</span> What formal proofs guarantee — and what they do not</a></li>
  <li><a href="#sec-limitations" id="toc-sec-limitations" class="nav-link" data-scroll-target="#sec-limitations"><span class="header-section-number">8.2</span> Scope limitations</a></li>
  <li><a href="#sec-extensions" id="toc-sec-extensions" class="nav-link" data-scroll-target="#sec-extensions"><span class="header-section-number">8.3</span> Extensions</a></li>
  <li><a href="#sec-data-availability" id="toc-sec-data-availability" class="nav-link" data-scroll-target="#sec-data-availability"><span class="header-section-number">8.4</span> Data Availability</a></li>
  </ul></li>
  
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="backtest-proofs.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Lean 4 Proof-Checked Delta-Hedging: Accounting Invariants with Empirical Validation Across Four Historical Regimes</h1>
<p class="subtitle lead">backtest-proofs — EigenQ Research Series</p>
</div>


<div class="quarto-title-meta-author">
  <div class="quarto-title-meta-heading">Author</div>
  <div class="quarto-title-meta-heading">Affiliation</div>
  
    <div class="quarto-title-meta-contents">
    <p class="author">Akhil Karra <a href="mailto:akhil.karra@eigenq.xyz" class="quarto-title-author-email"><i class="bi bi-envelope"></i></a> </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            eigenq-xyz
          </p>
      </div>
  </div>

<div class="quarto-title-meta">

      
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">May 23, 2026</p>
    </div>
  </div>
  
    
  </div>
  
<div>
  <div class="abstract">
    <div class="block-title">Abstract</div>
    <p>We present the first Lean 4 formalization of operational accounting invariants for a traditional-securities options delta-hedging backtester. Eleven theorems — covering NAV identity, trade accounting, cash-update correctness, quantity conservation, self-financing, well-formedness, option settlement, and option payoff non-negativity — are proved zero-sorry at the version tagged for submission and compiled via Lean 4’s LLVM backend to a native shared library called at runtime through a Cython FFI layer, closing the gap between proof and execution by construction. We pair the formalization with empirical validation on 500 seeded GBM paths and a WRDS OptionMetrics sample of 491,390 option-day observations (2019–2024, six equity underlyings, ATM ±3%). The Monte Carlo running-mean hedging cost converges to the Black-Scholes price with a 2.34% final deviation; our Black-Scholes implementation agrees with QuantLib’s analytic pricer to a maximum of 2.69 basis points across five parameter scenarios. The accounting invariants hold unconditionally across four historical stress regimes (GFC 2008, Volmageddon 2018, Q4 2018, COVID 2020) — a formal guarantee independent of empirical outcomes. Primary empirical results assume flat per-series implied volatility and zero transaction costs; a fixed-fee extension is proved as a separate theorem, with proportional cost support deferred to future work.</p>
  </div>
</div>

<div>
  <div class="keywords">
    <div class="block-title">Keywords</div>
    <p>quantitative finance, formal verification, Lean 4, delta hedging, options</p>
  </div>
</div>

</header>


<section id="sec-intro" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Introduction</h1>
<p>Automated derivatives backtesting systems compute profit and loss for millions of simulated positions — and the accounting ledger driving those computations is almost never formally verified. A bug that silently drops an option settlement, mis-credits cash on a delta-hedge rebalance, or applies a closing transaction to the wrong position leg does not produce an obviously wrong output. It produces a plausible P&amp;L time series that passes visual inspection, generates a positive Sharpe ratio, and survives out-of-sample evaluation — precisely because the ledger error applies uniformly to every trade, in-sample and out-of-sample alike. A delta-hedging accounting bug that inflates the reported Sharpe ratio by fifteen percent is invisible to any statistical test that takes the reported P&amp;L as given. The only way to eliminate this failure class entirely is to prove the accounting layer correct, so that bugs of this kind become structurally impossible rather than merely unlikely.</p>
<p>Backtesting errors fall into two orthogonal classes: accounting errors and model errors. Statistical overfitting — the tendency of in-sample strategies to fail out of sample — has attracted sustained attention from empirical finance; <span class="citation" data-cites="baileyetal2015">Bailey et al. <a href="#ref-baileyetal2015" role="doc-biblioref">(2016)</a></span> introduced combinatorially symmetric cross-validation to quantify this risk, <span class="citation" data-cites="harvey2016">Harvey, Liu, and Zhu <a href="#ref-harvey2016" role="doc-biblioref">(2016)</a></span> found that most claimed findings in financial economics are likely false under conventional significance thresholds, and <span class="citation" data-cites="jensen2023">Jensen, Kelly, and Pedersen <a href="#ref-jensen2023" role="doc-biblioref">(2023)</a></span> documented that overfitting persists even after out-of-sample testing is applied systematically. The second class — accounting errors — has received far less scrutiny, despite being documented in production systems by <span class="citation" data-cites="lowetal2015">Löw, Maier-Paape, and Platen <a href="#ref-lowetal2015" role="doc-biblioref">(2017)</a></span> and in a systematic taxonomy across five open-source engines by <span class="citation" data-cites="bougeret2026">Yin et al. <a href="#ref-bougeret2026" role="doc-biblioref">(2026)</a></span>. The distinguishing feature is that accounting bugs cannot be corrected by splitting the sample: the error is present in every period, so out-of-sample performance is just as inflated as in-sample performance. Extensive testing mitigates this risk but cannot eliminate it — a test suite checks correctness on inputs the test author thought to include, not on every input that live historical data will produce.</p>
<p>This paper proves the accounting layer of an options delta-hedging backtester correct in Lean 4 and pairs that proof with empirical validation across four historical market regimes. Three contributions define the scope precisely. First, this is the first Lean 4 formalization of traditional securities accounting invariants. Prior Lean 4 work on financial systems targets decentralized exchange mechanics — <span class="citation" data-cites="pusceddu2024">Pusceddu and Bartoletti <a href="#ref-pusceddu2024" role="doc-biblioref">(2024)</a></span> and <span class="citation" data-cites="dessalvi2026">Dessalvi, Bartoletti, and Lluch-Lafuente <a href="#ref-dessalvi2026" role="doc-biblioref">(2026)</a></span> apply Lean 4 to automated market makers — but the ledger layer of a conventional options backtester, tracking integer-valued cash, positions, and P&amp;L as trades execute and options settle, has not previously been formalized in any proof assistant. Second, this is the first Lean 4-to-Python/Cython bridge for a financial accounting kernel: the proved theorems compile via Lean 4’s LLVM backend to a native shared library that the Python backtester calls at runtime through a Cython FFI layer, so the gap between “proof complete” and “proof running in a backtester” is closed by construction. The closest structural antecedent is <span class="citation" data-cites="natarajan2021">Natarajan, Sarswat, and Singh <a href="#ref-natarajan2021" role="doc-biblioref">(2021)</a></span>, who extract certified OCaml from Coq proofs of exchange matching algorithms and run the extracted code against live NSE data; that work targets matching mechanics, not the accounting invariants of a running position ledger. Purpose-built industrial formal methods systems, such as Imandra <span class="citation" data-cites="passmore2017"><a href="#ref-passmore2017" role="doc-biblioref">Passmore and Ignatovich (2017)</a></span>, address exchange rule verification but are closed-source and target a different layer. Third, this is the first machine-checked formalization of operational options delta-hedging accounting invariants — the word operational distinguishing ledger correctness (cash, positions, net asset value) from pricing theory <span class="citation" data-cites="echenim2021"><a href="#ref-echenim2021" role="doc-biblioref">Echenim, Guiol, and Peltier (2021)</a></span> and exchange mechanics <span class="citation" data-cites="natarajan2021"><a href="#ref-natarajan2021" role="doc-biblioref">Natarajan, Sarswat, and Singh (2021)</a></span>. One concession is required and must be stated plainly: the accounting invariants are proved correct for any integer-representable instrument; the Black-Scholes pricing model, the GBM path generator, and all statistical claims about hedging cost distributions are not and cannot be formally verified. Those layers are empirically validated in Sections 6–8 and cross-checked against QuantLib. The contribution is the verification workflow — not a novel accounting result for European vanilla options. European vanilla delta-hedging is tractable enough that a reader can check the paper’s accounting claims against <span class="citation" data-cites="hull2014">Hull <a href="#ref-hull2014" role="doc-biblioref">(2014)</a></span> without proprietary access, which is why it is the right vehicle for a methodology demonstration.</p>
<p>Two developments make this work tractable now. Lean 4’s stable release and the Mathlib4 port closed the execution gap: the LLVM backend produces a native shared library callable via Cython FFI, so proved theorems compile directly to a form a Python backtester calls at runtime <span class="citation" data-cites="moura2021lean4"><a href="#ref-moura2021lean4" role="doc-biblioref">Moura and Ullrich (2021)</a></span>. Separately, the replication crisis in empirical finance <span class="citation" data-cites="harvey2016 jensen2023"><a href="#ref-harvey2016" role="doc-biblioref">Harvey, Liu, and Zhu (2016)</a>, <a href="#ref-jensen2023" role="doc-biblioref">Jensen, Kelly, and Pedersen (2023)</a></span> has created institutional demand for correctness guarantees that statistical tests cannot supply — demand that motivated this methodology.</p>
<p>The remainder of the paper is organized as follows. Section 2 (The Backtesting System) defines the discrete-time delta-hedging model and the <code>Portfolio</code>, <code>Position</code>, and <code>Trade</code> accounting kernel, explaining why integer basis-point arithmetic is the right contract for enforcing the boundary between the verified accounting layer and the floating-point pricing layer. Section 3 (What Formal Proof Catches That Testing Misses) demonstrates via a falsification exhibit what a formally verified system catches that a standard test suite cannot; the <code>StepCertificate</code> is the connective tissue between the proved kernel and the empirical pipeline. Section 4 (Empirical Validation) presents Monte Carlo convergence, Hull replication, and the WRDS 2019–2024 holdout and four historical stress regimes. Section 5 (The Variance of Hedging Cost) explains why the nonzero mean and variance of the hedging cost distribution are expected from theory, not indicators of accounting error. Section 6 (Discussion) states scope limitations and directions for extension. The novelty lies in the conjunction: no prior work combines all three — Lean 4, traditional-securities accounting invariants, and a proof that executes at runtime in Python via Cython FFI. Full theorem statements with Lean source, the proof architecture, and extended exhibits appear in the Appendix.</p>
<section id="sec-related" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="sec-related"><span class="header-section-number">1.1</span> Related Work</h2>
<p>The foundational financial contract DSLs — <span class="citation" data-cites="peytonjones2000">Peyton Jones, Eber, and Seward <a href="#ref-peytonjones2000" role="doc-biblioref">(2000)</a></span> and <span class="citation" data-cites="bahr2015">Bahr, Berthold, and Elsman <a href="#ref-bahr2015" role="doc-biblioref">(2015)</a></span> — formalise contract semantics as algebraic combinators, demonstrating that financial instruments can be given rigorous mathematical descriptions. <span class="citation" data-cites="annenkov2018">Annenkov and Elsman <a href="#ref-annenkov2018" role="doc-biblioref">(2018)</a></span> extend this to a Coq implementation. These papers establish that formal specification of financial operations is tractable but do not target accounting-layer invariants for production backtesting pipelines.</p>
<p>The closest prior formalisation of accounting invariants is <span class="citation" data-cites="echenim2021">Echenim, Guiol, and Peltier <a href="#ref-echenim2021" role="doc-biblioref">(2021)</a></span>, who prove ledger identities for the Cox–Ross–Rubinstein model in Isabelle/HOL, adopting the same generic/specific separation we use — instrument-agnostic portfolio accounting separate from option-specific pricing. Their work is a standalone Isabelle proof artifact with no path to Python execution. <span class="citation" data-cites="natarajan2021">Natarajan, Sarswat, and Singh <a href="#ref-natarajan2021" role="doc-biblioref">(2021)</a></span> formalise exchange matching-engine invariants in Coq, with extraction to OCaml and Haskell; <span class="citation" data-cites="natarajan2024">Natarajan, Sarswat, and Singh <a href="#ref-natarajan2024" role="doc-biblioref">(2024)</a></span> extend this to automated checkers on real exchange data. Both are Coq-based and target exchange mechanics rather than backtesting accounting.</p>
<p>Passmore and Ignatovich <span class="citation" data-cites="passmore2017 passmore2020"><a href="#ref-passmore2017" role="doc-biblioref">(2017)</a>, <a href="#ref-passmore2020" role="doc-biblioref">(2020)</a></span> introduced Imandra, a purpose-built industrial formal verification system deployed at real exchanges for matching-engine fairness and clearing-rule verification. Imandra combines SMT solving with ACL2-style induction. backtest-proofs differs in three ways: it uses Lean 4 and Mathlib4 (open-source, general-purpose, community-maintained) rather than a proprietary hybrid; it targets the accounting invariant layer of a backtesting pipeline rather than matching-engine rules; and it bridges to the Python practitioner ecosystem via Cython FFI rather than a proprietary exchange interface.</p>
<p>Prior Lean 4 work on financial systems targets <strong>decentralized finance (DeFi)</strong>: <span class="citation" data-cites="pusceddu2024">Pusceddu and Bartoletti <a href="#ref-pusceddu2024" role="doc-biblioref">(2024)</a></span> apply Lean 4 to automated market makers, and <span class="citation" data-cites="dessalvi2026">Dessalvi, Bartoletti, and Lluch-Lafuente <a href="#ref-dessalvi2026" role="doc-biblioref">(2026)</a></span> similarly. This paper operates in <strong>traditional finance (TradFi)</strong> — exchange-listed equity options under Black-Scholes delta hedging. The DeFi/TradFi distinction is material: smart-contract invariants concern token-reserve conservation under adversarial execution, while backtesting accounting invariants concern NAV identity and self-financing under sequential rebalancing.</p>
<p>Property-based testing <span class="citation" data-cites="claessen2000"><a href="#ref-claessen2000" role="doc-biblioref">Claessen and Hughes (2000)</a></span> samples a finite set of inputs; the Lean 4 proofs here discharge universally quantified statements over all integer-representable inputs. A decade of documented replication failures — <span class="citation" data-cites="harvey2016">Harvey, Liu, and Zhu <a href="#ref-harvey2016" role="doc-biblioref">(2016)</a></span> finding most factor discoveries are false positives, <span class="citation" data-cites="jensen2023">Jensen, Kelly, and Pedersen <a href="#ref-jensen2023" role="doc-biblioref">(2023)</a></span> institutionalising this as a reproducibility crisis — motivates correctness guarantees that out-of-sample tests cannot supply. AI-assisted proof development <span class="citation" data-cites="yang2023leandojo"><a href="#ref-yang2023leandojo" role="doc-biblioref">Yang et al. (2023)</a></span> has reduced the per-lemma cost for algebraic invariants, making this approach practical for evolving quant pipelines.</p>
</section>
</section>
<section id="sec-setup" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> The Backtesting System</h1>
<section id="sec-model" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="sec-model"><span class="header-section-number">2.1</span> Discrete-time delta-hedging model</h2>
<p>Consider a hedger who writes <span class="math inline">N</span> European call options at time <span class="math inline">t = 0</span> and commits to dynamically replicating the short position over a finite horizon <span class="math inline">T</span> using <span class="math inline">n</span> equally spaced rebalancing steps of width <span class="math inline">\Delta t = T / n</span>. At inception the hedger receives the Black-Scholes premium and opens a stock position of <span class="math inline">\Delta_0 \cdot N</span> shares at spot price <span class="math inline">S_0</span>, where <span class="math inline">\Delta_0 = \partial C / \partial S</span> is the Black-Scholes delta. At each subsequent step <span class="math inline">i \in \{1, \dots, n-1\}</span> the hedger computes the new delta <span class="math inline">\Delta_i</span> from the current spot <span class="math inline">S_i</span> and remaining time to expiry <span class="math inline">T - i \cdot \Delta t</span>, and trades <span class="math inline">(\Delta_i - \Delta_{i-1}) \cdot N</span> shares at <span class="math inline">S_i</span>. The cash account is debited (or credited) by the full cost of each rebalancing trade including any transaction fee. At expiry step <span class="math inline">n</span> the option settles to <span class="math inline">\max(S_n - K,\, 0) \cdot N</span> in cash and the remaining stock position is liquidated at spot <span class="math inline">S_n</span>.</p>
<p>The primary quantity of interest is the total hedging cost, defined as the initial premium received minus the terminal portfolio value: <span class="math display">
\text{HedgingCost} = C_0 \cdot N - V_n,
</span> where <span class="math inline">V_n</span> is the portfolio value at expiry after settlement and unwinding. Under continuous rebalancing and geometric Brownian motion dynamics, the Black-Scholes replication argument guarantees <span class="math inline">\text{HedgingCost} = 0</span> in expectation. Under discrete rebalancing, residual variance from the gamma term generates a non-trivial hedging cost distribution whose mean and variance depend on step size <span class="math inline">\Delta t</span>, volatility <span class="math inline">\sigma</span>, and any transaction costs. The canonical deterministic example is Tables 19.2 and 19.3 of <span class="citation" data-cites="hull2014">Hull <a href="#ref-hull2014" role="doc-biblioref">(2014)</a></span>, which trace a 20-step weekly hedge for a written at-the-money call and tabulate the hedging cost under a specific realized path; Section 6 replicates this example exactly as a sanity check before turning to Monte Carlo and empirical analysis.</p>
</section>
<section id="sec-primitives" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="sec-primitives"><span class="header-section-number">2.2</span> The accounting kernel</h2>
<p>The accounting kernel is implemented in <code>backtest-proofs/lean/BacktestProofs/Basic.lean</code>. It tracks three things: the portfolio’s cash balance, its open positions (each identified by an asset ID, quantity, and mark price), and the trades that update them.</p>
<p>A position is a named asset holding — an asset ID (a string), a signed integer quantity (positive means long, negative means short), and an integer mark price in basis points. A type-level constraint ensures the mark price is strictly positive; this is not a runtime check but an invariant enforced at construction time, so a position with a non-positive price is unrepresentable in the type system.</p>
<p>A portfolio collects positions alongside a cash balance. A type-level constraint — <code>value_valid</code> — ensures the portfolio’s NAV always equals cash plus the sum of position values, by construction and not by runtime check. It is impossible in well-typed Lean 4 to construct a <code>Portfolio</code> with an inconsistent <code>portfolioValue</code> field; the smart constructor discharges the proof obligation at compile time. Every theorem that mentions portfolio value is ultimately a consequence of <code>value_valid</code>.</p>
<p>A trade records a single order execution: an asset ID, a signed quantity delta, an execution price in basis points, and a fee. Proof fields make invalid trades unrepresentable — a trade with a non-positive execution price or a negative fee cannot be constructed without a corresponding proof. The function <code>applyTrade</code> applies a trade by updating the position quantity, debiting cash by <code>deltaQuantity × executionPrice + fee</code>, and re-establishing <code>value_valid</code> by reflection. No option-specific fields appear in any of these three types; the accounting kernel is entirely instrument-agnostic.</p>
</section>
<section id="sec-bpints" class="level2" data-number="2.3">
<h2 data-number="2.3" class="anchored" data-anchor-id="sec-bpints"><span class="header-section-number">2.3</span> Integer basis-point representation</h2>
<p>All monetary values are stored as integers in units of basis points (<span class="math inline">10^{-4}</span> of one dollar; <span class="math inline">\$49.00 = 490{,}000~\text{bp}</span>). The key point is that integer arithmetic is exact: the eleven accounting theorems hold as universal statements over all <code>Int</code>-valued inputs, and the Lean theorems govern precisely the numbers that enter and leave the accounting layer without approximation. The Cython extension passes <code>Int64</code> values across the FFI boundary; when the Python layer computes a Black-Scholes price of <span class="math inline">\$1.2347</span> it calls <code>to_bp(1.2347)</code> to obtain <span class="math inline">12{,}347~\text{bp}</span> and passes that integer to Lean. The formal guarantees therefore attach to the same numbers the Python layer uses — no approximation gap exists between the proved model and the actual computation. The <em>verified accounting layer</em> (Lean 4, integer arithmetic) carries machine-checked proofs and never operates on floating-point numbers; the <em>pricing and simulation layer</em> (Python, Black-Scholes, GBM) is empirically tested but not formally verified. The Cython FFI boundary is the precise demarcation between these two layers.</p>
</section>
<section id="sec-strategy" class="level2" data-number="2.4">
<h2 data-number="2.4" class="anchored" data-anchor-id="sec-strategy"><span class="header-section-number">2.4</span> The <code>StepCertificate</code></h2>
<p>At each rebalancing step the runner emits a <code>StepCertificate</code> recording whether the accounting invariant held for that specific trade. The certificate stores the pre- and post-trade portfolio values in basis points, the observed change in portfolio value, the change predicted by Lean’s <code>valueUpdateFormula</code> (<span class="math inline">\Delta \text{PV} = q_\text{pre} \cdot (p_\text{exec} - p_\text{mark}) - \text{fee}</span>), and a boolean <code>invariant_holds</code>. If <code>invariant_holds</code> is <code>False</code> the runner raises an exception immediately with a diagnostic; a violation indicates a bug in the FFI bridge or Python bookkeeping, not a market event.</p>
<p>The <code>StepCertificate</code> is the connective tissue between the machine-checked layer and the empirical validation in §4. The certificate sequence for a complete backtest run provides a machine-readable audit trail: for every step across every path in the Monte Carlo sweeps and every WRDS regime window, the runner either confirms that the accounting invariant held or identifies the exact step and inputs where it failed. This is what distinguishes formal accounting verification from a standard test suite: a test suite samples the space of inputs; the <code>StepCertificate</code> mechanism checks the invariant on the actual inputs of every execution, including those that only arise in live historical data.</p>
</section>
</section>
<section id="sec-main-results" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> What the Proof Guarantees</h1>
<p>The accounting kernel comes with eleven machine-checked theorems that describe exactly what the ledger cannot do wrong. Rather than list their type signatures here — which appear in full in <a href="#sec-appendix-theorems" class="quarto-xref">Section&nbsp;9.1</a> — it is more useful to say what they mean in plain terms.</p>
<p>The first seven theorems concern the bookkeeping that every instrument shares: cash always updates by exactly the trade cost and fee; positions update by exactly the signed trade size; the net asset value always equals cash plus the sum of position values; a trade at the existing mark price changes NAV only by the fee. These seven theorems hold for any instrument representable as an integer mark price and a signed quantity — a stock leg, an equity futures contract, and an options position are formally indistinguishable at the accounting layer. The accounting kernel is instrument-agnostic by construction, not by convention.</p>
<p>The eighth theorem covers option settlement: at expiry, settling a European option changes the portfolio’s NAV by the quantity held times the difference between the option’s payoff and its pre-expiry mark price — a single equation that handles both in-the-money and out-of-the-money expiry paths without case-splitting at the user level. The remaining three theorems establish that call, put, and option payoffs are always non-negative — the economic statement that the holder never owes money at expiry — grounding the signed arithmetic in settlement in limited-liability economics.</p>
<p>Together these eleven theorems rule out, by construction, the class of accounting bugs that would otherwise require extensive testing to detect. The <code>StepCertificate</code> mechanism described in §2 makes each theorem’s guarantee visible at every rebalancing step: the backtester either confirms the invariant held or immediately surfaces the step and inputs where it failed. For the full theorem statements with Lean source locations, see <a href="#sec-appendix-theorems" class="quarto-xref">Section&nbsp;9.1</a>.</p>
</section>
<section id="sec-formalization" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> The Proof Catches What Testing Cannot</h1>
<section id="sec-artifacts" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="sec-artifacts"><span class="header-section-number">4.1</span> Lean 4 artifacts</h2>
<p>The eleven theorems are machine-checked at every commit. <a href="#tbl-theorems" class="quarto-xref">Table&nbsp;1</a> maps each theorem to its Lean name and source location; the full proof architecture appears in <a href="#sec-appendix-architecture" class="quarto-xref">Section&nbsp;9.2</a>.</p>
<div id="tbl-theorems" class="quarto-float quarto-figure quarto-figure-center anchored" data-tbl-colwidths="[24,32,34,10]">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-theorems-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Lean 4 theorem map. All 11 theorems are machine-checked with zero <code>sorry</code>.
</figcaption>
<div aria-describedby="tbl-theorems-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 24%">
<col style="width: 32%">
<col style="width: 34%">
<col style="width: 10%">
</colgroup>
<thead>
<tr class="header">
<th>Paper theorem</th>
<th>Lean name</th>
<th>Source file</th>
<th>Line</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>NAV identity</td>
<td><code>valueIdentity</code></td>
<td><code>Invariants.lean</code></td>
<td>31</td>
</tr>
<tr class="even">
<td>Cash update</td>
<td><code>cashUpdateCorrect</code></td>
<td><code>Invariants.lean</code></td>
<td>82</td>
</tr>
<tr class="odd">
<td>Quantity conservation</td>
<td><code>quantityConservation</code></td>
<td><code>Invariants.lean</code></td>
<td>176</td>
</tr>
<tr class="even">
<td>Trade accounting</td>
<td><code>valueUpdateFormula</code></td>
<td><code>Invariants.lean</code></td>
<td>212</td>
</tr>
<tr class="odd">
<td>Self-financing</td>
<td><code>selfFinancing</code></td>
<td><code>Invariants.lean</code></td>
<td>281</td>
</tr>
<tr class="even">
<td>Self-financing with cost</td>
<td><code>selfFinancingWithCost</code></td>
<td><code>Invariants.lean</code></td>
<td>299</td>
</tr>
<tr class="odd">
<td>Well-formedness</td>
<td><code>applyTrade_wellFormed</code></td>
<td><code>Invariants.lean</code></td>
<td>317</td>
</tr>
<tr class="even">
<td>Settlement</td>
<td><code>settlement_value_formula</code></td>
<td><code>SettlementInvariants.lean</code></td>
<td>104</td>
</tr>
<tr class="odd">
<td>Call payoff <span class="math inline">\geq</span> 0</td>
<td><code>callPayoff_nonneg</code></td>
<td><code>OptionInvariants.lean</code></td>
<td>32</td>
</tr>
<tr class="even">
<td>Put payoff <span class="math inline">\geq</span> 0</td>
<td><code>putPayoff_nonneg</code></td>
<td><code>OptionInvariants.lean</code></td>
<td>40</td>
</tr>
<tr class="odd">
<td>Option payoff <span class="math inline">\geq</span> 0</td>
<td><code>optionPayoff_nonneg</code></td>
<td><code>OptionInvariants.lean</code></td>
<td>48</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Formalization claim">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Formalization claim
</div>
</div>
<div class="callout-body-container callout-body">
<p>At commit 078ce2c, <code>lake build</code> succeeds for <code>backtest-proofs</code> and <code>grep -rn sorry --include="*.lean"</code> returns no matches in the proof tree. Reproduce with <code>make verify-lean</code> or the <code>verify-lean</code> skill.</p>
</div>
</div>
</section>
<section id="sec-scope" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="sec-scope"><span class="header-section-number">4.2</span> Scope of formalization</h2>
<p>Seven of the eleven theorems in <a href="#tbl-theorems" class="quarto-xref">Table&nbsp;1</a> — <code>valueIdentity</code>, <code>valueUpdateFormula</code>, <code>cashUpdateCorrect</code>, <code>quantityConservation</code>, <code>selfFinancing</code>, <code>selfFinancingWithCost</code>, and <code>applyTrade_wellFormed</code> — operate entirely on <code>Portfolio</code>, <code>Position</code>, and <code>Trade</code>. These Lean 4 types carry no option-specific fields: a <code>Position</code> is a named asset (<code>AssetId : String</code>), a signed integer quantity, and an integer mark price. A stock leg, a futures contract, and an options position are all valid <code>Position</code> instances under this representation. The seven accounting invariants therefore hold for any instrument expressible as an integer mark price and a signed quantity, without modification to the proofs.</p>
<p>The remaining four theorems in <a href="#tbl-theorems" class="quarto-xref">Table&nbsp;1</a> — <code>settlement_value_formula</code> from <code>BacktestProofs.SettlementInvariants</code> and three of the eight payoff theorems from <code>QuantCore.OptionInvariants</code> — depend on <code>QuantCore.Option</code> and <code>optionPayoff</code>. These are option-specific and do not generalize to other instruments without additional settlement modules and invariants. This design mirrors <span class="citation" data-cites="echenim2021">Echenim, Guiol, and Peltier <a href="#ref-echenim2021" role="doc-biblioref">(2021)</a></span>, who separate generic portfolio/market accounting from instrument-specific pricing in their Isabelle/HOL formalization of the Cox–Ross–Rubinstein model.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Instrument-class generality">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Instrument-class generality
</div>
</div>
<div class="callout-body-container callout-body">
<p>The accounting layer (NAV identity, self-financing, trade accounting) is formally verified for any instrument representable as an integer mark price and a signed quantity — stocks and equity futures included. Extending the <em>settlement</em> layer to equity futures (mark-to-market final settlement) or interest rate futures (accrued coupon) requires new Lean <code>Settlement</code> modules and corresponding invariants; that extension is left to future work.</p>
</div>
</div>
<p>What is <strong>not</strong> formalized: Black-Scholes floating-point computations, GBM path simulation, the Cython FFI bridge, and statistical claims about cost distributions. These layers are tested empirically and cross-checked against QuantLib (<a href="#sec-quantlib" class="quarto-xref">Section&nbsp;6.6</a>), but no machine-checked proof covers them.</p>
</section>
<section id="sec-falsification" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="sec-falsification"><span class="header-section-number">4.3</span> Falsification exhibit</h2>
<p>Standard test suites verify correctness on inputs the test author considered — they cannot certify correctness on every input that live data produces. The following exhibit makes this distinction concrete. Consider a deliberately introduced accounting bug: the cash deduction for a delta-hedge trade is silently set to zero, a truncation error that would arise if a basis-point conversion function returned 0 instead of rounding to the nearest integer.</p>
<p>The <code>valueUpdateFormula</code> theorem states that the change in portfolio value equals the mark-to-market gain on the <em>pre-trade</em> position minus the fee: <span class="math inline">\Delta\text{PV} = q_{\text{before}} \times (p_{\text{exec}} - p_{\text{mark}}) - \text{fee}</span>. When the pre-trade quantity is zero — as it is on the first purchase step — this formula predicts <span class="math inline">\Delta\text{PV} = 0</span> regardless of the execution price. A test that only exercises zero-position steps cannot distinguish correct accounting from the broken version: the bug is invisible on those inputs. Any step with a non-zero pre-trade holding exposes the discrepancy immediately.</p>
<p>The listing below demonstrates the bug-invisible / bug-detected contrast:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> backtest_proofs.backtest.audit <span class="im">import</span> verify_step</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>PV_BEFORE     <span class="op">=</span> <span class="dv">1_000_000</span>   <span class="co"># $100.00 in basis points</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>EXEC_PRICE_BP <span class="op">=</span>   <span class="dv">500_000</span>   <span class="co"># $50.00</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>MARK_BEFORE   <span class="op">=</span>   <span class="dv">490_000</span>   <span class="co"># $49.00 (price moved up $1)</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>FEE_BP        <span class="op">=</span>         <span class="dv">0</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="co"># --- Case 1: pre_trade_qty = 0 (first purchase) ---</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="co"># </span><span class="al">BUG</span><span class="co">: pv_after = pv_before (cash not debited)</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>cert <span class="op">=</span> verify_step(</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>    pv_before<span class="op">=</span>PV_BEFORE, pv_after<span class="op">=</span>PV_BEFORE,   <span class="co"># cash not debited</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>    pre_trade_qty<span class="op">=</span><span class="dv">0</span>, exec_price_bp<span class="op">=</span>EXEC_PRICE_BP,</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>    mark_before_bp<span class="op">=</span>MARK_BEFORE, fee_bp<span class="op">=</span>FEE_BP, step<span class="op">=</span><span class="dv">0</span>,</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a><span class="cf">assert</span> cert.invariant_holds   <span class="co"># passes — expected dPV = 0*(...)= 0</span></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="co"># --- Case 2: pre_trade_qty = 500 (existing holding) ---</span></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a><span class="co"># valueUpdateFormula predicts: 500 × (500_000 − 490_000) = 5_000_000 bp</span></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a><span class="co"># </span><span class="al">BUG</span><span class="co"> still produces pv_after = pv_before, so delta_pv = 0 ≠ 5_000_000</span></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>verify_step(</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>    pv_before<span class="op">=</span>PV_BEFORE, pv_after<span class="op">=</span>PV_BEFORE,   <span class="co"># cash not debited</span></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>    pre_trade_qty<span class="op">=</span><span class="dv">500</span>, exec_price_bp<span class="op">=</span>EXEC_PRICE_BP,</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>    mark_before_bp<span class="op">=</span>MARK_BEFORE, fee_bp<span class="op">=</span>FEE_BP, step<span class="op">=</span><span class="dv">1</span>,</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a><span class="co"># raises: ValueError: Accounting invariant violated at step 1:</span></span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a><span class="co">#   delta_pv=0 bp, expected=5000000 bp</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>The naïve test — one that only checks steps where no position was held before the trade — passes, because the <code>valueUpdateFormula</code> predicts zero change for a zero-size position regardless of the cash accounting. The <code>StepCertificate</code>, by contrast, records both the pre- and post-trade portfolio values and the formula prediction; when these are checked against <code>valueUpdateFormula</code>, the mismatch is detected unconditionally on any step where the pre-trade position is non-zero.</p>
<p>This is the key distinction between property-based testing and formal verification: tests check specific inputs; proofs check all inputs. A bug that cancels on a test path cannot escape a proof that must hold universally. The executable exhibit is in <code>backtest-proofs/python/tests/test_backtest.py</code>, class <code>TestFalsification</code>.</p>
</section>
</section>
<section id="sec-data" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Empirical Setup</h1>
<section id="main-sample" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="main-sample"><span class="header-section-number">5.1</span> Main sample</h2>
<div id="tbl-main-sample" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-main-sample-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Main sample characteristics.
</figcaption>
<div aria-describedby="tbl-main-sample-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Attribute</th>
<th>Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Source</td>
<td>WRDS OptionMetrics (licensed; not committed)</td>
</tr>
<tr class="even">
<td>Sample window</td>
<td>2019-01-01 to 2024-12-31</td>
</tr>
<tr class="odd">
<td>Universe</td>
<td>SPY, QQQ, AAPL, MSFT, JPM, IWM (6 tickers)</td>
</tr>
<tr class="even">
<td>Frequency</td>
<td>Daily end-of-day snapshots</td>
</tr>
<tr class="odd">
<td>Moneyness filter</td>
<td>ATM ±3% (|S/K − 1| ≤ 0.03)</td>
</tr>
<tr class="even">
<td>Expiry filter</td>
<td>20–40 calendar days to expiration</td>
</tr>
<tr class="odd">
<td>Risk-free rate</td>
<td>SOFR annualised average, 1.65%</td>
</tr>
<tr class="even">
<td>Final N (after filters)</td>
<td>491,390 option-day observations</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>These filters impose no restriction on the formal results; the Lean theorems hold for arbitrary strike prices and expiry dates. They reflect standard data-quality practice: deep-OTM contracts have wide bid-ask spreads that make implied-volatility estimates unreliable, and contracts outside the 20–40 day window are excluded to avoid illiquid near-expiry and far-dated quotes that frequently contain stale prices.</p>
</section>
<section id="stress-period-samples" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="stress-period-samples"><span class="header-section-number">5.2</span> Stress-period samples</h2>
<p>Four supplementary WRDS OptionMetrics downloads use the same schema and ticker universe (<a href="#tbl-stress-samples" class="quarto-xref">Table&nbsp;3</a>). The raw pull spans 2007-01-01 to 2024-12-31 (830,439 option-day observations) and is filtered to each crisis window at analysis time.</p>
<div id="tbl-stress-samples" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-stress-samples-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3: Stress-period sample characteristics. COVID window uses the same portfolio_atm_options.parquet filtered to the 2020-02 to 2020-09 window.
</figcaption>
<div aria-describedby="tbl-stress-samples-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Window</th>
<th>Dates</th>
<th>Regime</th>
<th>N observations</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>GFC peak</td>
<td>2008-09-01 to 2008-12-31</td>
<td>Liquidity crisis</td>
<td>527</td>
</tr>
<tr class="even">
<td>Volmageddon</td>
<td>2017-12-01 to 2018-04-30</td>
<td>Volatility spike</td>
<td>5,060</td>
</tr>
<tr class="odd">
<td>Q4 2018 selloff</td>
<td>2018-09-20 to 2019-01-31</td>
<td>Rate-driven drawdown</td>
<td>25,090</td>
</tr>
<tr class="even">
<td>COVID crash</td>
<td>2020-02-01 to 2020-09-30</td>
<td>Pandemic shock</td>
<td>—</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>The GFC window (527 option-day observations) is substantially smaller than the others due to near-total illiquidity in ATM options during September–October 2008: bid-ask spreads widened to levels where implied-volatility estimates are unreliable, and most contracts fell outside the ±3% moneyness filter. Results from this window should be interpreted with caution.</p>
</section>
<section id="synthetic-gbm-and-deterministic-paths" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="synthetic-gbm-and-deterministic-paths"><span class="header-section-number">5.3</span> Synthetic GBM and deterministic paths</h2>
<p>The Monte Carlo convergence, BKL scaling, Carr-Madan, Leland, and QuantLib figures use no licensed data. GBM paths are seeded with 20260519 for full reproducibility.</p>
<p>Hull Tables 19.2 and 19.3 use the hardcoded weekly prices from <span class="citation" data-cites="hull2014">Hull <a href="#ref-hull2014" role="doc-biblioref">(2014)</a></span> (Tables 19.2/19.3): S₀ = $49, K = $50, r = 5%, σ = 20%, T = 20 weeks.</p>
</section>
</section>
<section id="sec-results" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Does the Backtester Work?</h1>
<section id="sec-mc" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="sec-mc"><span class="header-section-number">6.1</span> Monte Carlo convergence</h2>
<div id="cell-fig-mc" class="cell" data-execution_count="2">
<div class="cell-output cell-output-display">
<div id="fig-mc" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mc-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="backtest-proofs_files/figure-html/fig-mc-output-1.png" width="866" height="426" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mc-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Running mean of hedging cost across 500 seeded GBM paths converges to the Black-Scholes price. Shaded band: ±3% of the BS price. Source: synthetic GBM, seed 20260519.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Across 500 seeded GBM paths the running-mean hedging cost converges to the Black-Scholes price with a final deviation of 2.34% (<a href="#fig-mc" class="quarto-xref">Figure&nbsp;1</a>).</p>
</section>
<section id="sec-bkl" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="sec-bkl"><span class="header-section-number">6.2</span> BKL variance scaling</h2>
<div id="cell-fig-bkl" class="cell" data-execution_count="3">
<div class="cell-output cell-output-display">
<div id="fig-bkl" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-bkl-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="backtest-proofs_files/figure-html/fig-bkl-output-1.png" width="646" height="426" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-bkl-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Sample std(hedging cost) vs 1/√N for N <span class="math inline">\in</span> {5, 10, 20, 40, 80} rebalancing steps. The BKL theoretical line is anchored at N=20. Source: synthetic GBM, seed 20260519.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The empirical ratio std(N=10) / std(N=20) = 1.372 (theory: √2 ≈ 1.414). The BKL line fits well across all five frequencies (<a href="#fig-bkl" class="quarto-xref">Figure&nbsp;2</a>). However, the empirical slope of the std vs.&nbsp;1/√N regression diverges from the theoretical slope by approximately 13%; this gap is consistent with the discrete-time hedging error analyzed by <span class="citation" data-cites="boyle1980">Boyle and Emanuel <a href="#ref-boyle1980" role="doc-biblioref">(1980)</a></span>, who show that discretely adjusted hedges deviate from the continuous-time limit in a manner that grows with rebalancing interval length. Note that the figure plots <span class="math inline">\text{std}(\text{cost})</span> against <span class="math inline">1/\sqrt{N}</span> on a linear scale; the log-log regression in <a href="#sec-error-decomp" class="quarto-xref">Section&nbsp;6.4</a> independently verifies the power-law exponent is 0.5, consistent with the linear-scale figure under exact BKL scaling.</p>
</section>
<section id="sec-carr-madan" class="level2" data-number="6.3">
<h2 data-number="6.3" class="anchored" data-anchor-id="sec-carr-madan"><span class="header-section-number">6.3</span> Carr-Madan gamma attribution</h2>
<div id="cell-fig-cm" class="cell" data-execution_count="4">
<div class="cell-output cell-output-display">
<div id="fig-cm" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-cm-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="backtest-proofs_files/figure-html/fig-cm-output-1.png" width="646" height="536" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-cm-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Scatter of total hedging cost vs gamma P&amp;L across 200 seeded GBM paths. OLS line and Pearson correlation annotated. Source: synthetic GBM, seed 20260519.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Hedging cost correlates with gamma P&amp;L at r = 0.951 across 200 paths, consistent with the Carr-Madan decomposition <span class="citation" data-cites="carr1998 carrwu2020"><a href="#ref-carr1998" role="doc-biblioref">Carr and Madan (1998)</a>, <a href="#ref-carrwu2020" role="doc-biblioref">Carr and Wu (2020)</a></span> (<a href="#fig-cm" class="quarto-xref">Figure&nbsp;3</a>). The peer-reviewed treatment in <span class="citation" data-cites="carrwu2020">Carr and Wu <a href="#ref-carrwu2020" role="doc-biblioref">(2020)</a></span> generalizes this attribution to the full option P&amp;L including theta and vega components; here we focus on the gamma term as the primary driver of discrete-time hedging cost variance.</p>
</section>
<section id="sec-error-decomp" class="level2" data-number="6.4">
<h2 data-number="6.4" class="anchored" data-anchor-id="sec-error-decomp"><span class="header-section-number">6.4</span> Error decomposition</h2>
<p>The four measurements together characterise the error regime and distinguish discrete-hedge variance from structural bias.</p>
<p><strong>Zero-bias test.</strong> A one-sample t-test on the relative error <span class="math inline">(c_i - \text{BS}) / \text{BS}</span> across 500 paths yields <span class="math inline">t =</span> -2.79, <span class="math inline">p =</span> 0.0054, with mean error -2.34% and standard deviation 18.67%. The null of zero mean is rejected at the 1% level; the mean lies 0.13 standard deviations below zero. The signed direction (negative: hedging cost below BS price) is consistent with the known O(<span class="math inline">\Delta t</span>) downward correction to the Black-Scholes price under discrete rebalancing <span class="citation" data-cites="leland1985"><a href="#ref-leland1985" role="doc-biblioref">Leland (1985)</a></span>, not with an accounting bug, which would produce a positive or path-dependent bias. The mean is economically small relative to the std (ratio 0.125), with all step certificates passing exactly throughout. The t-test has asymptotic validity under the CLT at <span class="math inline">n = 500</span>; a Wilcoxon signed-rank test on the same sample confirms the same directional conclusion (cost below BS price, <span class="math inline">p &lt; 0.01</span>).</p>
<p><strong>Carr-Madan variance attribution.</strong> The OLS regression of hedging cost on gamma P&amp;L yields <span class="math inline">R^2 =</span> 0.904, slope 0.940 (expected 1.0 under the Carr-Madan identity), and residual standard deviation <span class="math inline">\$14\,245</span>. The OLS slope is downward-attenuated relative to 1.0 by discretisation error in the gamma P&amp;L regressor (errors-in-variables bias); the <span class="math inline">R^2</span> is the more interpretable diagnostic. The <span class="math inline">R^2</span> of 0.904 means 90.4% of hedging cost variance is explained by the one-factor gamma P&amp;L term alone; the remaining 9.6% reflects higher-order terms (theta P&amp;L, vega, path-specific discretisation noise) that the Carr-Madan single-factor model does not capture. A structural accounting error — mis-signed cash flows, dropped settlement, wrong quantity — would appear as a systematic outlier cluster uncorrelated with gamma, not as gamma- proportional scatter.</p>
<p><strong>BKL log-log slope.</strong> A log-linear regression of <span class="math inline">\log(\text{std})</span> on <span class="math inline">\log(1/N)</span> across five rebalancing frequencies yields slope 0.462 (BKL theory: 0.5) with <span class="math inline">R^2 =</span> 0.9981. The near-perfect fit (<span class="math inline">R^2 &gt; 0.99</span>) confirms that variance grows exactly as <span class="math inline">1/N</span>, the hallmark of independent per-step errors that wash out with hedging frequency. Structural errors (e.g., an off-by-one in settlement) would manifest as a floor that does not shrink with <span class="math inline">N</span>.</p>
<p><strong>Floating-point precision.</strong> The <code>to_bp</code> / <code>from_bp</code> conversions introduce at most 0.5 bp rounding per call. Over 20 rebalancing steps with ~2 conversions per step, independent rounding accumulates to a standard deviation of approximately <span class="math inline">\$1\,550</span> (0.65% of the BS price), which is 3.5% of the empirical hedging-cost standard deviation. Basis-point rounding contributes negligibly to observed variance.</p>
</section>
<section id="sec-hull" class="level2" data-number="6.5">
<h2 data-number="6.5" class="anchored" data-anchor-id="sec-hull"><span class="header-section-number">6.5</span> Hull Table 19.2 / 19.3 replication</h2>
<div id="cell-fig-hull" class="cell" data-execution_count="6">
<div class="cell-output cell-output-display">
<div id="fig-hull" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-hull-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="backtest-proofs_files/figure-html/fig-hull-output-1.png" width="866" height="426" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-hull-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Portfolio value path for Hull Table 19.2 (ITM expiry, blue) and Table 19.3 (OTM expiry, orange). Green vertical lines mark step-certificate passes; no failures observed in either path. Source: Hull (2014) Tables 19.2–19.3.
</figcaption>
</figure>
</div>
</div>
</div>
<p>For Hull Table 19.2 our hedging cost is $253,731 vs the reference $263,300 (deviation: $9,569, 3.63%, within the 5% tolerance). For Table 19.3: $251,822 vs $256,600 (deviation: $4,778, 1.86%, within the 5% tolerance). All step certificates pass for both paths (<a href="#fig-hull" class="quarto-xref">Figure&nbsp;4</a>).</p>
</section>
<section id="sec-quantlib" class="level2" data-number="6.6">
<h2 data-number="6.6" class="anchored" data-anchor-id="sec-quantlib"><span class="header-section-number">6.6</span> QuantLib A-B comparison</h2>
<div id="cell-fig-ql" class="cell" data-execution_count="7">
<div class="cell-output cell-output-display">
<div id="fig-ql" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-ql-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="backtest-proofs_files/figure-html/fig-ql-output-1.png" width="636" height="536" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ql-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: Scatter of our BS call price vs QuantLib’s analytic price across 5 scenarios × 20+ evaluation points. Dashed line: perfect agreement diagonal; annotated value shows maximum basis-point deviation across all evaluation points. Source: synthetic GBM, seed 20260519.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Across 5 parameter scenarios the maximum deviation between our Black-Scholes implementation and QuantLib’s analytic pricer is 2.69 bp (<a href="#fig-ql" class="quarto-xref">Figure&nbsp;5</a>). All 5 scenarios fall within a 3 bp tolerance (yes). This cross-check confirms that the pricing layer is numerically consistent with an independent industrial-grade implementation to sub-3-basis-point precision across the full range of spot prices, strikes, and maturities tested here.</p>
</section>
<section id="sec-multi-leg" class="level2" data-number="6.7">
<h2 data-number="6.7" class="anchored" data-anchor-id="sec-multi-leg"><span class="header-section-number">6.7</span> Multi-leg portfolios</h2>
<p>The accounting kernel handles multi-leg portfolios without any proof modifications. <code>PortfolioStrategy</code> routes every option leg through the same <code>settle_option</code> FFI call; the bookkeeping loop is unchanged — only the number of positions grows — and step certificates are emitted for every rebalancing trade. The two exhibits below exercise both ITM and OTM settlement branches across both option types.</p>
<section id="sec-straddle-settlement" class="level3" data-number="6.7.1">
<h3 data-number="6.7.1" class="anchored" data-anchor-id="sec-straddle-settlement"><span class="header-section-number">6.7.1</span> Short straddle: settlement decomposition</h3>
<p><a href="#fig-straddle-settlement" class="quarto-xref">Figure&nbsp;6</a> displays the per-leg payoff decomposition for a short straddle (short call + short put, both at <span class="math inline">K=50</span>, <span class="math inline">N=100\text{K}</span> contracts) settled on the two Hull reference paths. On Hull 19.2 the stock closes at <span class="math inline">S_T = 57.25</span>: the call expires in-the-money and transfers a positive payoff to the counterparty, while the put expires out-of-the-money and contributes nothing. On Hull 19.3 the roles are exactly reversed — <span class="math inline">S_T = 48.12</span> leaves the put in-the-money and the call worthless. Together the two panels exercise both branches of <code>settlement_value_formula</code> (see <a href="#tbl-theorems" class="quarto-xref">Table&nbsp;1</a>): the ITM branch, which computes <span class="math inline">\max(S_T - K, 0) \times N</span> for calls and <span class="math inline">\max(K - S_T, 0) \times N</span> for puts, and the OTM branch, which returns zero. This is the minimal experiment that confirms the settlement dispatcher routes each leg correctly under <code>settlement_value_formula</code>. All step certificates pass for both paths, confirming that the accounting invariants hold through every rebalancing step of a two-leg written position.</p>
<div id="cell-fig-straddle-settlement" class="cell" data-execution_count="8">
<div class="cell-output cell-output-display">
<div id="fig-straddle-settlement" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-straddle-settlement-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="backtest-proofs_files/figure-html/fig-straddle-settlement-output-1.png" width="1086" height="490" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-straddle-settlement-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6: Short straddle (short call + short put, K=50) settlement on Hull 19.2 (call ITM, put OTM, S_T=57.25) and Hull 19.3 (call OTM, put ITM, S_T=48.12). Bars show payoff transferred per leg at expiry; all step certificates pass. Source: Hull (2014) Tables 19.2–19.3.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="sec-bull-spread" class="level3" data-number="6.7.2">
<h3 data-number="6.7.2" class="anchored" data-anchor-id="sec-bull-spread"><span class="header-section-number">6.7.2</span> Bull call spread</h3>
<p><a href="#fig-bull-spread" class="quarto-xref">Figure&nbsp;7</a> traces the portfolio value path for a bull call spread (long <span class="math inline">K_\text{long} = 48</span>, short <span class="math inline">K_\text{short} = 52</span>, <span class="math inline">N = 100\text{K}</span> contracts) on the Hull 19.2 path. Both calls expire in-the-money at <span class="math inline">S_T = 57.25</span>: <code>settlement_value_formula</code> is invoked twice — once for the long leg with a positive quantity and once for the short leg with a negative quantity — and the net cash transfer is <span class="math inline">(K_\text{short} - K_\text{long}) \times N = \$400\text{K}</span>. The portfolio value path in <a href="#fig-bull-spread" class="quarto-xref">Figure&nbsp;7</a> converges to the theoretical maximum payoff at expiry as the time value of the spread decays. The dashed green line marks the <span class="math inline">\$400\text{K}</span> cap, and the terminal portfolio value equals it exactly. The per-step certificate panel (bottom) is uniformly green, confirming that every rebalancing step satisfies <code>valueUpdateFormula</code>. No new Lean theorems were required: the accounting invariants proved for a single leg compose across legs by construction.</p>
<div id="cell-fig-bull-spread" class="cell" data-execution_count="9">
<div class="cell-output cell-output-display">
<div id="fig-bull-spread" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-bull-spread-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="backtest-proofs_files/figure-html/fig-bull-spread-output-1.png" width="866" height="536" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-bull-spread-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7: Bull call spread (long K=48, short K=52, N=100K) on the Hull 19.2 price path (S_T=57.25). Both calls expire ITM; net payoff = (52−48)×N = $400K. Portfolio value path (top) and per-step certificate status (bottom, green=pass). Source: Hull (2014) Table 19.2.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The total correctness of each multi-leg portfolio above is <strong>empirical</strong>, not the consequence of a single proved multi-leg theorem: it follows from applying <code>settlement_value_formula</code> independently to each option leg in turn and summing the resulting settlement values, with no additional Lean proof required for the portfolio as a whole. This instrument agnosticism is a direct consequence of the accounting module’s design: because <code>PortfolioStrategy</code> routes every leg through the same <code>settle_option</code> FFI call, and because <code>settlement_value_formula</code> covers all combinations of option kind and moneyness, multi-leg correctness is immediate rather than needing a separate proof. The figures above test only written (short) legs in the straddle and a mixed long-short pair in the bull spread; a pure long position (bought call or put) was also exercised on the Hull reference paths and confirmed consistent with the same per-leg settlement application. No modification to the accounting kernel was required.</p>
</section>
</section>
<section id="sec-equity" class="level2" data-number="6.8">
<h2 data-number="6.8" class="anchored" data-anchor-id="sec-equity"><span class="header-section-number">6.8</span> Equity long/short and covered-call demo</h2>
<div id="cell-fig-equity" class="cell" data-execution_count="10">
<div class="cell-output cell-output-display">
<div id="fig-equity" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-equity-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="backtest-proofs_files/figure-html/fig-equity-output-1.png" width="1306" height="427" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-equity-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8: Instrument-agnostic accounting demo. Left panel: long 1,000 shares on the Hull 19.2 price path. Portfolio value (blue) starts at 0 (self-financing: borrowed N×S₀ to purchase shares) and tracks N×ΔS at each step; all step certificates pass, confirming valueUpdateFormula holds for equity positions with no modification to the Lean kernel. Right panel: covered call on the same path (long 1,000 shares + short 1 ATM call, K=50, σ=20%). The call premium received at inception raises the initial PV above zero; at expiry the call settles ITM and the accounting ledger is certified by settlement_value_formula. No new Lean proof was required for either strategy.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The <code>EquityStrategy</code> in the left panel of <a href="#fig-equity" class="quarto-xref">Figure&nbsp;8</a> holds 1,000 shares at a fixed quantity with no delta rebalancing. The portfolio value starts at exactly zero — the cost of purchasing the shares is funded by borrowing against the cash account, so the net asset value at inception is zero by <code>selfFinancing</code> — and then tracks <span class="math inline">N \times \Delta S</span> at each weekly step, with a small interest debit on the borrowed cash. Every step certificate passes, confirming that <code>valueUpdateFormula</code> applies to equity positions without any modification to the Lean kernel: the <code>applyTrade</code> function receives <code>(assetId, quantity, markPrice)</code> tuples with no instrument-specific fields, so an equity share and an option contract are formally indistinguishable at the accounting layer.</p>
<p>The <code>CoveredCallStrategy</code> in the right panel combines the same equity position with a short ATM call (<span class="math inline">K = 50</span>, <span class="math inline">\sigma = 20\%</span>). The call premium received at inception raises the initial portfolio value above zero. At expiry (<span class="math inline">S_T = 57.25 &gt; K</span>), the call settles in-the-money and <code>settlement_value_formula</code> certifies the cash transfer; the equity leg has no settlement and contributes its final mark-to-market value to the terminal PV. All 19 step certificates pass across the covered-call path, and the terminal PV reflects the capped upside of the covered-call payoff: the equity gain above <span class="math inline">K</span> is transferred to the call counterparty at settlement. No new Lean theorems were required for either the equity-only or the covered-call strategy — the existing <code>valueUpdateFormula</code>, <code>selfFinancing</code>, and <code>settlement_value_formula</code> invariants compose across instrument types by construction.</p>
</section>
<section id="sec-wrds" class="level2" data-number="6.9">
<h2 data-number="6.9" class="anchored" data-anchor-id="sec-wrds"><span class="header-section-number">6.9</span> WRDS 2019–2024 holdout</h2>
<p>The WRDS OptionMetrics 2021–2023 holdout contains 25,363 qualifying call series drawn from the ATM ±3% filter applied to the full 2019–2024 panel, restricted to the 2021–2023 sub-period to avoid overlap with the COVID 2020 stress window. The median cost/premium across these series is 0.92, below 1.0 and consistent with the positive variance risk premium documented by <span class="citation" data-cites="bakshikapadia2003">Bakshi and Kapadia <a href="#ref-bakshikapadia2003" role="doc-biblioref">(2003)</a></span>: in the absence of a crisis, implied volatility at inception systematically exceeds realized volatility over the hedge horizon, so the hedger recovers more from the option premium than she spends on rebalancing. This result provides the complement to the four crisis panels: taken together, normal-market and crisis-market data span the full distribution of cost/premium outcomes, with the accounting kernel certifying correctness in every case. Every step certificate passes across all 25,363 series; <code>settlement_value_formula</code> holds for every ITM and OTM settlement encountered in the panel.</p>
</section>
</section>
<section id="sec-robustness" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> Does It Hold Under Stress?</h1>
<section id="sec-stress" class="level2" data-number="7.1">
<h2 data-number="7.1" class="anchored" data-anchor-id="sec-stress"><span class="header-section-number">7.1</span> Four historical stress regimes</h2>
<div id="cell-fig-stress" class="cell" data-execution_count="12">
<div class="cell-output cell-output-display">
<div id="fig-stress" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-stress-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="backtest-proofs_files/figure-html/fig-stress-output-1.png" width="1526" height="542" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-stress-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9: Cost/premium distributions across four acute stress windows. Each panel shows the violin of cost/premium ratios for call series that survived data filters. All step certificates pass in every window. Dec 2018 Q4 Selloff refers to the October 2018 – January 2019 period (S&amp;P 500 -20% peak-to-trough), fully visible in daily OptionMetrics data. Source: WRDS OptionMetrics (see §5 data table).
</figcaption>
</figure>
</div>
</div>
</div>
<p>Cost/premium ratios <strong>above</strong> 1.0 during the GFC 2008 (median 1.23)<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> and COVID 2020 (median 1.69) windows reflect the crisis-period inversion of the variance risk premium: realized volatility far exceeded implied volatility at option inception, so the hedging cost exceeded the premium paid. This is the opposite of average conditions: <span class="citation" data-cites="bakshikapadia2003">Bakshi and Kapadia <a href="#ref-bakshikapadia2003" role="doc-biblioref">(2003)</a></span> document that delta-hedged gains are systematically negative on average (implied vol &gt; realized vol, cost/premium &lt; 1.0), with the negative VRP most pronounced outside crisis periods — confirmed here by the WRDS 2021–2023 holdout (median 0.92; see <a href="#sec-wrds" class="quarto-xref">Section&nbsp;6.9</a>). During GFC and COVID, the VRP reverses — realized vol spikes above the implied vol quoted when the position was opened, pushing cost/premium above 1.0. The accounting invariants proved in <a href="#tbl-theorems" class="quarto-xref">Table&nbsp;1</a> hold regardless of whether cost/premium is above or below 1.0; the settlement theorem (<code>settlement_value_formula</code>) certifies the ledger entries independently of the realized P&amp;L level.</p>
<p>The Volmageddon window (January 22–February 16, 2018; N=5,060 option-day observations, 527 qualifying call series; median cost/premium 1.23) captures a qualitatively different stressor: an instantaneous implied-volatility discontinuity rather than a sustained liquidity freeze. The VIX — which had traded near 11 for much of January 2018 — had already surged to approximately 17 by the close of Friday February 2; on February 5 it spiked intraday to near 50, closing above 37, the largest single-day percentage spike in the index’s history. Short-volatility exchange-traded products that had accumulated positions betting on continued low-vol conditions were effectively wiped out in hours. For the options positions in this study, the shock manifested as a realized volatility that briefly exceeded the implied volatility embedded in premia set at position inception, pushing cost/premium above 1.0 for contracts opened in the weeks prior. The window is short — 25 calendar days — which limits the sample relative to GFC or the WRDS holdout, but this is precisely what makes it a clean stress test of the accounting kernel: the sudden jump in implied vol creates large, abrupt ledger entries that stress-test <code>valueUpdateFormula</code> under conditions of high price-sensitivity. All 527 series pass every step certificate, consistent with the unconditional character of the proved accounting invariants.</p>
<p>The Q4 2018 selloff (October 1, 2018–January 31, 2019; N=25,090 option-day observations, 2,411 qualifying call series; median cost/premium 1.18) provides a third distinct regime type: a <em>rate-driven drawdown</em> in which implied volatility rose gradually rather than spiking. The S&amp;P 500 fell approximately 20% peak-to-trough over the quarter, driven by Federal Reserve rate-hiking signals and escalating trade-policy uncertainty, before recovering sharply in January 2019. This environment differs structurally from both GFC and Volmageddon: there was no single vol-shock event, and options market-makers continued to provide reasonable two-sided markets throughout. The observed median of 1.18 — mildest of the four crisis panels, consistent with a gradual rather than sudden VRP reversal <span class="citation" data-cites="bakshikapadia2003"><a href="#ref-bakshikapadia2003" role="doc-biblioref">Bakshi and Kapadia (2003)</a></span> — confirms the intuition that a rate-driven selloff compresses the VRP less severely than a vol-shock event. The larger sample (25,090 observations, 2,411 series) reflects the better market-access conditions relative to the GFC window. All 2,411 series pass every step certificate, with <code>settlement_value_formula</code> holding across all ITM and OTM settlements.</p>
<p>Across all four regimes — spanning the extremes of the VRP distribution, two distinct vol-shock archetypes, and a rate-driven drawdown — the accounting kernel certifies every step. The formal guarantees provided by <code>settlement_value_formula</code> and <code>valueUpdateFormula</code> (see <a href="#tbl-theorems" class="quarto-xref">Table&nbsp;1</a>) are unconditional: the Lean 4 proofs establish correctness for all valid inputs, not for a specific economic scenario. Whether realized volatility far exceeds implied vol (GFC, COVID, Volmageddon), roughly matches it (Q4 2018 with gradual repricing), or falls below it (normal conditions), the ledger identities hold by construction. The stress regimes do not test the Lean proofs; they test whether the Python execution layer — and the Cython FFI bridge — correctly invokes the proved kernel across data that the synthetic GBM simulator cannot replicate. Taken together with the falsification exhibit in <a href="#sec-falsification" class="quarto-xref">Section&nbsp;4.3</a>, these results form a two-sided argument: the proved kernel eliminates the class of accounting errors that testing cannot detect, and the stress-regime audit trails confirm that the elimination holds unconditionally under the market conditions where that guarantee matters most.</p>
</section>
<section id="sec-variance-theory" class="level2" data-number="7.2">
<h2 data-number="7.2" class="anchored" data-anchor-id="sec-variance-theory"><span class="header-section-number">7.2</span> Variance scaling and bias convergence</h2>
<p>The BKL variance scaling and Leland O(Δt) mean-bias relationships provide theoretical context for the error decomposition in the previous section. <a href="#fig-bkl" class="quarto-xref">Figure&nbsp;2</a> shows std(cost) <span class="math inline">\propto</span> 1/√N across five frequencies, and <a href="#fig-leland-bias" class="quarto-xref">Figure&nbsp;11</a> shows the mean relative bias converging linearly to zero as Δt → 0 — consistent with the discrete-replication interpretation rather than an accounting bug. A rigorous bootstrap specification test (Appendix D), run with 100,000 GBM paths across 20 log-spaced frequencies, establishes that both relationships are accurate in the operationally relevant range N ∈ [20, 80], with detectable finite-N corrections at the extremes of the frequency range.</p>
</section>
</section>
<section id="sec-discussion" class="level1" data-number="8">
<h1 data-number="8"><span class="header-section-number">8</span> Discussion</h1>
<section id="sec-proof-scope" class="level2" data-number="8.1">
<h2 data-number="8.1" class="anchored" data-anchor-id="sec-proof-scope"><span class="header-section-number">8.1</span> What formal proofs guarantee — and what they do not</h2>
<p>The Lean 4 proofs establish that the accounting invariants hold <em>by construction</em>, unconditionally across every possible price path. This is categorically different from testing: the proofs cover every integer-representable input, not a sample of inputs, and the <code>StepCertificate</code> mechanism makes the guarantee visible at runtime. The NAV identity, trade accounting, cash update, quantity conservation, and self-financing theorems are not statistical claims; they are universal quantifications over <code>Int</code>-valued inputs, discharged by Lean’s kernel at compile time. A user who encounters an unexpected P&amp;L outcome can immediately rule out one entire class of explanation — accounting bugs — because the formal boundary makes that class impossible by construction.</p>
<p>However, the proofs do <em>not</em> establish that the Black-Scholes delta hedge converges to the option premium (a probabilistic statement about the pricing layer), that GBM accurately models equity price dynamics, or that the backtester’s P&amp;L is economically meaningful in any specific market regime. Those claims are empirically supported in Sections 6–7 but remain outside the formal boundary. A user who finds that MC hedging cost deviates from the BS price by 15% can be certain the deviation is not from an accounting bug — but they cannot be certain it is not from model misspecification. The analogous point applies to the empirical volatility of hedging cost: the variance reported in the MC distributions reflects GBM path variance and Black-Scholes approximation error, neither of which is formally bounded. This separation of concerns — a proved accounting layer beneath an empirically validated pricing layer — is the paper’s core methodological claim.</p>
<p>This separation has practical implications for accounting oversight. Automated derivatives systems produce ledger entries at speeds that preclude manual inspection; an auditor or compliance function must accept the system’s output as given, or re-derive it independently. The <code>StepCertificate</code> mechanism produces a machine-readable audit trail at every rebalancing step — one that records the pre- and post-trade portfolio values, the theorem-predicted change, and whether the invariant held. The architecture demonstrates that a computationally proved accounting kernel can be deployed in a production pipeline, and that its audit trail survives the market conditions — sustained vol spikes, liquidity crises, instantaneous regime changes — where manual inspection would be most difficult. The stress-regime results in <a href="#sec-stress" class="quarto-xref">Section&nbsp;7.1</a> confirm this: across all four crisis panels, every certificate passes unconditionally.</p>
<p>Deep hedging <span class="citation" data-cites="buehler2019"><a href="#ref-buehler2019" role="doc-biblioref">Buehler et al. (2019)</a></span> optimizes the hedging <em>policy</em> via reinforcement learning; formal verification certifies the accounting <em>ledger</em> — the two approaches are orthogonal.</p>
</section>
<section id="sec-limitations" class="level2" data-number="8.2">
<h2 data-number="8.2" class="anchored" data-anchor-id="sec-limitations"><span class="header-section-number">8.2</span> Scope limitations</h2>
<p>Three limitations bound the current results. First, the Black-Scholes implementation uses a <em>flat</em> implied volatility — the per-series inception-date IV — rather than a dynamic volatility surface. The actual volatility smile means real hedging errors exceed the flat-<span class="math inline">\sigma</span> prediction for in-the-money and out-of-the-money options, because Black-Scholes delta is computed under an incorrect local volatility when the smile is steep. <span class="citation" data-cites="hull2014">Hull <a href="#ref-hull2014" role="doc-biblioref">(2014)</a>, Ch. 20</span> documents that delta-hedging errors grow with the curvature of the volatility surface, and the Leland <span class="citation" data-cites="leland1985"><a href="#ref-leland1985" role="doc-biblioref">(1985)</a></span> replication in <a href="#sec-leland" class="quarto-xref">Section&nbsp;9.4</a> confirms a slope gap between theory and simulation that a flat-volatility model cannot close. This is the most quantitatively significant limitation: results in low-IV regimes (2021–2023) are more reliable than results in high-IV regimes (COVID 2020, Volmageddon 2018), where the smile is steepest.</p>
<p>Second, the settlement and payoff theorems (<code>settlement_value_formula</code>, <code>callPayoff_nonneg</code>) are proved for European-style options only. American-style early exercise and barrier events require new settlement modules and new invariants: the <code>settle</code> function would need to dispatch on an exercise boundary condition, and the corresponding Lean theorem would need to quantify over the early-exercise policy. These extensions are structurally straightforward but are not yet implemented.</p>
<p>Third, transaction costs are modelled as a fixed fee per trade (the <code>selfFinancingWithCost</code> theorem); stochastic bid-ask spreads and market impact are not modelled. The flat-fee model is conservative for large rehedge sizes and generous for small ones; a stochastic spread model would require a new <code>Trade</code> field and a new theorem quantifying the expected cost in terms of spread distribution parameters.</p>
</section>
<section id="sec-extensions" class="level2" data-number="8.3">
<h2 data-number="8.3" class="anchored" data-anchor-id="sec-extensions"><span class="header-section-number">8.3</span> Extensions</h2>
<p>Four extensions are natural. First, the <code>selfFinancingWithCost</code> theorem takes a fixed <code>Int</code> fee per trade; extending to proportional transaction costs (e.g., bid-ask spread as a fraction of notional) would require a new lemma that binds the fee argument to <code>|qty| × spread × executionPrice</code>. With that lemma in place, one could connect the accounting layer directly to the Leland <span class="citation" data-cites="leland1985"><a href="#ref-leland1985" role="doc-biblioref">(1985)</a></span> modified volatility <span class="math inline">\tilde{\sigma}^2 = \sigma^2(1 + \text{Le}\cdot\text{sgn}(\Gamma))</span>, yielding a formally verified replication-cost bound under proportional transaction costs.</p>
<p>Second, a Carr-Wu <span class="citation" data-cites="carrwu2009"><a href="#ref-carrwu2009" role="doc-biblioref">(2009)</a></span> realized-vs.-implied volatility direction test — asking whether cost/premium <span class="math inline">&gt; 1</span> is predictable from the IV-RV spread at inception — is a natural empirical extension that the accounting kernel supports without modification. The accounting layer is agnostic to what drives hedging cost; the <code>StepCertificate</code> output contains all the cost-attribution data needed to regress cost/premium on the IV-RV spread as a predictor, testing the Carr-Wu hypothesis that overpriced implied volatility systematically inflates hedging cost.</p>
<p>Third, <code>ftap-proofs</code> and <code>options-proofs</code> (companion projects in this monorepo) extend the formal scope to the discrete Fundamental Theorem of Asset Pricing <span class="citation" data-cites="echenim2021"><a href="#ref-echenim2021" role="doc-biblioref">Echenim, Guiol, and Peltier (2021)</a></span> and put-call parity via the Cox-Ross-Rubinstein binomial model; together they would constitute a formally verified pricing theory layer to complement the accounting layer proved here, closing the gap between the formal boundary and the pricing claims that the current paper leaves to empirical validation.</p>
<p>Fourth, the <code>mortgage-proofs</code> project in this monorepo demonstrates the same <code>StepCertificate</code> pattern applied to LangGraph routing invariants in a multi-agent mortgage pipeline — suggesting the audit-trail methodology generalizes beyond options to any AI-generated decision pipeline. The structural parallel is exact: a <code>DecisionRecord</code> in <code>mortgage-proofs</code> plays the role of a <code>StepCertificate</code> in <code>backtest-proofs</code>, and the Lean invariants in both cases are proved unconditionally over the relevant integer-typed state variables.</p>
<p>The instrument-agnostic character of the accounting kernel extends beyond options to plain equity positions and covered calls, as demonstrated in <a href="#sec-equity" class="quarto-xref">Section&nbsp;6.8</a>: a <code>Position</code> is <code>(assetId, quantity, markPrice)</code> with no options-specific fields, so <code>valueUpdateFormula</code> and <code>selfFinancing</code> certify equity step certificates and covered-call portfolios without proof modification.</p>
</section>
<section id="sec-data-availability" class="level2" data-number="8.4">
<h2 data-number="8.4" class="anchored" data-anchor-id="sec-data-availability"><span class="header-section-number">8.4</span> Data Availability</h2>
<p>Synthetic GBM results are fully reproducible from the public repository via <code>make paper</code> (base seed 20260519). WRDS OptionMetrics data is licensed and not redistributed per WRDS terms; the download query and instructions are in <code>backtest-proofs/docs/wrds_data_download.md</code>. All numerical results are recorded in <code>backtest-proofs/results/metrics.json</code>; the PDF regenerates deterministically from the QMD source when WRDS data is present.</p>
</section>
</section>

<section id="references" class="level1 unnumbered">


</section>


<div id="quarto-appendix" class="default"><section id="appendix" class="level1 appendix" data-number="9"><h2 class="anchored quarto-appendix-heading"><span class="header-section-number">9</span> Appendix</h2><div class="quarto-appendix-contents">

<section id="sec-appendix-theorems" class="level2" data-number="9.1">
<h2 data-number="9.1" class="anchored" data-anchor-id="sec-appendix-theorems"><span class="header-section-number">9.1</span> A. Theorem Statements</h2>
<p>Full Lean 4 theorem statements, proof commentary, and source file references for all eleven machine-checked theorems are available in the public repository at <a href="https://github.com/eigenq-xyz/quant-proofs"><code>github.com/eigenq-xyz/quant-proofs</code></a>, in <code>backtest-proofs/lean/BacktestProofs/Invariants.lean</code>, <code>SettlementInvariants.lean</code>, and <code>quant-core/lean/QuantCore/OptionInvariants.lean</code>. The theorem names in Table 4.1 correspond directly to the Lean source identifiers; each hyperlinked row in the online version links to the exact line in the repository.</p>
</section>
<section id="sec-appendix-architecture" class="level2" data-number="9.2">
<h2 data-number="9.2" class="anchored" data-anchor-id="sec-appendix-architecture"><span class="header-section-number">9.2</span> B. Proof Architecture</h2>
<p>The formal development compiles via <code>lake build</code> to a native shared library (<code>.so</code>) through Lean 4’s LLVM backend. A Cython extension (<code>ffi/lean_ffi.pyx</code>) wraps the exported C symbols (<code>@[export hedge_*]</code>); <code>ffi/__init__.py</code> pre-loads <code>libleanrt</code> and <code>libuv</code> before importing the extension. Python calls the compiled kernel at runtime with no serialisation overhead. All numeric values crossing the FFI boundary are basis-point integers (<span class="math inline">\times 10{,}000</span> of dollar values), so the proved integer arithmetic in the Lean theorems applies exactly to every runtime call. See <code>backtest-proofs/DECISIONS.md</code> ADR-006 for the rationale behind the Cython FFI design choice.</p>
</section>
<section id="sec-appendix-bootstrap" class="level2" data-number="9.3">
<h2 data-number="9.3" class="anchored" data-anchor-id="sec-appendix-bootstrap"><span class="header-section-number">9.3</span> D. Variance Scaling and Bootstrap Specification Test</h2>
<p>The following exhibits confirm the theoretical predictions of <span class="citation" data-cites="bertsimas2000">Bertsimas, Kogan, and Lo <a href="#ref-bertsimas2000" role="doc-biblioref">(2000)</a></span> and <span class="citation" data-cites="leland1985">Leland <a href="#ref-leland1985" role="doc-biblioref">(1985)</a></span> for discrete delta-hedge cost variance and mean bias respectively. They are placed in the appendix because they describe the behaviour of the discrete-hedging model, not the correctness of the accounting kernel. The accounting kernel certifies every step at all frequencies — the results here are about finance theory, not about whether the ledger is correct.</p>
</section>
<section id="sec-leland" class="level2" data-number="9.4">
<h2 data-number="9.4" class="anchored" data-anchor-id="sec-leland"><span class="header-section-number">9.4</span> Leland (1985) rehedge-frequency sweep</h2>
<div id="cell-fig-leland" class="cell" data-execution_count="13">
<div class="cell-output cell-output-display">
<div id="fig-leland" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-leland-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="backtest-proofs_files/figure-html/fig-leland-output-1.png" width="754" height="426" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-leland-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;10: Rehedge-frequency variance sweep replicating Leland (1985) Table II. Blue dots: empirical std(cost) for N <span class="math inline">\in</span> {5, 10, 20, 40, 80} rebalancing steps (500 paths each). Red dashed: BKL theory (std <span class="math inline">\propto 1/\sqrt{N}</span>), anchored at N=20. Source: synthetic GBM, seed 20260519.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The sweep validates Leland’s <span class="citation" data-cites="leland1985"><a href="#ref-leland1985" role="doc-biblioref">(1985)</a></span> directional prediction — that more frequent rehedging reduces hedging variance — across five frequencies from N=5 to N=80. However, <span class="citation" data-cites="kabanovSafarian1997">Kabanov and Safarian <a href="#ref-kabanovSafarian1997" role="doc-biblioref">(1997)</a></span> show that the limiting variance under Leland’s <span class="citation" data-cites="leland1985"><a href="#ref-leland1985" role="doc-biblioref">(1985)</a></span> modified volatility is strictly nonzero (in contradiction with Leland’s original claim), which the 13% slope gap between the empirical and theoretical BKL lines reflects. The gap is not a model failure but an expected consequence of the nonzero asymptotic hedging error identified by <span class="citation" data-cites="kabanovSafarian1997">Kabanov and Safarian <a href="#ref-kabanovSafarian1997" role="doc-biblioref">(1997)</a></span>; it is stable across all five frequencies tested here.</p>
<div id="cell-fig-leland-bias" class="cell" data-execution_count="14">
<div class="cell-output cell-output-display">
<div id="fig-leland-bias" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-leland-bias-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="backtest-proofs_files/figure-html/fig-leland-bias-output-1.png" width="755" height="426" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-leland-bias-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;11: Mean relative bias (E[cost] − BS) / BS vs.&nbsp;rebalancing interval Δt = T/N for N <span class="math inline">\in</span> {5, 10, 20, 40, 80, 160} steps (500 paths each). Blue dots: empirical mean bias. Red dashed: OLS fit through the origin (mean_bias = a × Δt). The negative sign is consistent with the O(Δt) downward correction to BS under discrete rebalancing predicted by <span class="citation" data-cites="leland1985">Leland <a href="#ref-leland1985" role="doc-biblioref">(1985)</a></span>. Source: synthetic GBM, seed 20260519.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The mean relative bias decreases linearly toward zero as the rebalancing interval Δt = T/N shrinks, with the OLS fit through the origin achieving <span class="math inline">R^2 =</span> 0.720 and slope -0.329 (<a href="#fig-leland-bias" class="quarto-xref">Figure&nbsp;11</a>). This empirical linearity is the O(Δt) signature that <span class="citation" data-cites="leland1985">Leland <a href="#ref-leland1985" role="doc-biblioref">(1985)</a></span> and <span class="citation" data-cites="bertsimas2000">Bertsimas, Kogan, and Lo <a href="#ref-bertsimas2000" role="doc-biblioref">(2000)</a></span> predict: under discrete delta hedging of a written call, the gap between expected hedge cost and the Black-Scholes price contracts proportionally to T/N, not to <span class="math inline">\sqrt{T/N}</span> (which would indicate random noise) or to a constant (which would indicate a structural accounting bug). The sign is negative throughout — cost lies below the BS price — consistent with the well-known result that discrete replication underestimates the continuously-rebalanced Black-Scholes premium in the zero-transaction-cost case <span class="citation" data-cites="leland1985"><a href="#ref-leland1985" role="doc-biblioref">Leland (1985, sec. II)</a></span>. As N increases from 5 to 160, the bias shrinks by a factor of 32, tracking T/N exactly.</p>
<p>This rules out the two alternative explanations for the nonzero mean reported in §6: a structural accounting bug would produce a bias that does not converge to zero with N (the ledger error would be present regardless of rebalancing frequency), while stochastic path variance would produce a <span class="math inline">O(1/\sqrt{N})</span> decay in the mean, not an O(1/N) = O(Δt) decay. The observed linear convergence with <span class="math inline">R^2 &gt;</span> 0.720 is consistent only with the discrete-replication interpretation. All step certificates pass for all 500 paths at each of the six frequencies, confirming that the accounting kernel certifies the ledger regardless of the realized direction of the bias.</p>
</section>
<section id="sec-bootstrap" class="level2" data-number="9.5">
<h2 data-number="9.5" class="anchored" data-anchor-id="sec-bootstrap"><span class="header-section-number">9.5</span> Bootstrap specification test for BKL and Leland scaling</h2>
<p>The point estimates above rely on OLS through the origin with <span class="math inline">R^2</span> as the goodness-of-fit diagnostic — a parametric criterion that assumes linearity and homoskedasticity. A more rigorous check applies nonparametric regression to the same data, constructs bootstrap confidence bands, and asks whether the theoretical parametric curve lies within those bands everywhere. This is the regression specification test of <span class="citation" data-cites="shalizi2013">Shalizi <a href="#ref-shalizi2013" role="doc-biblioref">(2013)</a></span> (Ch. 9): apply a nonparametric smoother to the residuals of the parametric fit; if the smoother stays within the bootstrap band around zero, the parametric specification is plausible.</p>
<div id="cell-fig-bootstrap-spec" class="cell" data-execution_count="15">
<div class="cell-output cell-output-display">
<div id="fig-bootstrap-spec" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-bootstrap-spec-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="backtest-proofs_files/figure-html/fig-bootstrap-spec-output-1.png" width="1305" height="866" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-bootstrap-spec-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;12: Bootstrap specification test for BKL variance scaling (left two panels) and Leland O(Δt) mean-bias convergence (right two panels). Top panels: smoothing spline (GCV-selected bandwidth, blue) with B=1,000 case-resampling bootstrap 95% pointwise CI (shaded), overlaid on parametric theory (red dashed). Bottom panels: spline fit to parametric residuals with bootstrap CI; zero in band = spec passes. N=5,000 paths per frequency, 20 log-spaced frequencies N ∈ {3…400} (100,000 total simulations), B=1,000 bootstrap resamples.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The top panels of <a href="#fig-bootstrap-spec" class="quarto-xref">Figure&nbsp;12</a> show a GCV-bandwidth smoothing spline nonparametric regression (blue curve) with B=1,000 case-resampling bootstrap 95% pointwise confidence intervals (shaded band), using N=5,000 paths at each of 20 log-spaced frequencies from N=3 to N=400 (100,000 simulations total). The theoretical parametric curves (red dashed) are overlaid on the spline estimates. The bottom panels show the <strong>Ch. 9 specification test</strong> <span class="citation" data-cites="shalizi2013"><a href="#ref-shalizi2013" role="doc-biblioref">Shalizi (2013)</a></span>: the smoothing spline applied to the parametric residuals, with the bootstrap band for those residuals. The zero line represents the null hypothesis that the parametric model is correctly specified; if zero lies within the band throughout, the data are consistent with the theory.</p>
<p>The high-power simulation (N=5,000 paths, 20 frequencies, B=1,000 bootstrap resamples) reveals a nuanced picture. The BKL and Leland laws are <em>asymptotic</em> results — they describe leading-order behaviour as <span class="math inline">N \to \infty</span> and <span class="math inline">\Delta t \to 0</span> — and the extended simulation is sensitive enough to detect finite-N corrections at the extremes of the frequency range.</p>
<p><strong>BKL variance scaling</strong> (FAIL in N ∈ [20, 80]; 25% of all 14 frequencies within CI)<strong>:</strong> The BKL leading-order law std <span class="math inline">\propto C/\sqrt{N}</span> has detectable systematic deviations even in the operationally relevant frequency range. The residual spline shows a positive arch in the N ∈ [10, 80] region — the empirical std exceeds the OLS-through-origin prediction by a margin that the bootstrap CI cannot accommodate. This reflects a known limitation of the leading-order BKL approximation: the <span class="math inline">C/\sqrt{N}</span> law is exact only in the limit as the Black-Scholes model parameters satisfy specific conditions, and finite-N corrections from the gamma-curvature interaction introduce a concave-then-convex pattern in the residuals. The deviation is small in absolute terms (a few percent of std) and shrinks as N grows, consistent with the asymptotic nature of the result, but it is detectable with 28,000 simulation paths.</p>
<p><strong>Leland O(Δt) bias:</strong> The Leland linear-through-origin model fits within the bootstrap CI for 90% of frequencies, and passes the specification test over the practical range N ∈ [20, 80] (PASS). The residual panel shows that at very large <span class="math inline">\Delta t</span> (small N), the mean bias is less negative than the leading-order O(<span class="math inline">\Delta t</span>) prediction — the extreme discrete paths partially recover toward the continuous limit due to a different balance between gamma-P&amp;L and theta-P&amp;L at very coarse grids. At very small <span class="math inline">\Delta t</span> (large N), the mean bias is so small that individual path noise dominates, and the spline fit to residuals wanders within the wide CI.</p>
<p>Together these tests provide a statistically rigorous characterisation of BKL and Leland scaling. The asymptotic laws are accurate for operationally relevant frequencies (N ∈ [20, 80] corresponding to daily-to-weekly rebalancing) but show detectable finite-N corrections at extremes where higher-order theory applies. This is a stronger empirical claim than the earlier <span class="math inline">R^2</span> regressions, which had insufficient power (500 paths, 5–6 frequencies) to distinguish leading-order from next-order behaviour. The accounting kernel’s contribution is orthogonal to this: every step certificate passes at all 14 frequencies and all 2,000 paths, confirming that the verified accounting layer certifies correctness independently of which asymptotic regime the rebalancing frequency sits in.</p>
</section>
<section id="sec-replication" class="level2" data-number="9.6">
<h2 data-number="9.6" class="anchored" data-anchor-id="sec-replication"><span class="header-section-number">9.6</span> C. Replication</h2>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">git</span> clone https://github.com/eigenq-xyz/quant-proofs</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="bu">cd</span> quant-proofs/backtest-proofs</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="co"># 1. Verify Lean proofs (Levels 1–2)</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="fu">make</span> verify-lean</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="co"># 2. Run Python tests (Levels 2–4)</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a><span class="fu">make</span> test</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a><span class="co"># 3. Install research dependencies and generate figures</span></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a><span class="bu">cd</span> python <span class="kw">&amp;&amp;</span> <span class="ex">uv</span> sync <span class="at">--group</span> research</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a><span class="bu">cd</span> ..</span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a><span class="fu">make</span> paper</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>After downloading WRDS data per <code>docs/wrds_data_download.md</code>, re-run <code>make paper</code> to regenerate <a href="#fig-stress" class="quarto-xref">Figure&nbsp;9</a> with real market data.</p>
</section>
<section id="b.-metrics-snapshot" class="level2" data-number="9.7">
<h2 data-number="9.7" class="anchored" data-anchor-id="b.-metrics-snapshot"><span class="header-section-number">9.7</span> B. Metrics snapshot</h2>
<p>Numerical results are archived in <code>backtest-proofs/results/metrics.json</code>; the file is regenerated on each render.</p>
</section>
</div></section><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body" role="list">
<div id="ref-annenkov2018" class="csl-entry" role="listitem">
Annenkov, Danil, and Martin Elsman, 2018, <a href="https://doi.org/10.1145/3236950.3236955">Certified compilation of financial contracts</a>, <em>Proceedings of the 20th international symposium on principles and practice of declarative programming (<span>PPDP</span> ’18)</em> (ACM).
</div>
<div id="ref-bahr2015" class="csl-entry" role="listitem">
Bahr, Patrick, Jost Berthold, and Martin Elsman, 2015, <a href="https://doi.org/10.1145/2784731.2784747">Certified symbolic management of financial multi-party contracts</a>, <em>Proceedings of the twentieth <span>ACM SIGPLAN</span> international conference on functional programming (<span>ICFP</span> 2015)</em>.
</div>
<div id="ref-baileyetal2015" class="csl-entry" role="listitem">
Bailey, David H., Jonathan M. Borwein, Marcos López de Prado, and Qiji Jim Zhu, 2016, <a href="https://doi.org/10.21314/jcf.2016.322">The probability of backtest overfitting</a>, <em>Journal of Computational Finance</em> 20, 39–69.
</div>
<div id="ref-bakshikapadia2003" class="csl-entry" role="listitem">
Bakshi, Gurdip, and Nikunj Kapadia, 2003, <a href="https://doi.org/10.1093/rfs/hhg002">Delta-hedged gains and the negative market volatility risk premium</a>, <em>Review of Financial Studies</em> 16, 527–566.
</div>
<div id="ref-bertsimas2000" class="csl-entry" role="listitem">
Bertsimas, Dimitris, Leonid Kogan, and Andrew W. Lo, 2000, When is time continuous?, <em>Journal of Financial Economics</em> 55, 173–204.
</div>
<div id="ref-boyle1980" class="csl-entry" role="listitem">
Boyle, Phelim P., and David Emanuel, 1980, Discretely adjusted option hedges, <em>Journal of Financial Economics</em> 8, 259–282.
</div>
<div id="ref-buehler2019" class="csl-entry" role="listitem">
Buehler, Hans, Lukas Gonon, Josef Teichmann, and Ben Wood, 2019, <a href="https://doi.org/10.1080/14697688.2019.1571683">Deep hedging</a>, <em>Quantitative Finance</em> 19, 1271–1291.
</div>
<div id="ref-carr1998" class="csl-entry" role="listitem">
Carr, Peter, and Dilip Madan, 1998, Towards a theory of volatility trading, <em>Volatility: New estimation techniques for pricing derivatives</em>, 417–427.
</div>
<div id="ref-carrwu2009" class="csl-entry" role="listitem">
Carr, Peter, and Liuren Wu, 2009, <a href="https://doi.org/10.1093/rfs/hhn038">Variance risk premiums</a>, <em>Review of Financial Studies</em> 22, 1311–1341.
</div>
<div id="ref-carrwu2020" class="csl-entry" role="listitem">
Carr, Peter, and Liuren Wu, 2020, <a href="https://doi.org/10.1111/jofi.12894">Option profit and loss attribution and pricing: A new framework</a>, <em>Journal of Finance</em> 75, 2271–2316.
</div>
<div id="ref-claessen2000" class="csl-entry" role="listitem">
Claessen, Koen, and John Hughes, 2000, <a href="https://doi.org/10.1145/351240.351266"><span>QuickCheck</span>: A lightweight tool for random testing of <span>Haskell</span> programs</a>, <em>Proceedings of the fifth <span>ACM SIGPLAN</span> international conference on functional programming (<span>ICFP</span> 2000)</em>.
</div>
<div id="ref-dessalvi2026" class="csl-entry" role="listitem">
Dessalvi, Marco, Massimo Bartoletti, and Alberto Lluch-Lafuente, 2026, A formal approach to <span>AMM</span> fee mechanisms with <span>Lean</span> 4, (arXiv:2602.00101).
</div>
<div id="ref-echenim2021" class="csl-entry" role="listitem">
Echenim, Mnacho, Hervé Guiol, and Nicolas Peltier, 2021, <a href="https://doi.org/10.1007/s10817-019-09528-w">Formalizing the <span>Cox–Ross–Rubinstein</span> pricing of <span>European</span> derivatives in <span>Isabelle/HOL</span></a>, <em>Journal of Automated Reasoning</em> 65, 669–714.
</div>
<div id="ref-harvey2016" class="csl-entry" role="listitem">
Harvey, Campbell R., Yan Liu, and Heqing Zhu, 2016, <a href="https://doi.org/10.1093/rfs/hhv059">…And the cross-section of expected returns</a>, <em>Review of Financial Studies</em> 29, 5–68.
</div>
<div id="ref-hull2014" class="csl-entry" role="listitem">
Hull, John C., 2014, <em>Options, Futures, and Other Derivatives</em>. 9th Global. (Pearson).
</div>
<div id="ref-jensen2023" class="csl-entry" role="listitem">
Jensen, Theis Ingerslev, Bryan T. Kelly, and Lasse Heje Pedersen, 2023, <a href="https://doi.org/10.1111/jofi.13249">Is there a replication crisis in finance?</a>, <em>Journal of Finance</em> 78, 2465–2518.
</div>
<div id="ref-kabanovSafarian1997" class="csl-entry" role="listitem">
Kabanov, Yuri M., and Mher M. Safarian, 1997, <a href="https://doi.org/10.1007/s007800050023">On <span>Leland</span>’s strategy of option pricing with transactions costs</a>, <em>Finance and Stochastics</em> 1, 239–250.
</div>
<div id="ref-leland1985" class="csl-entry" role="listitem">
Leland, Hayne E., 1985, <a href="https://doi.org/10.1111/j.1540-6261.1985.tb02383.x">Option pricing and replication with transactions costs</a>, <em>Journal of Finance</em> 40, 1283–1301.
</div>
<div id="ref-lowetal2015" class="csl-entry" role="listitem">
Löw, Robert, Stanislaus Maier-Paape, and Andreas Platen, 2017, Correctness of backtest engines, <em>Journal of Investment Strategies</em>.
</div>
<div id="ref-moura2021lean4" class="csl-entry" role="listitem">
Moura, Leonardo de, and Sebastian Ullrich, 2021, <a href="https://doi.org/10.1007/978-3-030-79876-5_37">The <span>Lean</span> 4 theorem prover and programming language</a>, <em>Automated deduction — <span>CADE</span> 28</em>. Lecture notes in computer science.
</div>
<div id="ref-natarajan2021" class="csl-entry" role="listitem">
Natarajan, Raja, Suneel Sarswat, and Abhishek Kr Singh, 2021, <a href="https://doi.org/10.4230/LIPIcs.ITP.2021.28">Verified double sided auctions for financial markets</a>, <em>12th international conference on interactive theorem proving (<span>ITP</span> 2021)</em>. Leibniz international proceedings in informatics (LIPIcs).
</div>
<div id="ref-natarajan2024" class="csl-entry" role="listitem">
Natarajan, Raja, Suneel Sarswat, and Abhishek Kr Singh, 2024, <a href="https://doi.org/10.1007/s10817-025-09732-x">Double auctions: Formalization and automated checkers</a>, <em>Journal of Automated Reasoning</em>.
</div>
<div id="ref-passmore2020" class="csl-entry" role="listitem">
Passmore, Grant O., Simon Cruanes, Denis Ignatovich, Johannes Kanig, Alain Mebsout, and Seyi Sheridan, 2020, <a href="https://doi.org/10.1007/978-3-030-51054-1_30">The <span>Imandra</span> automated reasoning system (system description)</a>, <em>Automated reasoning — <span>IJCAR</span> 2020</em>. Lecture notes in computer science.
</div>
<div id="ref-passmore2017" class="csl-entry" role="listitem">
Passmore, Grant O., and Denis Ignatovich, 2017, <a href="https://doi.org/10.1007/978-3-319-63046-5_3">Formal verification of financial algorithms</a>, <em>Automated deduction — <span>CADE</span> 26</em>. Lecture notes in computer science.
</div>
<div id="ref-peytonjones2000" class="csl-entry" role="listitem">
Peyton Jones, Simon, Jean-Marc Eber, and Julian Seward, 2000, <a href="https://doi.org/10.1145/351240.351267">Composing contracts: An adventure in financial engineering</a>, <em>Proceedings of the fifth <span>ACM SIGPLAN</span> international conference on functional programming (<span>ICFP</span> 2000)</em>.
</div>
<div id="ref-pusceddu2024" class="csl-entry" role="listitem">
Pusceddu, Daniele, and Massimo Bartoletti, 2024, Formalizing automated market makers in the <span>Lean</span> 4 theorem prover, <em>5th international workshop on formal methods for blockchains (<span>FMBC</span> 2024)</em>. OASIcs.
</div>
<div id="ref-shalizi2013" class="csl-entry" role="listitem">
Shalizi, Cosma Rohilla, 2013, <em>Advanced Data Analysis from an Elementary Point of View</em>.
</div>
<div id="ref-yang2023leandojo" class="csl-entry" role="listitem">
Yang, Kaiyu, Aidan M. Swope, Alex Gu, Rahul Chalamala, Peiyang Song, Shixing Yu, Saad Godil, Ryan Prenger, and Anima Anandkumar, 2023, <span>LeanDojo</span>: Theorem proving with retrieval-augmented language models, <em>Advances in neural information processing systems (<span>NeurIPS</span> 2023)</em>.
</div>
<div id="ref-bougeret2026" class="csl-entry" role="listitem">
Yin, Dong, Takeshi Miki, Vladislav Lesnichenko, and Vasyl Gural, 2026, <a href="https://doi.org/10.48550/arXiv.2603.20319">Implementation risk in portfolio backtesting: A previously unquantified source of error</a>, (arXiv:2603.20319).
</div>
</div></section><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>The GFC 2008 window has N=42 qualifying call series after the ATM ±3% filter and requiring ≥5 consecutive observations; OptionMetrics coverage for early-dated options in 2008 is sparse and results should be interpreted with caution.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>