{
  "hash": "803ec966a8415d1add8636f77d283d9a",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Provably Correct Quantitative Backtesting\"\nsubtitle: \"A Machine-Verified Position Ledger with Empirical Validation Across Four Historical Stress Regimes\"\nauthor:\n  - name: Akhil Karra\ndate: today\ndate-format: long\nabstract: |\n  Bugs in a backtester's position ledger produce plausible profit and\n  loss time series that statistical validation cannot diagnose: the\n  test takes the reported P&L as given. We build a backtesting framework\n  whose position ledger is machine-checked in Lean 4 and exposed to\n  Python through a runtime bridge that emits a per-step audit record,\n  ruling out accounting errors in the verified layer. The framework is\n  asset-agnostic: any strategy that produces integer-valued trades\n  inherits the same accounting guarantee, and the audit records address\n  the ongoing-monitoring requirement under SR 11-7 model risk\n  management guidance. We exercise the framework using a discrete\n  delta-hedging strategy on European call options, with per-series\n  implied volatility held flat at the inception date. Across 37,246\n  OptionMetrics option-day observations spanning four historical stress\n  regimes (GFC 2008, Volmageddon 2018, Q4 2018, COVID 2020) and 25,363\n  qualifying series in a 2021–2023 calm-market holdout, every step\n  audit record passes on real-data inputs the synthetic test harness\n  cannot replicate. Separately, the discrete-hedging implementation\n  reproduces the standard benchmarks: realized hedging cost converges\n  to within 2.34% of the Black-Scholes price across 500 Monte Carlo\n  paths, the integer pricer agrees with QuantLib to within 2.69 basis\n  points across five canonical scenarios, and the Bertsimas-Kogan-Lo\n  variance-scaling and Carr-Madan gamma-attribution predictions hold\n  within bootstrap confidence intervals on a 100,000-simulation panel.\n  Extension to a dynamic volatility surface, proportional transaction\n  costs, and American-style payoffs is left for future work.\nkeywords:\n  - quantitative finance\n  - formal verification\n  - backtesting\n  - model risk management\n  - options\njel:\n  - G12\n  - G13\n  - C63\nbibliography: _references.bib\nexecute:\n  echo: false\n  warning: false\n---\n\n\n# Introduction {#sec-intro}\n\nOn 1 August 2012, Knight Capital lost roughly $440 million in 45 minutes\nwhen a deployment activated an obsolete code path alongside new order\nrouting logic, sending millions of unintended orders into the market\nbefore the firm could halt trading. The bug routed orders, not P&L\nentries, so the analogy to backtesting is not in the location of the\ndefect but in its structural cause: the obsolete code path executed on\nan input neighborhood the test author had not anticipated, and the test\nsuite that had passed during deployment could not have caught it.\nBacktesters carry the same exposure in a quieter register. A flawed\nposition ledger produces a plausible P&L time series rather than a\nflood of erroneous live orders, so the error can survive both\nin-sample and out-of-sample evaluation undetected. When the ledger\nthat produces realized P&L contains a bug (a settlement dropped, a\ncash debit applied at the wrong step, a position quantity that drifts\nfrom its trade history), the reported P&L is well-formed. It generates a Sharpe ratio, it passes\nout-of-sample evaluation, it survives robustness checks across regimes.\nThe bug is invisible because the test takes the reported P&L as given.\n@bougeret2026 audited five widely used open-source backtesting engines\nand documented exactly this class of error; @lowetal2015 documented the\nsame class of silent error in a deployed production system. Testing\ninevitably checks correctness on the inputs the test author chose; live\nhistorical data presents inputs the test author did not anticipate.\n\nThis paper builds a backtesting framework whose position ledger (the\ncomponent that records trades, marks positions, and reconciles cash\nagainst portfolio value) is machine-checked in Lean 4 and exposed to\nPython through a runtime bridge that emits a per-step audit record. The proved\nkernel rules out accounting errors of the silent kind described above\nwithin the verified layer; the bridge that ferries integer-valued\ninputs across the FFI boundary is itself unproved, and the audit record\nis the artifact that closes the loop (a mismatch between the proved\nprediction and the runtime state surfaces as a record failure rather\nthan as silent ledger corruption). The framework is asset-agnostic. Any\nstrategy that produces integer-valued trades inherits the same\naccounting guarantee. We demonstrate the framework using a discrete\ndelta-hedging strategy on European call options, but delta-hedging is\nthe validation vehicle, not the contribution.\n\nFormal verification is the practice of writing machine-checked proofs\nthat code satisfies a mathematical specification. @peytonjones2000 and\n@bahr2015 establish the foundational result for finance applications:\nfinancial contracts can be expressed as algebraic combinators with\ncomposition laws that admit proof. The position\nledger is exactly this kind of algebraic structure. Trades compose\ninto portfolio state under provable laws (cash flows aggregate\nadditively, position quantities accumulate from the trade history, net\nasset value is the inner product of marks and positions). The novelty\nhere is not the formalization itself but the integration: the proved\ncode runs in the same process as a production Python backtester, with\nthe verified ledger called from the same runtime that executes the\nstrategy and reads market data. The aim is a quantitative research\ntoolchain in which formal verification is part of everyday practice,\nnot confined to specialist demonstrations.\n\nThree contributions follow.\n\n1. An open-source backtesting framework whose position ledger is\n   machine-checked. Cash flows, position quantities, and the\n   portfolio-value identity are discharged by Lean's kernel for every\n   integer-valued input the runtime bridge can pass. The guarantee\n   holds within the verified layer regardless of the strategy\n   implemented on top of the ledger.\n\n2. An integration of formal verification into the Python\n   quantitative-research ecosystem. The verified kernel runs in the\n   Python process via a runtime bridge, and the framework produces a\n   machine-readable step audit record at every rebalancing step that\n   compares the proved prediction to the observed P&L change. This\n   directly addresses the ongoing-monitoring requirement under SR 11-7\n   model risk management guidance [@sr117] and OCC Bulletin 2011-12.\n\n3. An empirical demonstration that the step audit records pass on\n   real-data inputs the synthetic test harness cannot replicate.\n   Across 491,390 WRDS OptionMetrics option-day observations and four\n   historical stress regimes (GFC 2008, Volmageddon 2018, Q4 2018,\n   COVID 2020), every step audit record passes. Separately, the\n   discrete-hedging implementation reproduces the standard benchmarks:\n   Monte Carlo hedging cost converges to the Black-Scholes price, the\n   Bertsimas-Kogan-Lo and Carr-Madan attributions hold within\n   bootstrap confidence intervals on a 100,000-simulation panel, and\n   the variance risk premium documented by @bakshikapadia2003 appears\n   in both the holdout median and the crisis-window reversal. These\n   are two distinct claims: the first is the framework guarantee, the\n   second is a sanity check on the discrete-hedging implementation\n   running on top of it.\n\nThe position ledger is proved for any integer-representable instrument:\ncash flows, position quantities, and the portfolio-value identity hold\nby construction. Black-Scholes pricing, GBM simulation, and all\ndistributional claims about hedging cost are empirically validated, not\nformally proved. The contribution is the verification workflow and its\nempirical demonstration, not a novel result for European vanilla options.\n\n## Related Work {#sec-related}\n\nA first body of work concerns backtest overfitting and the statistical\ncorrectness of strategy selection. @baileyetal2015 introduce\nCombinatorially Symmetric Cross-Validation (CSCV) to estimate the\nprobability that a reported backtest is overfit to historical data, and\nshow that this probability can be substantial when a strategy is chosen\nfrom a large configuration space. @harvey2016 argue that, given the\nroughly 316 candidate factors already examined in the cross-sectional\nreturns literature, new factor claims should require a t-statistic of at\nleast 3.0 to maintain a defensible false discovery rate; subsequent\nwork qualifies this severity. @jensen2023 document that overfitting\npersists even after out-of-sample testing is applied systematically.\nThis literature addresses the statistical correctness of the strategy\nselection process. Our concern is orthogonal: the correctness of the\nposition ledger that produces the P&L series the statistical tests\nrely on. The two are independent classes of error.\n\nA second body of work establishes the theoretical and empirical baseline\nfor discrete hedging against which our validation is evaluated.\n@bertsimas2000 (BKL) show that the standard deviation of discrete\nhedging cost scales as $1/\\sqrt{N}$ in the number of rebalancing steps\nunder the continuous-rebalancing limit. @leland1985 derives a modified\nvolatility correction for discrete hedging under proportional\ntransaction costs. @figlewski1989 measures empirical hedging error\nacross rebalancing frequencies and option characteristics in real data.\n@hutchinson1994 develop a nonparametric learning-network approach to\npricing and hedging derivatives from market data, providing a model-free\nbaseline. @bakshikapadia2003 documents the negative variance risk\npremium that drives the cost-to-premium ratio in real options markets.\nModern reinforcement-learning extensions such as deep hedging\n[@buehler2019] generalize the strategy layer but still rely on a\nposition ledger to compute realized P&L from the policy's trades, so\nthe verified ledger introduced here is composable with these recent\napproaches. Our\nempirical sections (@sec-mc, @sec-wrds) reproduce and extend the\nclassical benchmarks on synthetic and real data using the verified\nposition ledger.\n\nA third body of work supplies the institutional motivation for\nmachine-readable audit trails. Supervisory guidance on model risk\nmanagement, in particular @sr117 (Federal Reserve SR 11-7 and OCC\nBulletin 2011-12), requires that model validation extend beyond initial\nstatistical backtesting to ongoing monitoring, documentation of model\nbehavior under stress conditions, and conceptual soundness review. The\nstep audit record architecture introduced in this paper addresses the\nongoing-monitoring requirement directly: every rebalancing step produces\na machine-readable record certifying that the accounting invariants held\nfor that specific trade.\n\nThe methods we use to discharge those invariants come from the\nliterature applying formal verification to financial systems.\n@peytonjones2000 and @bahr2015 formalize financial contracts as\nalgebraic combinators in a domain-specific language (DSL).\n@annenkov2018 extends this with a Coq proof of contract cashflow\nsemantics; Coq is a proof assistant similar to Lean 4. @echenim2021\nproves ledger identities for the Cox-Ross-Rubinstein binomial model in\nIsabelle/HOL (another proof assistant), adopting the same separation\nbetween instrument-agnostic portfolio accounting and option-specific\npricing that we use. @natarajan2021 formalizes exchange matching-engine\ninvariants in Coq with extraction to OCaml and Haskell, and\n@natarajan2024 extends this to live exchange data; both target matching\nmechanics rather than backtester accounting. Passmore and Ignatovich\n[-@passmore2017; -@passmore2020] develop Imandra, a proprietary\nindustrial verification system deployed at exchanges for matching-engine\nfairness and clearing-rule verification. Recent Lean 4 work in finance\nhas focused on decentralized finance: @pusceddu2024 and @dessalvi2026\napply Lean 4 to automated market makers. This paper differs in two\nways. It targets the position ledger of a research backtester rather\nthan a matching engine or smart contract, and it bridges to the Python\nquantitative-research ecosystem at runtime rather than producing\nstandalone proof artifacts.\n\n## A Motivating Example {#sec-falsification}\n\nConsider a class of accounting bug a careful test suite cannot detect: the\ncash deduction for a delta-hedge trade is silently set to zero. The trade\nquantity is recorded on the position correctly, but the cash balance\nremains unchanged. This is exactly the kind of error a flawed\nbasis-point conversion would introduce if the converter returned zero on\nfractional cents instead of rounding to the nearest integer.\n\nThe trade-accounting identity that the ledger enforces is\n$\\Delta\\text{PV} = q_{\\text{pre}} \\cdot (p_{\\text{exec}} -\np_{\\text{mark}}) - \\text{fee}$. Concretely, suppose the portfolio holds\n$100.00 in cash, the mark price is $49.00, and the execution price\nmoves to $50.00 with no fee. Two trades happen in sequence: a first\npurchase from a zero starting position, then a subsequent purchase of\n500 more shares.\n\n| | $q_{\\text{pre}}$ | $p_{\\text{exec}}$ | $p_{\\text{mark}}$ | Predicted $\\Delta\\text{PV}$ |\n|---|---|---|---|---|\n| Trade 1 (first purchase) | 0 shares | $50.00 | $49.00 | $0 \\times (50.00 - 49.00) = \\$0$ |\n| Trade 2 (subsequent buy) | 500 shares | $50.00 | $49.00 | $500 \\times (50.00 - 49.00) = \\$500$ |\n\nOn Trade 1, the predicted change is $\\$0$ because the pre-trade quantity\nis zero. The bug produces a $\\$0$ change too: cash was not debited but\nthe identity does not require cash movement when $q_{\\text{pre}}=0$.\nPredicted and observed values agree, the audit record passes, the test\nsuite is satisfied.\n\nOn Trade 2, the identity predicts $\\Delta\\text{PV} = \\$500$. The bug\nstill produces $\\$0$ because cash is not debited. The audit record now\nrecords observed $\\Delta\\text{PV} = \\$0$ and predicted $\\Delta\\text{PV}\n= \\$500$; the mismatch surfaces immediately. The bug is caught.\n\nA test suite cannot reliably catch this bug for two structural reasons.\nFirst, the trade-accounting identity has a removable singularity at\n$q_{\\text{pre}}=0$: when the pre-trade quantity is zero, the predicted\nchange in portfolio value is zero regardless of the execution price, so\na test that constructs inputs from a zero starting position cannot\ndistinguish a correct cash debit from no cash debit at all. A natural\ntest author writes the first test as \"buy 500 shares at \\$50 from an\nempty position and check the result\" exactly because that is the\nsimplest input to construct. The simplest test is also the test the bug\nsurvives.\n\nSecond, even a test that exercises $q_{\\text{pre}}>0$ inputs only\ncatches the bug on the specific input values it chose to construct.\nThere is no algorithmic guarantee that the test set is representative\nof the inputs the live system will see. The bug we constructed is\ntrivial to add a second test for once an audit record has flagged it,\nbut the next bug a future change introduces will sit in a different\ninput neighborhood, and the test suite will need to be extended again\neach time. Testing is reactive: it covers the inputs the author\nremembered to include. The proof is exhaustive: it covers every\ninteger-valued input the type system admits, which is the same set of\ninputs the Python execution layer can pass.\n\nStatistical validation of the backtest output is also blind to this\nclass of bug. The bias the bug introduces appears on every rebalancing\nstep, so the reported P\\&L curve is shifted by exactly the same amount\nin every period. Cross-validation, out-of-sample evaluation, and\nregime-conditional comparisons all subtract the bias from itself; the\nbug is invisible to any test that takes the reported P\\&L as given.\n\nA natural reader will ask what the Lean proof contributes that a\ncarefully written runtime assertion in Python could not. The bug above\nis caught at the audit-record check, which is a runtime comparison of\nthe predicted change in portfolio value against the observed change.\nThe same comparison could in principle be coded as a Python assertion\nwithout any proof assistant. The proof's contribution is upstream of\nthat comparison. It establishes two things a hand-written assertion\ncannot. First, the formula on the right-hand side of the audit-record\ncheck ($q_{\\text{pre}} \\cdot (p_{\\text{exec}} - p_{\\text{mark}}) -\n\\text{fee}$) is the specification of the trade-accounting identity for\nthe verified ledger, machine-checked to be the unique formula that the\nledger's trade-update function satisfies for every integer-valued\ninput. Without the proof, the assertion's right-hand side is a hand\ntranscription, itself prone to the same class of bug it is meant to\ncatch. Second, the proof quantifies over every integer-valued input the\ntype system admits; the bridge cannot pass an input the proof does not\ncover. The audit record is therefore not a sample of the input space\nbut a witness, on every step the runtime actually executes, that the\nproved prediction matches the observed P&L change. The complete code\nexhibit and the full audit-record format are in Appendix A.\n\n# The Position Ledger {#sec-ledger}\n\n## What the ledger tracks {#sec-ledger-arch}\n\nThe position ledger tracks three things: the portfolio's cash balance,\nits open positions, and the trades that update them. A position pairs a\nsigned integer quantity with an integer mark price; a portfolio collects\npositions alongside cash; a trade records one execution as an asset\nidentifier, a signed quantity, an execution price, and a fee. All\nmonetary values are integer basis points (one ten-thousandth of one\ndollar); the proved theorems hold as universal statements over\ninteger-valued inputs, with no floating-point arithmetic crossing the\nproved boundary.\n\nThe three data types carry structural invariants at the Lean type\nlevel. A position requires a positive mark price; a trade requires a\npositive execution price and a non-negative fee; a portfolio requires\nits reported value to equal cash plus the sum of position values. A\nvalue of any of the three types whose components do not satisfy these\ninvariants cannot be constructed: the Lean elaborator rejects it. The\nruntime bridge applies the same invariants to integer inputs crossing\nthe FFI boundary before passing them to the proved kernel, so any\ninconsistent runtime input is rejected at the boundary rather than\npropagated. The central identity, that portfolio value equals cash\nplus the sum of position values, is therefore a typing invariant\nrather than a runtime check.\n\nThe ledger's update rule applies a single trade to a portfolio: it\nadjusts the position quantity by the signed trade size, debits cash by\nthe signed quantity times the execution price plus the fee, and\nre-establishes the value invariant on the resulting portfolio. No\noption-specific fields appear in any of the three data structures. The\nledger is instrument-agnostic by construction.\n\n## What is machine-checked {#sec-ledger-proofs}\n\nEight substantive theorems describe what the ledger cannot do wrong,\ntogether with three payoff-sign obligations that the type system\ndischarges as immediate consequences of the payoff definition.\n\n| Theorem | What it guarantees | Accounting failure it prevents |\n|---|---|---|\n| NAV identity | Portfolio value equals cash plus the sum of position values | Portfolio value drifts from cash plus marked positions |\n| Cash update | Cash debited by execution cost plus fee | Cash flows that do not match the trade ledger |\n| Quantity conservation | Position size changes by the signed trade quantity | Positions drift from transacted quantities |\n| Trade accounting | NAV change equals pre-trade quantity × (exec − mark) − fee | Rebalancing P&L mis-attributed or partially recorded |\n| Self-financing | A costless trade leaves NAV unchanged | Free-lunch P&L from zero-cost operations |\n| Self-financing with fee | NAV change under a fixed fee equals mark-to-market gain minus fee | Fixed transaction costs inconsistently applied |\n| Well-formedness | A valid trade preserves the portfolio's validity invariant | Inconsistent ledger state propagates downstream |\n| Settlement | Option settlement changes NAV by quantity × (payoff − mark) | Incorrect ITM/OTM expiry cash flows |\n| Payoff well-formedness | Call, put, and generic option payoffs are non-negative | Sign error at expiry charges the option holder |\n\n: Lean 4 theorem map. Eight substantive theorems plus three\npayoff-sign obligations (folded into the last row) are machine-checked\nwith zero proof placeholders. Full Lean type signatures are in\nAppendix B (@sec-appendix-theorems).\n{#tbl-theorems tbl-colwidths=\"[22,40,38]\"}\n\nThe first seven theorems govern instrument-agnostic accounting. Cash\nupdates by the trade cost and fee; positions update by the signed\ntrade size; portfolio value equals cash plus position values; a trade\nat the prevailing mark price changes portfolio value only by the fee.\nAny asset representable as an integer mark price and a signed quantity\ninherits these guarantees. An equity position, a futures contract, and\nan options position are treated identically by the position ledger.\n\nThe settlement theorem covers European option expiry: settling at\nexpiry changes portfolio value by the quantity held times the\ndifference between the option's payoff and its pre-expiry mark price,\none equation that handles in-the-money and out-of-the-money paths\nwithout case logic at the call site. The payoff well-formedness\nobligations (call, put, and generic option payoffs are non-negative)\nare the economic statement that option holders bear no downside risk\nat expiry; the type system discharges them from the max-with-zero\ndefinition of payoff. Extending the formalization to instruments with\ndifferent settlement conventions, such as mark-to-market for futures or\naccrued coupon for bonds, would require analogous settlement\ninvariants; this is left to future work, and mirrors the separation of\nportfolio accounting from instrument-specific settlement in the\nIsabelle/HOL formalization of @echenim2021.\n\nThe proofs hold for any integer-representable input. They do not, and\ncannot, guarantee correctness of the upstream pricing model, the price\npath simulation, or the strategy logic that produces trades. The\nempirical sections that follow test what the backtester actually\nproduces on real and synthetic data.\n\n## The step audit record {#sec-ledger-audit}\n\nAt each rebalancing step the runner emits a step audit record. The\nrecord stores the pre- and post-trade portfolio values in basis points,\nthe change in portfolio value predicted by the trade-accounting identity\n($\\Delta V = q_{\\text{pre}} \\cdot (p_{\\text{exec}} - p_{\\text{mark}}) -\n\\text{fee}$), and a pass/fail flag. If the flag is false, the runner\nraises an exception immediately with a diagnostic identifying the step\nand inputs at which the identity failed.\n\nA failure cannot be a market event. The trade-accounting identity is a\nproved theorem of the ledger, and the ledger holds unconditionally for\nall integer-valued inputs. A failure therefore indicates a bug in the\nPython execution layer or the runtime bridge that connects it to the\nledger, never a property of the price path or trade sequence.\n\nTogether, the step audit records for a backtest run form a\nmachine-readable audit trail at every rebalancing step. For every step\nacross every path in the Monte Carlo sweeps and every empirical regime\nwindow, the runner either confirms that the trade-accounting identity\nheld or pinpoints the exact step at which it failed. This addresses the\nongoing-monitoring requirement under the SR 11-7 model risk management\nguidance, which expects firms to monitor models continuously rather than\nrely on point-in-time validation.\n\n## Scope: what is and is not formally verified {#sec-ledger-scope}\n\nThe ledger proofs cover cash and position accounting unconditionally for\nall integer-valued inputs. They do not cover the Black-Scholes pricing\ncomputations, the geometric Brownian motion path simulation, the\nstrategy logic, or the quality of the input data. These four sources of\nrisk are empirically evaluated in @sec-data through @sec-mc.\n\nThe comparison class for the formal results is narrow but precise. The\nledger proofs rule out, within the verified kernel, the class of\naccounting errors that no statistical test can detect, because any test\ntakes the reported P&L as an input. They do not address model risk or\nstrategy risk, and they do not substitute for the empirical validation\nthat the remainder of the paper provides.\n\n# The Delta-Hedging Strategy {#sec-strategy}\n\nTo demonstrate the position ledger on a theoretically tractable\ninstrument, we run a discrete-time delta-hedging strategy through it.\nThe strategy writer shorts $N$ European call options at $t = 0$ and\ndynamically replicates the position over horizon $T$ using $n$ equally\nspaced rebalancing steps of width $\\Delta t = T/n$. At inception the\nwriter receives the Black-Scholes premium and opens a stock position of\n$\\Delta_0 \\cdot N$ shares at spot price $S_0$. At each subsequent step\n$i \\in \\{1, \\dots, n-1\\}$ the hedger computes the new delta $\\Delta_i$\nfrom the current spot $S_i$ and remaining time to expiry\n$T - i \\cdot \\Delta t$, and trades $(\\Delta_i - \\Delta_{i-1}) \\cdot N$\nshares at $S_i$. The cash account is debited or credited by the full\ncost of each rebalancing trade including any transaction fee. At expiry\nstep $n$ the option settles to $\\max(S_n - K,\\, 0) \\cdot N$ in cash and\nthe remaining stock position is liquidated at spot $S_n$.\n\nThe primary quantity of interest is the total hedging cost, defined as\nthe initial premium received minus the terminal portfolio value:\n$$\n\\text{HedgingCost} = C_0 \\cdot N - V_n,\n$$\nwhere $V_n$ is the portfolio value at expiry after settlement and\nunwinding. Under continuous rebalancing and geometric Brownian motion\ndynamics, the Black-Scholes replication argument guarantees\n$\\text{HedgingCost} = 0$ almost surely. Under discrete rebalancing,\nresidual variance from the gamma term generates a non-trivial hedging\ncost distribution whose mean and variance depend on step size $\\Delta\nt$, volatility $\\sigma$, and any transaction costs. The canonical\ndeterministic example is Tables 19.2 and 19.3 of @hull2014, which trace\na 20-step weekly hedge for a written at-the-money call and tabulate the\nhedging cost under a specific realized path. The two Hull paths are\nreproduced in @sec-appendix-hull as a deterministic cross-check\nagainst a manual basis-point Python implementation; both Hull paths\nare also used to settle the multi-leg portfolios in @sec-multileg.\n\nThe delta-hedging strategy is the demonstration vehicle. Every result\nabout ledger correctness in this paper is a property of the underlying\nledger, not of this specific strategy; any strategy that produces\ninteger-valued trades would receive the same accounting guarantees.\n\nThe empirical results of this paper rest on four scope assumptions about\nthe strategy and its execution. The position ledger proofs hold without\nany of these assumptions; the assumptions bound only the empirical\nvalidation in Sections 5 and 6.\n\n> **Assumption A1 (Flat implied volatility).** The Black-Scholes pricing\n> calculation for each contract uses a single per-series implied\n> volatility taken from the contract's first observed quote. A dynamic\n> volatility surface is not modeled.\n\n> **Assumption A2 (European-style payoffs).** Options are exercised only\n> at expiry. American-style early exercise and barrier events are not\n> modeled.\n\n> **Assumption A3 (Fixed-fee transaction costs).** Transaction costs are\n> modeled as a fixed integer fee per trade. Proportional costs (bid-ask\n> spreads, market impact) are not modeled.\n\n> **Assumption A4 (Integer-valued trades).** Trade quantities and prices\n> are representable as 64-bit integers in basis-point units. This is the\n> condition under which the position ledger proofs apply.\n\n@sec-results and @sec-sanity evaluate the empirical consequences of\nA1 and A3, and @sec-limitations discusses extensions to American-style\nsettlement (A2) and stochastic transaction costs (A3 relaxed).\n\n# Empirical Setup {#sec-data}\n\n## Main sample\n\n| Attribute | Value |\n|---|---|\n| Source | WRDS OptionMetrics (licensed; not committed) |\n| Sample window | 2019-01-01 to 2024-12-31 |\n| Universe | SPY, QQQ, AAPL, MSFT, JPM, IWM (6 tickers) |\n| Frequency | Daily end-of-day snapshots |\n| Moneyness filter | ATM ±3% (\\|S/K − 1\\| ≤ 0.03) |\n| Expiry filter | 20–40 calendar days to expiration |\n| Risk-free rate | SOFR annualised average, 1.65% |\n| Final N (after filters) | 491,390 option-day observations |\n\n: Main sample characteristics. {#tbl-main-sample}\n\nThese filters impose no restriction on the formal results; the position\nledger proofs hold for arbitrary strike prices and expiry dates. They\nreflect standard data-quality practice: deep-OTM contracts have wide\nbid-ask spreads that make implied-volatility estimates unreliable, and\ncontracts outside the 20–40 day window are excluded to avoid illiquid\nnear-expiry and far-dated quotes that frequently contain stale prices.\n\n## Train and holdout split\n\nThe 2019–2024 main sample is partitioned in advance: the 2019–2020\nsub-period is treated as in-sample, and the 2021–2023 sub-period is\nthe out-of-sample holdout used in @sec-wrds. The 2020 calendar year is\nexcluded from the holdout to maintain clean separation from the COVID\nstress regime evaluated in @sec-stress. No parameters are tuned on\neither sub-period: the Black-Scholes pricer takes the per-series\ninception-date implied volatility as input (see Assumption A1), and\nthe Monte Carlo simulation uses a fixed seed (20260519) declared at\nthe top of the analysis script. This protocol (train/holdout\npartition declared before any empirical statistic is computed, a\nsingle seed for the simulation, no parameter tuning on either\nsub-period) is the design distinction between this validation and a\nbacktest-overfitting exercise of the kind catalogued by\n@baileyetal2015.\n\nThe four crisis windows in @sec-stress are out-of-period checks. GFC\n2008, Volmageddon 2018, and Q4 2018 all precede the in-sample window\nand are drawn from a separate WRDS pull. The COVID 2020 window is\ndrawn from the same parquet file as the main sample but is the\ncalendar year excluded from both the in-sample and holdout periods.\n\n## Stress-period samples\n\nFour supplementary WRDS OptionMetrics downloads use the same schema and\nticker universe (@tbl-stress-samples). The raw pull spans 2007-01-01 to\n2024-12-31 (830,439 option-day observations) and is filtered to each\nanalysis window below at render time. The N column reports the\noption-day count after the ATM ±3% moneyness filter and the\n≥5-consecutive-observations-per-series filter applied by\n`run_stress_window`. The total across all four crisis windows is\n37,246 option-day observations spanning 3,289 qualifying call series.\n\n| Window | Analysis dates | Regime | N observations | N series |\n|---|---|---|---|---|\n| GFC peak | 2008-09-15 to 2008-11-21 | Liquidity crisis | 527 | 42 |\n| Volmageddon | 2018-01-22 to 2018-02-16 | Volatility spike | 5,060 | 527 |\n| Q4 2018 selloff | 2018-10-01 to 2019-01-31 | Rate-driven drawdown | 25,090 | 2,411 |\n| COVID 2020 | 2020-02-19 to 2020-03-23 | Pandemic shock | 6,569 | 309 |\n\n: Stress-period sample characteristics. COVID rows are filtered from\n`portfolio_atm_options.parquet` (the same file used for the\n2021–2023 calm-market holdout); GFC, Volmageddon, and Q4 2018 are\nseparate pulls. The COVID analysis window is restricted to the\nFebruary 19 – March 23 vol-shock period rather than the full pandemic\nyear.\n{#tbl-stress-samples}\n\nThe GFC window (527 option-day observations) is substantially smaller than the\nothers due to near-total illiquidity in ATM options during September–October\n2008: bid-ask spreads widened to levels where implied-volatility estimates\nare unreliable, and most contracts fell outside the ±3% moneyness filter.\nThese results warrant caution given the sparse GFC coverage.\n\n## Synthetic GBM and deterministic paths\n\nThe Monte Carlo convergence, BKL scaling, Carr-Madan, Leland, and QuantLib\nfigures use no licensed data. GBM paths are seeded with\n20260519 for full reproducibility.\n\nHull Tables 19.2 and 19.3 use the hardcoded weekly prices from\n@hull2014 (Tables 19.2/19.3): S₀ = $49, K = $50, r = 5%, σ = 20%,\nT = 20 weeks. The Python runtime bridge reproduces these two\ndeterministic price paths and agrees with an independent Python\nreference implementation to within $\\sim 1$ basis point at every\nrebalance step; this deterministic cross-check is documented in\nAppendix D (@sec-appendix-hull). Black-Scholes prices computed via the\nbasis-point integer pricer also agree with QuantLib's analytic pricer\nto within 2.69 bp across a five-scenario parameter sweep, well inside\nthe 3 bp tolerance used by buy-side validation desks\n(@sec-appendix-quantlib).\n\n# The framework guarantee in practice {#sec-results}\n\nThe proofs in @sec-ledger hold for every integer-valued input the\nruntime bridge can pass; the question this section answers is whether\nthe bridge in fact passes such inputs on data the synthetic test\nharness cannot replicate. We exercise the framework along three\nindependent stressors of the runtime path: a 2021–2023 WRDS\nOptionMetrics calm-market holdout (@sec-wrds), four historical stress\nregimes spanning crisis archetypes (@sec-stress), and a battery of\nmulti-leg portfolios composed of long and short positions across both\noption kinds (@sec-multileg). Every step audit record passes in every\npanel: 25,363 qualifying calm-market series in the holdout, 37,246\noption-day observations across GFC 2008, Volmageddon 2018, Q4 2018,\nand COVID 2020 in the crisis windows, and every multi-leg exhibit. The\nledger's proved invariants are not tested by these results; what is\ntested is whether the runtime bridge passes inputs that satisfy them.\nOn the largest collection of real-data inputs and instrument\ncompositions reported to date for any formally verified financial\nsystem, it does. @sec-sanity then reports a separate set of sanity\nchecks on the discrete-hedging implementation that runs on top of the\nledger, confirming that the strategy and pricer layers reproduce\nstandard discrete-hedging benchmarks under synthetic GBM dynamics.\n\n## WRDS 2021–2023 calm-market holdout {#sec-wrds}\n\n\nThe WRDS OptionMetrics 2021–2023 holdout contains\n25\\,363 qualifying\ncall series drawn from the ATM ±3% filter applied to the full 2019–2024\npanel, restricted to the 2021–2023 sub-period to avoid overlap with the\nCOVID 2020 stress window. Every step audit record passes across all\n25\\,363 series;\nthe settlement theorem holds for every ITM and OTM settlement\nencountered in the panel. This is the framework guarantee verified on\ncalm-market real data.\n\nThe accompanying economic statistic, median cost/premium in the\nholdout of\n0\\.92\n(below 1.0), places the holdout in the calm-market half of the\ncost/premium distribution. The interpretation is that the hedger\ncaptures the variance risk premium: outside crisis windows, implied\nvolatility at inception systematically exceeds realized volatility over\nthe hedge horizon, so the hedger recovers more from the option premium\nthan she spends on rebalancing, a pattern documented by\n@bakshikapadia2003. The four crisis-regime panels in @sec-stress trace\nout the opposite half of the distribution.\n\n## Four historical stress regimes {#sec-stress}\n\n::: {.cell execution_count=3}\n\n::: {.cell-output .cell-output-display}\n![Real-data stress test under four historical market regimes. Each panel shows a violin plot of the cost-to-premium ratio (cost of replicating the call by delta hedging divided by the Black-Scholes premium received at inception) across all qualifying call series in the regime window. A ratio near 1.0 means the hedger broke even; above 1.0 means realized volatility exceeded the implied volatility quoted at inception (typical in crisis); below 1.0 means the hedger retained the variance risk premium (typical in calm markets). The four panels span four distinct regime archetypes: pandemic shock (COVID 2020), liquidity crisis (GFC 2008), instantaneous vol-shock (Volmageddon 2018), and a rate-driven drawdown (Q4 2018). The step audit record pass rate is 100% in every window, including the worst-case 1.69 median in COVID 2020. Source: WRDS OptionMetrics, ATM ±3% filter, 20–40 day expiry, ≥5 consecutive observations per series.](backtest-proofs_files/figure-pdf/fig-stress-output-1.pdf){#fig-stress}\n:::\n:::\n\n\nThe framework guarantee. Across the four crisis windows the step audit\nrecord pass rate is 100% in every panel (@fig-stress). The total\nobservation count across the four crisis windows is 37,246 option-day\nobservations spanning 3,289 qualifying call series; the ledger\ncertifies every step. This is the strongest single piece of empirical\nevidence for the framework claim: the runtime bridge correctly invokes\nthe proved kernel on price paths that the synthetic GBM simulator\ncannot produce, including sudden vol-regime shifts, sustained\nliquidity freezes, and abrupt rate-driven drawdowns. The Lean proofs hold without side\nconditions on the input distribution; the empirical question is\nwhether the bridge can break that guarantee in practice, and on the\n37,246 option-days tested it cannot.\n\nThe economic statistic. Cost/premium ratios **above** 1.0 during the\nGFC 2008 (median 1.23)^[The GFC 2008 window has N=42 qualifying call\nseries after the ATM ±3% filter and requiring ≥5 consecutive\nobservations; OptionMetrics coverage for early-dated options in 2008 is\nsparse and these results warrant caution.] and COVID 2020 (median\n1.69; February 19 through March 23, 2020) windows reflect the\ncrisis-period inversion of the variance risk premium: realized\nvolatility far exceeded implied volatility at option inception, so the\nrealized hedging cost exceeded the premium received. This is the\nopposite of normal conditions. @bakshikapadia2003 document that\ndelta-hedged gains are systematically negative on average (implied vol\n> realized vol, cost/premium < 1.0), with the negative VRP most\npronounced outside crisis periods; the WRDS 2021–2023 holdout median\nof 0\\.92\n(@sec-wrds) traces out that calm-market side, while the GFC and COVID\nmedians trace the crisis inversion. The ledger's settlement and\ntrade-accounting theorems hold regardless of whether cost/premium is\nabove or below 1.0: the realized P&L level is the strategy's economic\noutcome, not a property of the position ledger.\n\nThe Volmageddon window (January 22 through February 16, 2018; N=5,060\noption-day observations, 527 qualifying call series; median\ncost/premium 1.23) captures a qualitatively different stressor: an\ninstantaneous implied-volatility discontinuity rather than a sustained\nliquidity freeze. The VIX, which had traded near 11 for much of January\n2018, had already surged to approximately 17 by the close of Friday\nFebruary 2; on February 5 it spiked intraday to near 50, closing above\n37, among the largest single-day percentage spikes in the index's\nhistory to that date. Short-volatility exchange-traded products that\nhad accumulated positions betting on continued low-vol conditions were\neffectively wiped out in hours. For the options positions in this\nstudy, the shock manifested as a realized volatility that briefly\nexceeded the implied volatility embedded in premia set at position\ninception. The window is short (25 calendar days), which limits the\nsample relative to GFC or the WRDS holdout, but this is precisely what\nmakes it a clean stress test of the position ledger: the sudden jump\nin implied vol creates large, abrupt rebalancing trades that test the\ntrade-accounting formula under conditions of high price-sensitivity.\nAll 527 series pass every step audit record.\n\nThe Q4 2018 selloff (October 1, 2018 through January 31, 2019;\nN=25,090 option-day observations, 2,411 qualifying call series; median\ncost/premium 1.18) provides a third distinct regime type: a\n*rate-driven drawdown* in which implied volatility rose gradually\nrather than spiking. The S&P 500 fell approximately 20% peak-to-trough\nover the quarter, driven by Federal Reserve rate-hiking signals and\nescalating trade-policy uncertainty, before recovering sharply in\nJanuary 2019. This environment differs structurally from both GFC and\nVolmageddon: there was no single vol-shock event, and options\nmarket-makers continued to provide reasonable two-sided markets\nthroughout. The observed median of 1.18 (mildest of the four crisis\npanels, consistent with a gradual rather than sudden VRP reversal\n[@bakshikapadia2003]) confirms the intuition that a rate-driven\nselloff compresses the VRP less severely than a vol-shock event. The\nlarger sample reflects the better market-access conditions relative to\nthe GFC window. All 2,411 series pass every step audit record, with\nthe settlement theorem holding across all ITM and OTM settlements.\n\nAcross all four regimes (spanning the extremes of the VRP\ndistribution, two distinct vol-shock archetypes, and a rate-driven\ndrawdown) the position ledger certifies every step. The Lean 4 proofs\nhold without side conditions on the input distribution. The\nstress-regime results do not test the Lean proofs; they test whether\nthe Python execution layer and the runtime bridge correctly invoke the\nproved kernel across data that the synthetic GBM simulator cannot\nreplicate.\n\n## Multi-leg portfolios {#sec-multileg}\n\nDesign claim. Any multi-leg portfolio that produces integer-valued\ntrades in the basis-point representation inherits the verified\nposition ledger's guarantees without modification to the Lean sources.\nEach option leg routes through the same settlement and trade-update\nfunctions; the per-trade update is identical regardless of how many\nlegs the strategy holds. Two non-trivial exhibits, a short\nstraddle settled on the Hull paths and a bull call spread, test this\nclaim across both ITM and OTM settlement branches and across mixed\nlong-short positions.\n\n::: {.cell execution_count=4}\n\n::: {.cell-output .cell-output-display}\n![Short straddle (short call + short put, K=50) settlement on Hull 19.2 (call ITM, put OTM, S_T=57.25) and Hull 19.3 (call OTM, put ITM, S_T=48.12). Bars show payoff transferred per leg at expiry; all step audit records pass. Source: Hull (2014) Tables 19.2–19.3.](backtest-proofs_files/figure-pdf/fig-straddle-settlement-output-1.pdf){#fig-straddle-settlement}\n:::\n:::\n\n\nResult, short straddle. The two panels of @fig-straddle-settlement\ndecompose the per-leg payoff at expiry for a short straddle (short\ncall + short put, both at $K = 50$, $N = 100{,}000$ contracts) settled\non the Hull reference paths. On Hull 19.2 ($S_T = 57.25$) the call is\nin-the-money and the put is out-of-the-money; on Hull 19.3\n($S_T = 48.12$) the roles are reversed. Between the two panels the\nsettlement dispatcher therefore exercises both the ITM branch (which\ntransfers $\\max(S_T - K, 0) \\times N$ for the call and\n$\\max(K - S_T, 0) \\times N$ for the put) and the OTM branch (which\nreturns zero) for both option kinds.\n\n::: {.cell execution_count=5}\n\n::: {.cell-output .cell-output-display}\n![Bull call spread (long K=48, short K=52, N=100K) on the Hull 19.2 price path (S_T=57.25). Both calls expire ITM; net payoff = (52−48)×N = \\$400K. Portfolio value path (top) and per-step audit-record status (bottom, green=pass). Source: Hull (2014) Table 19.2.](backtest-proofs_files/figure-pdf/fig-bull-spread-output-1.pdf){#fig-bull-spread}\n:::\n:::\n\n\nResult, bull call spread. @fig-bull-spread traces the portfolio value\nof a bull call spread (long $K_{\\text{long}} = 48$, short\n$K_{\\text{short}} = 52$, $N = 100{,}000$ contracts) along the Hull\n19.2 path. Both legs expire in-the-money: the settlement function is\ninvoked once with a positive quantity (long leg) and once with a\nnegative quantity (short leg), and the net cash transfer\n$(K_{\\text{short}} - K_{\\text{long}}) \\times N = \\$400{,}000$ matches\nthe spread's theoretical maximum payoff exactly. The dashed green line\nin the upper panel marks this cap; the terminal portfolio value\ncoincides with it. Mid-path the portfolio value drops below zero\nbecause the short $K=52$ leg is closer to the money than the long\n$K=48$ leg during the drawdown phase of the price path, so the\nshort-leg mark-to-market loss temporarily dominates the long-leg gain;\nthe $400K cap is a terminal-settlement statement, not a path-wise\nupper bound. The lower panel reports the per-step audit-record status\nacross all rebalancing steps.\n\nInterpretation. The position ledger is strategy-agnostic at the type\nlevel. A multi-leg portfolio that resolves to a sequence of\ninteger-valued per-leg trades produces the same per-step audit records\nthe single-leg case produces, with no additional Lean proof\nobligations. The short straddle exercises the dispatcher across both\noption kinds and both moneyness states; the bull call spread exercises\na mixed long-short pair with a capped payoff. Both exhibits are\nconsistent with the framework operating without modification on\nnon-trivial multi-leg strategies, evidence that the verified ledger\ncovers the strategy classes a buy-side desk would build on top of it.\n\n# Sanity checks: discrete-hedging reproduces theory {#sec-sanity}\n\nThe proofs in @sec-ledger and the real-data evidence in @sec-results\nestablish the framework's primary claim: accounting errors of the\nsilent class are ruled out inside the verified kernel, and on every\nreal-data input the runtime bridge has been tested on, the audit\nrecords pass. This section reports a separate set of sanity checks on\nthe discrete-hedging implementation that runs on top of the ledger.\nThe checks ask whether the strategy implementation (delta computation,\nMonte Carlo simulator, Carr-Madan decomposition) behaves as standard\ndiscrete-hedging theory predicts under synthetic GBM dynamics. Failure\nof any of these checks would identify a bug in the strategy or pricer\nlayer, not in the position ledger; the ledger continues to certify\nevery step regardless of how the strategy performs.\n\nWe test three predictions from the discrete-hedging literature:\n(1) the running-mean realized hedging cost converges to the\nBlack-Scholes premium with deviation shrinking at rate $1/\\sqrt{n}$ in\nthe number of paths [@bertsimas2000]; (2) the standard deviation of\nrealized cost scales as $1/\\sqrt{N}$ in the rebalancing frequency\n[@bertsimas2000]; (3) the path-by-path realized cost is explained, to\nleading order, by the path-integrated gamma term in the Carr-Madan\ndecomposition [@carr1998; @carrwu2020]. We also report a high-power\nbootstrap specification test (@sec-bootstrap-summary) that probes both\nscaling laws at N=5,000-path resolution. None of these checks tests\nthe position ledger; the audit records continue to pass at every\nfrequency in every Monte Carlo path.\n\n## Monte Carlo convergence to Black-Scholes {#sec-mc}\n\nHypothesis. Under Black-Scholes assumptions and GBM dynamics, the\nrunning-mean realized cost of a discrete delta-hedge across a growing\nset of seeded Monte Carlo paths should converge to the Black-Scholes\npremium received at inception, with deviation shrinking at rate\n$1/\\sqrt{n}$.\n\n::: {.cell execution_count=6}\n\n::: {.cell-output .cell-output-display}\n![Empirical test of the Black-Scholes replication argument. Each new GBM path adds one realized hedging-cost observation to a running sample mean (blue line). Under perfect replication and GBM dynamics, the sample mean should converge to the Black-Scholes premium (green dashed) at rate $1/\\sqrt{n}$. The shaded green band marks a $\\pm 3\\%$ tolerance around the BS premium. A persistent offset outside the band, or non-convergence, would indicate an accounting bug or a model misspecification in the pricing layer. Source: 500 GBM paths, seed 20260519, $S_0 = 49$, $K = 50$, $\\sigma = 0.20$, $r = 0.05$, $T = 20$ weeks, $N_{\\text{contracts}} = 100{,}000$.](backtest-proofs_files/figure-pdf/fig-mc-output-1.pdf){#fig-mc}\n:::\n:::\n\n\nResult. Across 500 seeded GBM paths the\nrunning-mean hedging cost converges to the Black-Scholes price with a\nfinal deviation of 2\\.34%\n(@fig-mc). The headline number, 2.34% deviation at $n = 500$, lies\ninside the 3% tolerance band typically used to validate discrete-hedging\nimplementations against the continuous-time benchmark.\n\nInterpretation. The signed direction (running-mean cost below the BS\nprice) is the qualitative signature of the discrete-rebalancing bias\ndocumented by @boyle1980: under GBM with no transaction costs, discrete\ndelta hedging at $N=20$ steps under-replicates the\ncontinuously-rebalanced premium by an amount of order $\\Delta t$ from\nthe gamma-curvature interaction with discrete price increments. (The\n@leland1985 modified-volatility correction is the transaction-cost\nanalog and does not apply here, since the Monte Carlo sweep is run\nwith zero fees.) The signature is not that of an accounting error,\nwhich would produce a sign-and-magnitude-independent bias whose size\ndoes not shrink with rebalancing frequency; the linear-in-$\\Delta t$\nconvergence to zero is documented in @sec-appendix-error-decomp and\nrevisited under bootstrap confidence intervals in\n@sec-appendix-bootstrap. Convergence inside the tolerance band is\nconsistent with the running-mean cost reflecting the GBM hedging error\nalone, with no residual contribution from the ledger.\n\n## BKL variance scaling and Carr-Madan attribution {#sec-bkl-cm}\n\nHypothesis. The joint hypothesis combines two predictions from the\ndiscrete-hedging literature. First, the standard deviation of the\nrealized hedging cost should scale as $1/\\sqrt{N}$ in the rebalancing\nfrequency $N$ [@bertsimas2000]. Second, the path-by-path realized\nhedging cost should be explained, to leading order, by the\npath-integrated gamma term in the Carr-Madan decomposition\n[@carr1998; @carrwu2020]. These two predictions together pin down both\nthe rate at which hedging-cost dispersion shrinks with rebalancing\nfrequency and the dominant source of dispersion at a fixed frequency.\n\n::: {.cell execution_count=7}\n\n::: {.cell-output .cell-output-display}\n![Bertsimas-Kogan-Lo variance scaling test. Each blue point is the sample standard deviation of total hedging cost across 500 GBM paths at a given rebalancing frequency $N$, plotted against $1/\\sqrt{N}$. BKL theory predicts std(cost) $\\propto 1/\\sqrt{N}$, a straight line through the origin (red dashed, anchored at $N=20$). The empirical slope exceeds the theoretical line by 13%, the discrete-rebalancing correction characterized by @boyle1980. An accounting bug would instead produce a variance floor that does not shrink with $N$. Source: 500 GBM paths per frequency.](backtest-proofs_files/figure-pdf/fig-bkl-output-1.pdf){#fig-bkl}\n:::\n:::\n\n\nResult, BKL scaling. The empirical ratio std(N=10) / std(N=20) =\n1\\.372 against the theoretical\n$\\sqrt{2} \\approx 1.414$ (@fig-bkl). Across five rebalancing\nfrequencies the empirical slope of the std vs. $1/\\sqrt{N}$ regression\nsits within 13% of the BKL theoretical slope; the excess is the\ndiscrete-rebalancing correction documented by @boyle1980, not an\naccounting failure.\n\n::: {.cell execution_count=8}\n\n::: {.cell-output .cell-output-display}\n![Carr-Madan gamma attribution. The decomposition predicts that the realized discrete-hedge cost equals the cumulative path-integrated gamma P\\&L $\\int \\frac{1}{2} \\Gamma_t S_t^2 \\sigma^2 dt$ plus higher-order terms (theta, vega, path noise). Each blue point is one GBM path; the red line is OLS. The Pearson correlation $r = 0.951$ implies a single-factor gamma regression explains 90.4% of the variance in realized cost; the remaining 10% sits in the higher-order terms the single-factor model omits. A structural ledger bug would scatter points off the line in a pattern uncorrelated with gamma. Source: 200 GBM paths.](backtest-proofs_files/figure-pdf/fig-cm-output-1.pdf){#fig-cm}\n:::\n:::\n\n\nResult, Carr-Madan attribution. Hedging cost correlates with\npath-integrated gamma P\\&L at\nr = 0\\.951 across 200\npaths (@fig-cm). The Carr-Madan decomposition [@carr1998; @carrwu2020]\npredicts that realized cost lies on the 45-degree line against\npath-integrated gamma P\\&L; the observed correlation\n$r \\approx 0.951$ means\n90\\.4% of cost variance is\nexplained by the gamma term alone, with the residual attributable to\ntheta, vega, and higher-order discretization terms [@carrwu2020].\n\nInterpretation. The two results jointly rule out a structural\naccounting bug. Such a bug, taken as a constant-magnitude per-step\nerror, would produce two visible signatures: a variance floor that\ndoes not shrink as the rebalancing interval shrinks (breaking BKL\nscaling), and a path-by-path cost component uncorrelated with gamma\n(breaking the Carr-Madan attribution). The empirical data show neither\nsignature: the standard deviation contracts as $1/\\sqrt{N}$ at the\npredicted rate, and the cost-by-path scatter sits tightly on the\n45-degree line against the gamma proxy. A statistically rigorous\nversion of the BKL and Leland scaling tests, with bootstrap pointwise\nconfidence intervals fit by a smoothing spline, is reported in\nAppendix C (@sec-appendix-bootstrap).\n\n## Bootstrap specification test {#sec-bootstrap-summary}\n\nThe point estimates in @sec-mc and @sec-bkl-cm rely on five\nrebalancing frequencies and 500 paths per frequency, which is enough\npower to verify the qualitative form of each scaling law but not\nenough to distinguish leading-order theory from higher-order\ncorrections. We re-run the variance and bias sweeps at 20 log-spaced\nfrequencies and 5,000 paths each, generate B=1,000 bootstrap resamples\nper frequency, and test whether the parametric form lies inside the\npointwise 95% confidence band of a smoothing-spline nonparametric\nregression [@shalizi2013] applied to the residuals. The full result,\nincluding residual panels and the spline fit at finer resolution, is\nin @sec-appendix-bootstrap.\n\nRestricted to the operationally relevant range $N \\in [20, 80]$, two\nfindings stand out. The Boyle-Emanuel O($\\Delta t$) mean-bias\nconvergence passes the specification test: the smoothing spline on the\nresiduals stays inside the bootstrap band around zero throughout,\nconsistent with the linear-in-$\\Delta t$ convergence documented by\n@boyle1980 and treated to higher order by @bertsimas2000. The BKL\nvariance scaling does not pass: the residual spline detects a small\npositive arch in the practical range, and the leading-order $C/\\sqrt{N}$\nlaw under-fits by a margin that the 1,000-bootstrap confidence band\ncannot accommodate. The deviation is small in absolute terms (a few\npercent of the standard deviation) and shrinks as $N$ grows, but it is\ndetectable at N=5,000 paths. This is a known finite-N gamma-curvature\ncorrection discussed in @bertsimas2000; the qualitative scaling is\nintact, while the linear-through-origin point estimate in @sec-bkl-cm\nis detectably biased at high resolution.\n\nBoth findings are consistent with the position ledger certifying every\nstep at every frequency in the 100,000-simulation sweep; the bootstrap\ntest interrogates the strategy and pricer layer's compliance with\nasymptotic theory, not the ledger.\n\n# Discussion {#sec-discussion}\n\n## What the proofs guarantee {#sec-proof-scope}\n\nThe Lean 4 proofs hold for every integer-representable input, with no\nside conditions on the input distribution or the strategy that produces\nthe inputs. This is categorically different from testing. Testing\nsamples the input space; the proofs quantify over it. The\nportfolio-value identity, trade accounting, cash update, quantity\nconservation, and self-financing properties are discharged by Lean's\nkernel at compile time, not at runtime.\n\nThe proofs do not establish that the Black-Scholes delta hedge converges\nto the option premium (a probabilistic claim about the pricing layer);\nthey do not establish that geometric Brownian motion describes real\nequity dynamics; they do not establish that the strategy is profitable\nin any specific market regime. Those claims belong to Sections 5 and 6\nand are empirical. A user who finds that hedging cost deviates from the\nBlack-Scholes price by 15% can rule out a ledger error as the cause, but\ncannot rule out model misspecification.\n\nThe Python runtime bridge that passes integer inputs to the proved\nkernel is itself unproved. The proof holds for the integers the bridge\npasses, not for the bridge itself. A bridge bug therefore surfaces as a\nstep audit record failure rather than as silent corruption of the\nledger: any mismatch between the proved invariant and the runtime state\nis rejected at the boundary. The stress-regime results in @sec-stress\nshow every audit record passing across vol spikes, liquidity crises, and\nregime changes.\n\nFor a model validator operating under SR 11-7 [@sr117], the step audit\nrecord architecture provides machine-readable evidence of ledger\nbehavior at every state transition, satisfying the standard's\nongoing-monitoring requirement for the position ledger without manual\nre-derivation.\n\n## Limitations {#sec-limitations}\n\nFour limitations bound the current results. First, the Black-Scholes\nimplementation uses a flat implied volatility (the per-series\ninception-date value) rather than a dynamic volatility surface. The\nempirical volatility smile means real hedging errors exceed the\nflat-$\\sigma$ prediction for in-the-money and out-of-the-money options,\nbecause the delta is computed under an incorrect local volatility when\nthe smile is steep. @hull2014 [Ch. 20] documents that delta-hedging\nerrors grow with the curvature of the volatility surface;\n@elkaroui1998 establish the formal superhedging bound: a flat\nimplied-volatility hedge is a superhedge when the assumed volatility\ndominates the true local volatility, providing a one-sided bound on the\nhedging error. Of the four limitations, this one has the largest\nquantitative effect on the discrete-hedging sanity checks. Results in\nlow-IV regimes (2021 to 2023) are more reliable than results in\nhigh-IV regimes (COVID 2020, Volmageddon 2018), where the smile is\nsteepest. The position ledger's per-step audit records hold regardless\nof the IV assumption.\n\nSecond, the settlement and payoff results are proved for European-style\noptions only. American-style early exercise and barrier events require\nnew settlement modules and new invariants: the settlement function must\ndispatch on an exercise boundary condition, and the corresponding result\nmust quantify over the early-exercise policy. These extensions are\nstructurally straightforward but not yet implemented.\n\nThird, transaction costs are modeled as a fixed fee per trade.\nProportional costs (bid-ask spreads, market impact) are deferred. The\nflat-fee model is conservative for large rehedge sizes and generous for\nsmall ones. Extending to proportional costs would let the position\nledger connect directly to the Leland [-@leland1985] modified\nvolatility, yielding a verified replication-cost bound under\nproportional transaction costs.\n\nFourth, the runtime bridge between the proved Lean kernel and the\nPython execution layer is itself not formally verified. The bridge\nmarshals integer-basis-point inputs across the FFI boundary, applies\nthe type-level invariants of `Portfolio`, `Position`, and `Trade`\nbefore invoking the kernel, and emits the step audit record by\ncomparing the proved prediction to the observed P&L change. A bug in\nthe bridge therefore surfaces as a step audit record failure rather\nthan as silent ledger corruption, but the bridge could in principle\nfail to invoke the kernel at all on a given step, in which case the\naudit record would not be emitted. The replication test suite\n(@sec-replication) exercises the bridge across every supported\nstrategy and asserts that the per-step record is produced; this is\nempirical evidence rather than a proof. Verifying the bridge itself\nwould require either CakeML-style certified extraction\n[@kumar2014] or a proof in a dependently typed FFI layer, both of\nwhich are open engineering problems beyond the present scope.\n\n## Toward a provably correct research desk {#sec-extensions}\n\nNot every layer of a quant pipeline merits formal verification. The\nvaluable targets are layers where bugs are silent (the output looks\nplausible), survive testing (they manifest only on inputs the test\nauthor did not anticipate), and compound downstream (one ledger error\ncontaminates every Sharpe ratio, every regime test, every\ncross-strategy comparison). The position ledger meets all three\ncriteria. So does the reconciliation layer that sits upstream of it\n(trade-booking bugs produce position drift that a correct ledger then\npropagates faithfully), and so does the risk-decomposition layer that\nsits downstream, where verified Greeks and P&L attribution compose\nwith the ledger's audit trail into a checked pipeline from trade to\nreported risk number. The Black-Scholes pricer, by contrast, does\nnot: a pricing bug produces visibly wrong prices that a QuantLib\ncomparison catches in minutes (@sec-appendix-quantlib). The strategy\nlogic does not either: a strategy bug produces visibly wrong trades.\nThe empirical sections of this paper confirm that the implementation\nof these less-deep layers works on real data without proof, and the\nQuantLib cross-check formalizes the operational tolerance practitioners\nuse to validate them.\n\nThe concrete next step is the reconciliation layer. Bugs there are the\nupstream analog of the position-ledger bugs catalogued in the\nintroduction: they look like correct trades until a downstream P&L\nattribution surfaces a discrepancy days or weeks later. Specifying\ntrade booking in Lean against the same integer-basis-point arithmetic\nthe position ledger uses closes the loop between order execution and\nthe verified accounting kernel. Beyond that, a verified risk\ndecomposition (Greeks, P&L attribution) composes naturally with the\nledger's audit trail; a deep hedging [@buehler2019] policy running on\nthe verified ledger inherits the accounting guarantees regardless of\nhow the policy was trained. We sketch the reconciliation specification\nin a companion note; the rest is left to future work.\n\n## Data availability {#sec-data-availability}\n\nThe synthetic Monte Carlo and deterministic-path results in this paper\nare fully reproducible from the public repository. WRDS OptionMetrics\ndata is licensed and is not redistributed under WRDS terms; the\nlicensed sample is required only to reproduce the WRDS holdout and\nstress-regime panels in @sec-results. Replication instructions, exact\nparameter values, and the metrics snapshot are in the appendix.\n\n```{=latex}\n\\clearpage\n\\appendix\n\\part*{Appendix}\n\\addcontentsline{toc}{part}{Appendix}\n```\n\n# Falsification exhibit: code listing {.appendix #sec-appendix-falsification}\n\nThe following code exhibit demonstrates the bug described in\n@sec-falsification. The complete exhibit is in\n`backtest-proofs/python/tests/test_backtest.py`, class\n`TestFalsification`.\n\n```python\nfrom backtest_proofs.backtest.audit import verify_step\n\nPV_BEFORE     = 1_000_000   # $100.00 in basis points\nEXEC_PRICE_BP =   500_000   # $50.00\nMARK_BEFORE   =   490_000   # $49.00 (price moved up $1)\nFEE_BP        =         0\n\n# --- Case 1: pre_trade_qty = 0 (first purchase) ---\n# BUG: pv_after = pv_before (cash not debited)\ncert = verify_step(\n    pv_before=PV_BEFORE, pv_after=PV_BEFORE,   # cash not debited\n    pre_trade_qty=0, exec_price_bp=EXEC_PRICE_BP,\n    mark_before_bp=MARK_BEFORE, fee_bp=FEE_BP, step=0,\n)\nassert cert.invariant_holds   # passes: trade accounting predicts dPV=0\n\n# --- Case 2: pre_trade_qty = 500 (existing holding) ---\n# trade accounting predicts: 500 x (500_000 - 490_000) = 5_000_000 bp\n# BUG still produces pv_after = pv_before, so delta_pv = 0 != 5_000_000\nverify_step(\n    pv_before=PV_BEFORE, pv_after=PV_BEFORE,   # cash not debited\n    pre_trade_qty=500, exec_price_bp=EXEC_PRICE_BP,\n    mark_before_bp=MARK_BEFORE, fee_bp=FEE_BP, step=1,\n)\n# raises: ValueError: Accounting invariant violated at step 1:\n#   delta_pv=0 bp, expected=5000000 bp\n```\n\nThe first call (pre_trade_qty=0) passes the step audit check because\nthe trade-accounting identity predicts $\\Delta \\text{PV} = 0$\nregardless of cash accounting. The second call (pre_trade_qty=500)\nraises immediately: the expected change of 5,000,000 basis points\ndoes not match the observed change of 0.\n\n# Theorem Statements {.appendix #sec-appendix-theorems}\n\nThe eight substantive theorems and the three payoff-sign obligations\nsummarised in @tbl-theorems are reproduced below in their Lean 4 form,\nverbatim from the repository at commit\n0dec283. All eleven compile under `lake build` with\nzero `sorry` placeholders. Source: `backtest-proofs/lean/BacktestProofs/`\n(`Invariants.lean`, `SettlementInvariants.lean`) and\n`quant-core/lean/QuantCore/OptionInvariants.lean`.\n\n**Portfolio-value identity.** Every ledger-admissible portfolio\nsatisfies `portfolioValue = cash + Σ position_values`. The right-hand\nside is a fold over the position HashMap.\n\n```lean\ntheorem valueIdentity (p : Portfolio) :\n    p.portfolioValue = p.cash + sumPositionValues p.positions\n```\n\n**Cash update.** Applying a trade debits cash by the signed quantity\ntimes the execution price plus the fee. The statement is definitional\n(`rfl`), reflecting that the `applyTrade` function is specified by\nthis equation.\n\n```lean\ntheorem cashUpdateCorrect (p : Portfolio) (t : Trade) :\n    (applyTrade p t).cash =\n      p.cash - (t.deltaQuantity * t.executionPrice + t.fee) := rfl\n```\n\n**Quantity conservation.** The post-trade quantity for the traded\nasset equals the pre-trade quantity plus the signed trade size; all\nother position quantities are untouched.\n\n```lean\ntheorem quantityConservation (p : Portfolio) (t : Trade) :\n    (applyTrade p t).getQuantity t.assetId =\n      p.getQuantity t.assetId + t.deltaQuantity\n```\n\n**Trade-accounting identity.** The change in portfolio value under a\nsingle trade is the pre-trade quantity times the spread between the\nexecution price and the prevailing mark, minus the fee. This is the\nidentity the step audit record checks at runtime.\n\n```lean\ntheorem valueUpdateFormula (p : Portfolio) (t : Trade) :\n    (applyTrade p t).portfolioValue =\n      p.portfolioValue\n        + p.getQuantity t.assetId\n          * (t.executionPrice - p.getMarkPrice_orZero t.assetId)\n        - t.fee\n```\n\n**Self-financing (fee-free).** A costless trade at the prevailing mark\nleaves portfolio value unchanged.\n\n```lean\ntheorem selfFinancing (p : Portfolio) (t : Trade) (pos : Position)\n    (hPos   : p.getPosition t.assetId = some pos)\n    (hPrice : t.executionPrice = pos.markPrice) :\n    (applyTrade p t).portfolioValue = p.portfolioValue - t.fee\n```\n\n**Self-financing with a fixed fee.** A trade at the prevailing mark\nreduces portfolio value by exactly the fee. The current formalization\ntakes the fee as a fixed integer per trade; extending to proportional\ncosts $\\text{fee} = c \\cdot |q| \\cdot p_{\\text{exec}}$ requires a new\nlemma binding `t.fee` to the proportional rate, which is sketched in\n@sec-limitations.\n\n```lean\ntheorem selfFinancingWithCost (p : Portfolio) (t : Trade) (fee : Int)\n    (pos : Position)\n    (h_fee  : t.fee = fee)\n    (hPos   : p.getPosition t.assetId = some pos)\n    (hPrice : t.executionPrice = pos.markPrice) :\n    (applyTrade p t).portfolioValue = p.portfolioValue - fee\n```\n\n**Well-formedness preservation.** Applying any trade to a well-formed\nportfolio yields a well-formed portfolio. `WellFormed` packages the\ntype-level invariants: positive mark prices, non-negative fees, and\nthe value-identity equation.\n\n```lean\ntheorem applyTrade_wellFormed (p : Portfolio) (t : Trade)\n    (hw : p.WellFormed) :\n    (applyTrade p t).WellFormed\n```\n\n**Settlement.** Settling a European option at expiry changes portfolio\nvalue by the position quantity times the spread between the option's\npayoff and its pre-expiry mark.\n\n```lean\ntheorem settlement_value_formula (p : Portfolio) (opt : EuropeanOption)\n    (pos : Position)\n    (hPos : p.getPosition opt.assetId = some pos)\n    (spot : Int) :\n    (applySettlement p opt\n        (settleEuropeanOption opt spot pos.quantity)).portfolioValue =\n      p.portfolioValue\n        + pos.quantity * (optionPayoff opt spot - pos.markPrice)\n```\n\n**Payoff non-negativity (three obligations).** Call, put, and the\ndispatched `optionPayoff` are non-negative for all integer-valued\ninputs. These follow from the `max(·, 0)` definition of payoff and are\nthe type-level economic guarantee that the option holder is never\ncharged at expiry.\n\n```lean\ntheorem callPayoff_nonneg (spot strike : Int) :\n    callPayoff spot strike ≥ 0\n\ntheorem putPayoff_nonneg (spot strike : Int) :\n    putPayoff spot strike ≥ 0\n\ntheorem optionPayoff_nonneg (opt : EuropeanOption) (spot : Int) :\n    optionPayoff opt spot ≥ 0\n```\n\nTogether these eleven results discharge every property a step audit\nrecord can check at runtime. A failure of the audit-record check is\ntherefore necessarily a runtime-bridge failure (a value crossed the\nFFI boundary that did not satisfy `Portfolio.WellFormed` or\n`Trade`'s structural invariants) rather than a counterexample to any\nof the theorems above.\n\n# Proof Architecture {.appendix #sec-appendix-architecture}\n\n*This section is a technical reference for developers wishing to inspect\nor extend the Python runtime bridge. QF/FM readers may skip to\nAppendix C.*\n\nThe formal development compiles via `lake build` to a native shared\nlibrary (`.so`) through Lean 4's LLVM backend. A Cython extension\n(`ffi/lean_ffi.pyx`) wraps the exported C symbols (`@[export hedge_*]`);\n`ffi/__init__.py` pre-loads `libleanrt` and `libuv` before importing the\nextension. Python calls the compiled kernel at runtime with no\nserialization overhead. All numeric values crossing the FFI boundary are\nbasis-point integers ($\\times 10{,}000$ of dollar values). See\n`backtest-proofs/DECISIONS.md` ADR-006 for the rationale behind the\nCython FFI design choice.\n\n# Variance Scaling and Bootstrap Specification Test {.appendix #sec-appendix-bootstrap}\n\n@bertsimas2000 and @leland1985 predict specific relationships between\ndiscrete delta-hedge cost variance, mean bias, and rebalancing frequency;\nthe exhibits below test those predictions. Both sets of results are\nplaced in the appendix because they concern the behavior of the\ndiscrete-hedging model, not the correctness of the position ledger.\nThe position ledger certifies every step at all frequencies; these\nexhibits are about finance theory.\n\n## Leland (1985) rehedge-frequency sweep {#sec-leland}\n\n::: {.cell execution_count=9}\n\n::: {.cell-output .cell-output-display}\n![Rehedge-frequency variance sweep replicating Leland (1985) Table II. Blue dots: empirical std(cost) for N $\\in$ {5, 10, 20, 40, 80} rebalancing steps (500 paths each). Red dashed: BKL theory (std $\\propto 1/\\sqrt{N}$), anchored at N=20. Source: synthetic GBM, seed 20260519.](backtest-proofs_files/figure-pdf/fig-leland-output-1.pdf){#fig-leland}\n:::\n:::\n\n\nAcross N=5 to N=80, std(hedging cost) falls monotonically with\nrebalancing frequency, as Leland [-@leland1985] predicted. The\nempirical slope of the std vs. 1/sqrt(N) line exceeds the BKL\ntheoretical slope by approximately 13% at every frequency tested.\n@kabanovSafarian1997 prove that the limiting variance under Leland's\nmodified volatility is strictly positive (contradicting Leland's\noriginal claim of zero asymptotic error); the 13% excess above the\nleading-order BKL slope is the measurable consequence of this\nnonzero term, not a defect in the backtester.\n\n::: {.cell execution_count=10}\n\n::: {.cell-output .cell-output-display}\n![Mean relative bias (E[cost] − BS) / BS vs. rebalancing interval Δt = T/N for N $\\in$ {5, 10, 20, 40, 80, 160} steps (500 paths each). Blue dots: empirical mean bias. Red dashed: OLS fit through the origin (mean_bias = a × Δt). The negative sign and linear-in-Δt convergence to zero are consistent with the discrete-rebalancing bias documented by @boyle1980 for GBM dynamics with zero transaction costs; the Leland (1985) modified-volatility correction is the transaction-cost analog and does not apply at zero TC. Source: synthetic GBM, seed 20260519.](backtest-proofs_files/figure-pdf/fig-leland-bias-output-1.pdf){#fig-leland-bias}\n:::\n:::\n\n\nThe mean relative bias decreases linearly toward zero as the rebalancing\ninterval Δt = T/N shrinks, with the OLS fit through the origin achieving\n$R^2 =$ 0\\.720 and slope\n\\-0\\.329 (@fig-leland-bias). This empirical\nlinearity is the O(Δt) signature documented by @boyle1980 for GBM\ndynamics with zero transaction costs and consistent with the\nhigher-order treatment of @bertsimas2000: under discrete delta hedging\nof a written call, the gap between expected hedge cost and the\nBlack-Scholes price contracts proportionally to T/N, not to $\\sqrt{T/N}$\n(which would indicate random noise) or to a constant (which would\nindicate a structural accounting bug). The sign is negative throughout\n(cost lies below the BS price), consistent with the well-known result\nthat discrete replication under-replicates the continuously-rebalanced\nBlack-Scholes premium in the zero-transaction-cost case [@boyle1980].\nAs N increases from 5 to 160, the bias shrinks by a factor of 32,\ntracking T/N exactly.\n\nThe O(Δt) linear convergence rules out the two alternative explanations\nfor the nonzero mean\nreported in §6: a structural accounting bug would produce a bias that\ndoes not converge to zero with N (the ledger error would be present\nregardless of rebalancing frequency), while stochastic path variance\nwould produce a $O(1/\\sqrt{N})$ decay in the mean, not an O(1/N) = O(Δt)\ndecay. The observed linear convergence with\n$R^2 >$ 0\\.720 is consistent only with the\ndiscrete-replication interpretation. All step audit records pass for all\n500 paths at each of the six frequencies, confirming that the accounting\nkernel certifies the ledger regardless of the realized direction of the\nbias.\n\n## Bootstrap specification test for BKL and Leland scaling {#sec-bootstrap}\n\nThe point estimates above rely on OLS through the origin with $R^2$ as\nthe goodness-of-fit diagnostic, a parametric criterion that assumes\nlinearity and homoskedasticity. A more rigorous check applies\nnonparametric regression to the same data, constructs bootstrap\nconfidence bands, and asks whether the theoretical parametric curve lies\nwithin those bands everywhere. The standard nonparametric\nregression specification test\n[@shalizi2013] fits a\nflexible smoother (a smoothing spline with automatic bandwidth selection)\nto the residuals of each parametric fit (BKL and Leland); if the\nsmoother stays inside the bootstrap band around zero everywhere, the\nparametric form is plausible.\nIf the smoother wanders systematically away from zero, the parametric\nform is missing some structure in the data.\n\n::: {.cell execution_count=11}\n\n::: {.cell-output .cell-output-display}\n![Bootstrap specification test for BKL variance scaling (left two panels) and Leland O(Δt) mean-bias convergence (right two panels). Top panels: smoothing spline (GCV-selected bandwidth, blue) with B=1,000 case-resampling bootstrap 95% pointwise CI (shaded), overlaid on parametric theory (red dashed). Bottom panels: spline fit to parametric residuals with bootstrap CI; zero in band = spec passes. N=5,000 paths per frequency, 20 log-spaced frequencies N ∈ {3…400} (100,000 total simulations), B=1,000 bootstrap resamples.](backtest-proofs_files/figure-pdf/fig-bootstrap-spec-output-1.pdf){#fig-bootstrap-spec}\n:::\n:::\n\n\nThe top panels of @fig-bootstrap-spec show a GCV-bandwidth smoothing\nspline nonparametric regression (blue curve) with B=1,000\ncase-resampling bootstrap 95% pointwise confidence intervals (shaded\nband), using N=5,000 paths at each of 20 log-spaced frequencies from N=3\nto N=400 (100,000 simulations total). The theoretical parametric curves\n(red dashed) are overlaid on the spline estimates. The bottom panels\napply the **specification test** [@shalizi2013]: the smoothing spline\napplied to the parametric residuals (data minus theory), with the\nbootstrap band for those residuals. The zero horizontal line represents\nthe null hypothesis that the parametric model is correctly specified; if\nzero lies within the band throughout, the data are consistent with the\ntheory.\n\nThe high-power simulation uses N=5,000 paths at each of 20\nlog-spaced frequencies with B=1,000 bootstrap resamples.\nThe BKL and Leland laws are *asymptotic*\nresults: they describe leading-order behavior as $N \\to \\infty$ and\n$\\Delta t \\to 0$, and the extended simulation is sensitive enough to\ndetect finite-N corrections at the extremes of the frequency range.\n\n**BKL variance scaling** (FAIL in\nN ∈ [20, 80]; 25% of all 14 frequencies\nwithin CI)**:** The BKL leading-order law std $\\propto C/\\sqrt{N}$ has\ndetectable systematic deviations even in the operationally relevant\nfrequency range. The residual spline shows a positive arch in the\nN ∈ [10, 80] region: the empirical std exceeds the OLS-through-origin\nprediction by a margin that the bootstrap CI cannot accommodate. This\nreflects a known limitation of the leading-order BKL approximation: the\n$C/\\sqrt{N}$ law is exact only in the limit as the Black-Scholes model\nparameters satisfy specific conditions, and finite-N corrections from the\ngamma-curvature interaction introduce a concave-then-convex pattern in\nthe residuals. The deviation is small in absolute terms (a few percent of\nstd) and shrinks as N grows, but it is detectable with 28,000 simulation\npaths.\n\n**Leland O(Δt) bias:** The Leland linear-through-origin model fits within\nthe bootstrap CI for 90% of\nfrequencies, and passes the specification test over the practical range\nN ∈ [20, 80] (PASS). The\nresidual panel shows that at very large $\\Delta t$ (small N), the mean\nbias is less negative than the leading-order O($\\Delta t$) prediction:\nthe extreme discrete paths partially recover toward the continuous limit\ndue to a different balance between gamma-P&L and theta-P&L at very coarse\ngrids. At very small $\\Delta t$ (large N), the mean bias is so small that\nindividual path noise dominates, and the spline fit to residuals wanders\nwithin the wide CI.\n\nThe asymptotic laws are accurate for operationally\nrelevant frequencies (N ∈ [20, 80] corresponding to daily-to-weekly\nrebalancing) but show detectable finite-N corrections at extremes where\nhigher-order theory applies. This is a stronger empirical claim than the\nearlier $R^2$ regressions, which had insufficient power (500 paths,\n5–6 frequencies) to distinguish leading-order from next-order behavior.\nThe position ledger certifies every step at all 14 frequencies and\nall 2,000 paths, regardless of which asymptotic regime the\nrebalancing frequency sits in.\n\n\n# Error decomposition {.appendix #sec-appendix-error-decomp}\n\nThe four diagnostics below decompose the discrete-hedging error reported\nin @sec-mc and @sec-bkl-cm into a structural-bias component, a\ngamma-attribution component, a variance-scaling exponent, and a\nfloating-point precision floor. Together they characterize the error\nregime and distinguish discrete-hedge variance from any candidate\nledger bug.\n\n\nZero-bias test. A one-sample t-test on the relative error\n$(c_i - \\text{BS}) / \\text{BS}$ across 500 paths\nyields $t =$ \\-2\\.79,\n$p =$ 0\\.0054, with mean error\n\\-2\\.34% and standard deviation\n18\\.67%. The null of zero mean is rejected at\nthe 1% level; the mean lies\n0\\.13 standard deviations\nbelow zero. The signed direction (negative: hedging cost below BS\nprice) is consistent with the O($\\Delta t$) discrete-rebalancing bias\ndocumented by @boyle1980 under GBM with zero transaction costs, not\nwith an accounting bug, which would produce a positive or\npath-dependent bias. The mean is\neconomically small relative to the standard deviation (ratio\n0\\.125). The t-test has\nasymptotic validity under the CLT at $n = 500$; a Wilcoxon signed-rank\ntest on the same sample confirms the same directional conclusion (cost\nbelow BS price, $p < 0.01$).\n\nCarr-Madan variance attribution. Across 200 GBM paths the OLS\nregression of hedging cost on gamma P\\&L yields\n$R^2 =$ 0\\.904, slope\n0\\.940 (expected 1.0 under the Carr-Madan\nidentity), and residual standard deviation\n$\\$14\\,245$. The OLS slope is\ndownward-attenuated relative to 1.0 by discretization error in the\ngamma P\\&L regressor (errors-in-variables bias); the $R^2$ is the more\ninterpretable diagnostic. The $R^2$ of\n0\\.904 means\n90\\.4% of hedging cost variance is explained\nby the one-factor gamma P\\&L term alone; the remaining\n9\\.6% reflects higher-order terms\n(theta P\\&L, vega, path-specific discretization noise) that the\nsingle-factor Carr-Madan model does not capture. A structural\naccounting error (mis-signed cash flows, dropped settlement, wrong\nquantity) would appear as a systematic outlier cluster uncorrelated\nwith gamma, not as gamma-proportional scatter.\n\nBKL log-log slope. A log-linear regression of $\\log(\\text{std})$ on\n$\\log(1/N)$ across five rebalancing frequencies yields slope\n0\\.462 (BKL theory: 0.5) with\n$R^2 =$ 0\\.9981. The near-perfect fit\n($R^2 > 0.99$) confirms that variance grows exactly as $1/N$, the\nhallmark of independent per-step errors that wash out with hedging\nfrequency. Structural errors would manifest as a floor that does not\nshrink with $N$.\n\nFloating-point precision. The basis-point conversion routines round\nto the nearest integer at $\\leq 0.5$ bp per call. Over\n20 rebalancing steps with approximately two\nconversions per step, independent rounding accumulates to a standard\ndeviation of about\n$\\$1\\,550$\n(0\\.65% of the BS price), which is\n3\\.5% of the empirical\nhedging-cost standard deviation. Basis-point rounding contributes\nnegligibly to observed variance.\n\n# Hull Table 19.2 / 19.3 deterministic cross-check {.appendix #sec-appendix-hull}\n\nThe Hull (2014) textbook tabulates a deterministic 20-step weekly\nhedge of a written ATM call ($S_0 = 49$, $K = 50$, $r = 5\\%$,\n$\\sigma = 20\\%$, $T = 20$ weeks) under two realized price paths:\nTable 19.2 ends ITM at $S_T = 57.25$; Table 19.3 ends OTM at\n$S_T = 48.12$. Hull's printed cost-of-hedging figures ($263{,}300 and\n$256{,}600 respectively) incorporate textbook rounding conventions\n(delta to three decimal places, share counts to the nearest hundred,\ndollar amounts to the nearest hundred) that introduce noise of several\nthousand dollars on a $\\sim$\\$250K hedging cost. The cleaner test is\nto recompute the hedge in Python using the same basis-point integer\narithmetic the Python runtime bridge uses, and compare the two NAV\npaths point by point.\n\n::: {.cell execution_count=13}\n\n::: {.cell-output .cell-output-display}\n![Cross-check of the Python runtime bridge against an independent Python reference implementation that uses identical basis-point integer arithmetic. **Top row:** week-by-week NAV path for Hull Table 19.2 (left, ITM expiry) and Table 19.3 (right, OTM expiry). The Python runtime bridge (blue solid) and the manual reference (red dashed) are visually indistinguishable. **Bottom row:** signed deviation between the two NAV series at each week, in dollars (note the $25/\\$50 y-axis range against $\\sim$\\$250K hedging cost). Total-cost agreement is annotated. The two implementations agree to within $\\sim 1$ basis point throughout, well below the noise floor of Hull's printed values, confirming that the Python runtime bridge does not introduce drift on top of the proved position ledger.](backtest-proofs_files/figure-pdf/fig-hull-output-1.pdf){#fig-hull}\n:::\n:::\n\n\nThe two implementations agree to\n1\\.12 bp on the ITM path and\n0\\.74 bp on the OTM path. The remaining\ndiscrepancy is cumulative basis-point rounding through the FFI\nboundary; the noise floor for end-to-end cross-checks of this kind is\nabout 1 bp per 20-step hedge. Hull's printed cost-of-hedging figures\nsit roughly 3 to 4% above both implementations; the difference is\nfully explained by the textbook's three-decimal-place delta rounding\nand hundred-share rounding rules. All step audit records pass for both\npaths.\n\n# QuantLib pricing cross-check {.appendix #sec-appendix-quantlib}\n\nQuantLib is an open-source C++ derivatives library widely used in\nquantitative finance. Comparing the basis-point integer Black-Scholes\npricer to QuantLib's analytic pricer at matched inputs isolates the\npricing layer from the position ledger: if the two pricers agree, the\ncost figures elsewhere in the paper cannot be attributed to a\npricing-implementation bug. Practitioners reviewing this work will\nrecognize the comparison as the standard vendor cross-check used by\nvalidation desks for new derivatives systems.\n\n::: {.cell execution_count=14}\n\n::: {.cell-output .cell-output-display}\n![Vendor cross-check of the pricing layer against QuantLib's analytic Black-Scholes implementation. Each dot is one $(S, K, T, r, \\sigma)$ evaluation point across five scenarios spanning calm, stress, and near-expiry regimes; color denotes scenario. The x-axis is the basis-point integer pricer's call value, the y-axis is QuantLib's double-precision value. The dashed line marks identical pricing. Maximum deviation across all scenarios is 2.69 basis points, attributable to the rounding band of basis-point integer arithmetic versus double-precision floating point and to differences between the two libraries' implementations of erf, log, and exp. A bug in integer arithmetic would produce a systematic offset, not a 2.69 bp noise band. Source: 5 parameter scenarios, 20+ evaluation points each.](backtest-proofs_files/figure-pdf/fig-ql-output-1.pdf){#fig-ql}\n:::\n:::\n\n\nAcross 5 parameter scenarios the maximum\ndeviation between the basis-point integer pricer and QuantLib's\nanalytic pricer is 2\\.69 bp (@fig-ql). All\n5 scenarios fall within a 3 bp tolerance\n(yes). Any systematic bias in\nthe integer-arithmetic Black-Scholes implementation large enough to\ndistort the hedging-cost figures elsewhere in the paper would appear\nas a diagonal offset here; the maximum 2.69 bp deviation rules out\npricing bias at the 3 bp threshold used by buy-side validation desks.\n\n# Equity and Covered-Call Demo {.appendix #sec-appendix-equity}\n\n::: {.cell execution_count=15}\n\n::: {.cell-output .cell-output-display}\n![Instrument-agnostic position-ledger demonstration. Left panel: long 1,000 shares on the Hull 19.2 price path. Portfolio value (blue) starts at 0 (self-financing: cash borrowed at inception to purchase shares) and tracks $N \\times \\Delta S$ at each step. All step audit records pass: the trade-accounting identity holds for equity positions without modification to the ledger. Right panel: covered call on the same path (long 1,000 shares plus short 1 ATM call, K=50, $\\sigma$=20%). The call premium received at inception raises the initial portfolio value above zero; at expiry the call settles ITM and the settlement identity certifies the cash transfer.](backtest-proofs_files/figure-pdf/fig-equity-output-1.pdf){#fig-equity}\n:::\n:::\n\n\nFunding assumption. Both panels of @fig-equity model the equity\nposition as self-financing at inception: the cost of purchasing the\n$N$ shares is borrowed against the cash account, so the net asset\nvalue at $t=0$ is set to zero. This is a modelling choice that lets\nthe panels display the path-wise $N \\cdot \\Delta S$ tracking error and\nthe call premium received at inception against a common zero\nreference. The ledger's `valueIdentity` theorem holds for any positive\ninitial cash balance, so the assumption is purely a presentation\nconvention.\n\nEquity-only panel (left). The `EquityStrategy` holds 1,000 shares at a\nfixed quantity with no delta rebalancing. The portfolio value tracks\n$N \\times \\Delta S$ at each weekly step, with a small interest debit\non the borrowed cash, and every step audit record passes. This\nconfirms that `valueUpdateFormula` applies to equity positions without\nmodification to the Lean kernel: the trade application function\nreceives `(assetId, quantity, markPrice)` tuples with no\ninstrument-specific fields, so an equity share and an option contract\nare indistinguishable at the ledger layer.\n\nCovered-call panel (right). The `CoveredCallStrategy` combines the\nsame equity position with a short ATM call ($K = 50$, $\\sigma = 20\\%$).\nThe call premium received at inception raises the initial portfolio\nvalue above zero. At expiry ($S_T = 57.25 > K$), the call settles\nin-the-money and `settlement_value_formula` certifies the cash\ntransfer; the equity leg has no settlement and contributes its final\nmark-to-market value to the terminal PV. All\n19 step audit records pass across\nthe covered-call path, and the terminal PV reflects the capped upside\nof the covered-call payoff: the equity gain above $K$ is transferred\nto the call counterparty at settlement. No new Lean theorems were\nrequired for either strategy.\n\n\n# Replication {.appendix #sec-replication}\n\n```bash\ngit clone https://github.com/eigenq-xyz/quant-proofs\ncd quant-proofs/backtest-proofs\n\n# 1. Verify Lean proofs (Levels 1–2)\nmake verify-lean\n\n# 2. Run Python tests (Levels 2–4)\nmake test\n\n# 3. Install research dependencies and generate figures\ncd python && uv sync --group research\ncd ..\nmake paper\n```\n\nToolchain pinning. The Lean toolchain is pinned in\n`backtest-proofs/lean/lean-toolchain` to\n`leanprover/lean4:v4.30.0-rc2`; the Mathlib commit is locked in\n`lake-manifest.json`. The Python environment is pinned by\n`python/pyproject.toml` and `python/uv.lock` and requires Python\n$\\geq$ 3.12. The compiled FFI artifact (`libleanbacktest.so`) is\nplatform-specific (built on macOS arm64 and Linux x86_64; other\ntargets require a fresh `lake build`). The metrics-snapshot JSON\nrecords the git SHA at render time so each numerical claim in the\npaper can be traced back to a specific commit. After downloading WRDS\ndata per `docs/wrds_data_download.md`, re-run `make paper` to\nregenerate @fig-stress with real market data.\n\n# Metrics snapshot {.appendix}\n\nNumerical results are archived in\n`backtest-proofs/results/metrics.json`; the file is regenerated on each\nrender.\n\n\n# References {.unnumbered}\n\n",
    "supporting": [
      "backtest-proofs_files"
    ],
    "filters": []
  }
}
