import Mathlib.Probability.Process.Filtration
import Mathlib.Probability.Process.Adapted
import FtapProofs.Market

/-!
# Measure-theoretic 𝓕ₜ-measurability of the signal map

This module upgrades the pointwise *non-anticipation* guarantee of
`ResearchPipeline.NoLookahead` to a genuine **measure-theoretic** statement: the
trading signal, as a stochastic process, is *adapted* to the natural filtration
generated by the price process. This is the standard formalization of
"no look-ahead" in discrete-time asset-pricing theory: a process is
`𝓕ₜ`-measurable (information available at time `t`) exactly when its value at `t`
is determined by the prices observed up to and including `t`.

## What is proved

We model the price process as `price : ι → Ω → ℝ` (with `ι` a preorder of times,
e.g. `ℕ` or `Fin (T+1)`) on a measurable space `Ω`, assumed measurable in the
sense that each `price t` is `StronglyMeasurable`. The **natural filtration** is
mathlib's `MeasureTheory.Filtration.natural price hprice`, whose value at time `t`
is the σ-algebra `⨆ s ≤ t, MeasurableSpace.comap (price s) _` — the smallest
σ-algebra making every `price s` with `s ≤ t` measurable.

The headline results:

* `price_measurable_natural` — each individual price `price s` is `𝓕ₜ`-measurable
  whenever `s ≤ t`. This is the atomic fact behind every adaptedness claim below.
* `momentumSignal` — a momentum signal at time `t` built from `price (t - skip)`
  and `price (t - lookback)` (both indices `≤ t`), over `ℕ`-indexed time.
* `momentumSignal_adapted` — `Adapted 𝓕 (momentumSignal …)`: the momentum signal
  process is adapted to the natural filtration of prices. This is the genuine
  `𝓕ₜ`-measurability upgrade. `Bridge.lean` derives the `NoLookahead.NonAnticipating`
  predicate from this adaptedness (forward direction), unifying the two formulations.
* `vrpSignal` / `vrpSignal_adapted` — the variance-risk-premium signal of `studies/vrp`,
  built from a trailing realized variance of the price process and a contemporaneous
  implied-variance (squared VIX) observation. Because it reads two observable processes,
  it is adapted to any filtration carrying both (`Adapted 𝒻 price` and
  `Adapted 𝒻 impliedVar`), the joint market-information filtration, rather than the
  price-only natural filtration.

## Relation to `ftap-proofs`

This is wired against `ftap-proofs` and **cites its `FinancialMarket`
infrastructure**. `FtapProofs.FinancialMarket` (in `FtapProofs.Market`) carries a
filtration `𝒻 : MeasureTheory.Filtration (Fin (T+1)) m` together with the field
`S_adapted : ∀ i, MeasureTheory.Adapted 𝒻 (S i)` — the exact adaptedness contract
asset prices satisfy in the discrete FTAP. The lemma
`market_price_natural_le_filtration` connects the two pictures: the *natural*
filtration generated by a market's price process is no finer than the market's own
filtration `𝒻`, which is precisely why an `𝓕ₜ`-adapted signal built on the natural
filtration is also adapted to the market filtration used by the FTAP. Concretely
it consumes `FtapProofs.FinancialMarket.S_adapted`.

The module imports `FtapProofs.Market`, so the `require «ftap-proofs»` dependency
in `lakefile.lean` is live and exercised, not nominal.
-/

open MeasureTheory MeasurableSpace

namespace ResearchPipeline

variable {Ω : Type*} [MeasurableSpace Ω] {ι : Type*} [Preorder ι]

/-! ### The natural filtration of a price process -/

/-- The natural filtration generated by a discrete-time price process
`price : ι → Ω → ℝ`. At time `t`, `naturalFiltration price hp t` is the σ-algebra
`⨆ s ≤ t, comap (price s) _`, the smallest one for which every observation
`price s` with `s ≤ t` is measurable. This is the information set `𝓕ₜ`. -/
noncomputable def naturalFiltration (price : ι → Ω → ℝ)
    (hp : ∀ t, StronglyMeasurable (price t)) : Filtration ι ‹MeasurableSpace Ω› :=
  Filtration.natural price hp

/-- A single past observation is `𝓕ₜ`-measurable: if `s ≤ t`, then `price s` is
measurable with respect to `naturalFiltration price hp t`.

This is the atomic non-anticipation fact, now stated measure-theoretically.
The comap `comap (price s) _` is one of the joined σ-algebras in
`⨆ s ≤ t, comap (price s) _`, so it is `≤ 𝓕ₜ`; measurability then follows from
`Measurable.of_comap_le`. -/
theorem price_measurable_natural
    (price : ι → Ω → ℝ) (hp : ∀ t, StronglyMeasurable (price t))
    {s t : ι} (hst : s ≤ t) :
    Measurable[naturalFiltration price hp t] (price s) := by
  apply Measurable.of_comap_le
  show MeasurableSpace.comap (price s) _ ≤
    ⨆ j, ⨆ (_ : j ≤ t), MeasurableSpace.comap (price j) _
  exact le_iSup₂ (f := fun j (_ : j ≤ t) => MeasurableSpace.comap (price j) _) s hst

/-! ### Citation of `ftap-proofs`: connecting to the FTAP market filtration -/

/-- **The natural filtration is coarser than any filtration to which the price is
adapted.** If a filtration `𝒻` already makes every price observation measurable
(`Adapted 𝒻 price`), then the natural filtration is `≤ 𝒻` at every time. The witness
is exactly the adaptedness hypothesis: each `comap (price j) _ ≤ 𝒻 j ≤ 𝒻 t`. -/
theorem naturalFiltration_le_of_adapted
    (price : ι → Ω → ℝ) (hp : ∀ t, StronglyMeasurable (price t))
    (𝒻 : Filtration ι ‹MeasurableSpace Ω›)
    (hadapted : Adapted 𝒻 price) (t : ι) :
    naturalFiltration price hp t ≤ 𝒻 t := by
  show ⨆ j, ⨆ (_ : j ≤ t), MeasurableSpace.comap (price j) _ ≤ 𝒻 t
  exact iSup₂_le fun j hjt => (hadapted j).comap_le.trans (𝒻.mono hjt)

/-- Specialization to a concrete `FtapProofs.FinancialMarket`: for a fixed risky
asset `i`, the natural filtration of that asset's discrete-time price process is
coarser than the market filtration `m.𝒻`. The adaptedness witness is
`m.S_adapted i`, the FTAP market's own `MeasureTheory.Adapted` field. This is the
live citation of `ftap-proofs`. -/
theorem market_price_natural_le_filtration
    [Fintype Ω] [MeasurableSingletonClass Ω]
    (m : FtapProofs.FinancialMarket Ω) (i : Fin m.n)
    (hp : ∀ t : Fin (m.T + 1), StronglyMeasurable (m.S i t))
    (t : Fin (m.T + 1)) :
    naturalFiltration (m.S i) hp t ≤ m.𝒻 t :=
  naturalFiltration_le_of_adapted (m.S i) hp m.𝒻 (m.S_adapted i) t

/-! ### The momentum signal and its adaptedness (over `ℕ`-indexed time) -/

/-- A momentum signal process over discrete time `ℕ`. At time `t` the (per-state)
signal is a function of two past prices: the price `skip` steps back and the price
`lookback` steps back, each clamped to a valid index by `Nat` truncated subtraction
(so both indices are `≤ t`). The combiner `g : ℝ → ℝ → ℝ` is an arbitrary
measurable rule (e.g. `g a b = a - b` for a price-difference momentum, or a log
ratio).

Because both `t - skip ≤ t` and `t - lookback ≤ t`, the value at time `t` reads
only the information in `𝓕ₜ`.

Note on early dates: `Nat` truncated subtraction means that for `t < skip` (resp.
`t < lookback`) the index clamps to `0`, so the signal reads `price 0` rather than
producing a sentinel. This is harmless for the adaptedness statement (the index is
still `≤ t`), but it is slightly more permissive than the Python implementation,
which emits `NaN` for an incomplete rolling window. -/
noncomputable def momentumSignal (price : ℕ → Ω → ℝ) (skip lookback : ℕ)
    (g : ℝ → ℝ → ℝ) : ℕ → Ω → ℝ :=
  fun t ω => g (price (t - skip) ω) (price (t - lookback) ω)

/-- **𝓕ₜ-measurability of the momentum signal.** If the price process is
measurable and the combiner `g` is measurable, then the momentum signal process is
**adapted** to the natural filtration of prices: for every `t`, `momentumSignal …
t` is `𝓕ₜ`-measurable. This is the genuine measure-theoretic non-anticipation
statement — the upgrade of `ResearchPipeline.NonAnticipating`.

The proof reads each leg through `price_measurable_natural` (`t - skip ≤ t` and
`t - lookback ≤ t` by `Nat.sub_le`) and combines them with measurability of `g`. -/
theorem momentumSignal_adapted
    (price : ℕ → Ω → ℝ) (hp : ∀ t, StronglyMeasurable (price t))
    (skip lookback : ℕ) {g : ℝ → ℝ → ℝ} (hg : Measurable g.uncurry) :
    Adapted (naturalFiltration price hp) (momentumSignal price skip lookback g) := by
  intro t
  have h1 : Measurable[naturalFiltration price hp t] (price (t - skip)) :=
    price_measurable_natural price hp (Nat.sub_le t skip)
  have h2 : Measurable[naturalFiltration price hp t] (price (t - lookback)) :=
    price_measurable_natural price hp (Nat.sub_le t lookback)
  exact hg.comp (h1.prodMk h2)

/-- **The momentum signal is adapted to any filtration the price is adapted to.**
This is the composition of `momentumSignal_adapted` with
`naturalFiltration_le_of_adapted`: since the natural filtration is the coarsest one
making the price adapted, a signal that is `𝓕ₜ`-measurable against it is also
measurable against every coarser-information filtration `𝒻` (i.e. any `𝒻` with
`Adapted 𝒻 price`).

The motivating instance is the FTAP market filtration: for an `ℕ`-indexed market
price process that is `Adapted m.𝒻`, the momentum signal is `Adapted m.𝒻` too. The
`Fin (m.T + 1)`-indexed `FtapProofs.FinancialMarket` is bridged separately by
`market_price_natural_le_filtration`; this lemma is the `ℕ`-time form that the
pipeline's signal layer actually consumes. -/
theorem momentumSignal_adapted_of_le
    (price : ℕ → Ω → ℝ) (hp : ∀ t, StronglyMeasurable (price t))
    (𝒻 : Filtration ℕ ‹MeasurableSpace Ω›) (hadapted : Adapted 𝒻 price)
    (skip lookback : ℕ) {g : ℝ → ℝ → ℝ} (hg : Measurable g.uncurry) :
    Adapted 𝒻 (momentumSignal price skip lookback g) := fun t =>
  (momentumSignal_adapted price hp skip lookback hg t).mono
    (naturalFiltration_le_of_adapted price hp 𝒻 hadapted t) le_rfl

/-! ### The variance-risk-premium signal and its adaptedness (over `ℕ`-indexed time)

The momentum signal above reads only the price process. The VRP signal of
`studies/vrp` reads two observable processes: the price process (through a trailing
realized variance) and an implied-variance process (the squared VIX). It is therefore
adapted not to the price-only natural filtration but to any filtration to which **both**
processes are adapted, i.e. the joint market-information filtration available at time
`t`. That is the honest scope of the non-anticipation guarantee for this signal. -/

/-- A trailing realized-variance functional. At time `t` it applies a measurable
aggregator `rv` to the window of the `window + 1` most recent prices
`price t, price (t-1), …, price (t-window)` (every index `≤ t` by truncated
subtraction). The VRP instance takes `rv` to be the sum of squared log returns over the
window; any measurable `rv` is covered. -/
noncomputable def realizedVar (price : ℕ → Ω → ℝ) (window : ℕ)
    (rv : (Fin (window + 1) → ℝ) → ℝ) : ℕ → Ω → ℝ :=
  fun t ω => rv (fun i => price (t - (i : ℕ)) ω)

/-- The variance-risk-premium signal process over discrete time `ℕ`. At time `t` it
combines the implied-variance observation `impliedVar t` (the squared VIX) with the
trailing `realizedVar` of the price process via a measurable rule `combine`. The VRP
instance is `combine iv r = c * iv - r` with `c = 30/365` and `iv = VIX²`, i.e.
implied minus realized variance.

Both arguments read only information available at `t`: `impliedVar t` is the
contemporaneous observation, and `realizedVar` reads prices at indices `t - i ≤ t`. -/
noncomputable def vrpSignal (price impliedVar : ℕ → Ω → ℝ) (window : ℕ)
    (rv : (Fin (window + 1) → ℝ) → ℝ) (combine : ℝ → ℝ → ℝ) : ℕ → Ω → ℝ :=
  fun t ω => combine (impliedVar t ω) (realizedVar price window rv t ω)

/-- **𝓕ₜ-measurability of the VRP signal.** If the price process and the
implied-variance process are both adapted to a filtration `𝒻`, the aggregator `rv` is
measurable, and the combiner `combine` is measurable, then the VRP signal process is
**adapted** to `𝒻`: its value at `t` is `𝒻 t`-measurable, reading only information
available at `t`.

This is the genuine measure-theoretic non-anticipation statement for the VRP signal,
the analogue of `momentumSignal_adapted` for a two-process signal. The realized-variance
leg reads each windowed price `price (t - i)` through `Adapted` plus `t - i ≤ t`
(`Nat.sub_le`), assembles them into a `Fin (window+1) → ℝ` vector (`measurable_pi_iff`),
and applies `rv`; the implied-variance leg is `hiv t`; the two are combined through
`combine`. Unlike the momentum signal, no price-only natural filtration suffices, since
the implied-variance process is exogenous to prices: the correct information set is the
joint filtration `𝒻` carrying both. -/
theorem vrpSignal_adapted
    (price impliedVar : ℕ → Ω → ℝ)
    (𝒻 : Filtration ℕ ‹MeasurableSpace Ω›)
    (hprice : Adapted 𝒻 price) (hiv : Adapted 𝒻 impliedVar)
    (window : ℕ) {rv : (Fin (window + 1) → ℝ) → ℝ} (hrv : Measurable rv)
    {combine : ℝ → ℝ → ℝ} (hcombine : Measurable combine.uncurry) :
    Adapted 𝒻 (vrpSignal price impliedVar window rv combine) := by
  intro t
  have hrvleg : Measurable[𝒻 t] (realizedVar price window rv t) := by
    -- `measurable_pi_lambda` synthesizes its domain `MeasurableSpace Ω` by instance
    -- resolution, which would pick the ambient `m` rather than the sub-σ-algebra `𝒻 t`;
    -- `letI` makes `𝒻 t` the resolved instance inside this leg so the window map is
    -- measured against `𝒻 t`. The `have`'s explicit `[𝒻 t]` type keeps it usable outside.
    letI : MeasurableSpace Ω := 𝒻 t
    exact hrv.comp (measurable_pi_lambda _ fun i =>
      (hprice (t - (i : ℕ))).mono (𝒻.mono (Nat.sub_le t (i : ℕ))) le_rfl)
  exact hcombine.comp ((hiv t).prodMk hrvleg)

end ResearchPipeline
