/-!
# Non-anticipation (the finite analogue of 𝓕ₜ-measurability)

The backtesting stage of the pipeline must guarantee that no decision uses information
from the future. In the finite, pointwise setting (cf. `ftap-proofs`, where almost-sure
qualifiers reduce to pointwise conditions) this is **non-anticipation**: a process whose
value at time `t` is a function of the path only up to time `t`.

This module is dependency-free (pure Lean core) and **`sorry`-free**. It states
non-anticipation, and proves the key consequence: *a portfolio decision built from a
non-anticipating signal cannot depend on future observations.* The measure-theoretic
upgrade — genuine 𝓕ₜ-measurability against the filtration generated by the price
process, citing `ftap-proofs` — is proved in `Measurability.lean`, and `Bridge.lean`
shows that the measure-theoretic version *implies* a pointwise (outcome-level)
non-anticipation property paralleling the one defined here.
-/

namespace ResearchPipeline

/-- Discrete time. -/
abbrev Time := Nat

/-- A path of observables (e.g. prices) indexed by time and asset, valued in `V`. -/
abbrev Path (Asset V : Type) := Time → Asset → V

/-- Two paths agree at every time `≤ t` (same information set up to `t`). -/
def AgreeUpTo {Asset V : Type} (p q : Path Asset V) (t : Time) : Prop :=
  ∀ s, s ≤ t → ∀ a, p s a = q s a

/-- A map from paths to a per-asset process is **non-anticipating** if its value at
time `t` depends only on the path up to time `t`. Pointwise analogue of `𝓕ₜ`-measurability. -/
def NonAnticipating {Asset V W : Type} (f : Path Asset V → Time → Asset → W) : Prop :=
  ∀ (p q : Path Asset V) (t : Time), AgreeUpTo p q t → ∀ a, f p t a = f q t a

/-- **No look-ahead in the decision.** If a signal `S` is non-anticipating and the
position map `w` reads only the time-`t` signal cross-section, then the positions taken
at time `t` are identical on any two paths that agree up to `t` — i.e. they cannot
depend on anything after `t`. -/
theorem decision_uses_no_future
    {Asset V W X : Type}
    (S : Path Asset V → Time → Asset → W)
    (w : (Asset → W) → Asset → X)
    (hS : NonAnticipating S)
    (p q : Path Asset V) (t : Time) (h : AgreeUpTo p q t) :
    (fun a => w (fun b => S p t b) a) = (fun a => w (fun b => S q t b) a) := by
  have hsig : (fun b => S p t b) = (fun b => S q t b) := funext (hS p q t h)
  rw [hsig]

end ResearchPipeline
