import Mathlib.Probability.Process.Adapted
import Mathlib.Probability.Distributions.Uniform
import Mathlib.MeasureTheory.Group.Arithmetic
import FtapProofs.Market

/-!
# The Cox-Ross-Rubinstein Binomial Market

This module instantiates the Cox-Ross-Rubinstein (CRR) binomial model as a
`FtapProofs.FinancialMarket`. It is the **market definition only**: the no-arbitrage
condition (the rate restriction `d < 1 + r < u`) and put-call parity are proved in
later modules.

## Model

Fix a horizon `T : ℕ`, an initial price `S₀ > 0`, up/down factors `0 < d < u`, and a
per-period rate `r > -1`. The state space is

  `Ω := Fin T → Bool`

a sequence of `T` up/down moves (`true` = up). It carries the discrete (`⊤`) measurable
space, so every set is measurable and `MeasurableSingletonClass` is automatic.

- **Up-count.** `ups t ω` is the number of up-moves strictly before time `t`.
- **Single risky asset** (`n := 1`): `S 0 t ω := S₀ * u ^ (ups t ω) * d ^ (t - ups t ω)`.
- **Numeraire.** `B t := (1 + r) ^ t`, so `B 0 = 1` and `B t > 0` from `0 < 1 + r`.
- **Filtration.** The natural filtration generated by the first `t` coordinates, built as
  the σ-algebra `comap (truncate t) ⊤` making the "restrict to the first `t` moves" map
  measurable. This is the information available at time `t`. We deliberately do **not** use
  the trivial `⊤` filtration: under `⊤` the conditional expectation collapses to the
  identity and the martingale condition of the FTAP becomes vacuous-wrong for a real tree.
- **Reference measure.** The uniform probability measure on `Ω` (full support).

## Contents

- Instances on `Ω` (`MeasurableSpace ⊤`, `MeasurableSingletonClass`, `Nonempty`).
- `crrNumeraire`, `crrNumeraire_pos`, `crrNumeraire_zero`.
- `ups`, `crrPrice`, and the factor-through lemma `ups_truncate`.
- `crrFiltration` and its measurability.
- `crrPrice_adapted` (adaptedness of the risky asset).
- `crrMeasure`, `crrMeasure_prob`.
- `crrMarket`, the assembled `FinancialMarket`.
-/

namespace OptionsProofs

open MeasureTheory

/-! ### State space and its instances -/

/-- The CRR state space: a sequence of `T` up/down moves (`true` = up-move). -/
abbrev CRRState (T : ℕ) : Type := Fin T → Bool

/-- The CRR state space carries the discrete (`⊤`) σ-algebra: every set is measurable. -/
instance instMeasurableSpaceCRRState (T : ℕ) : MeasurableSpace (CRRState T) := ⊤

/-- Under the discrete σ-algebra every singleton is measurable. -/
instance instMeasurableSingletonClassCRRState (T : ℕ) :
    MeasurableSingletonClass (CRRState T) :=
  ⟨fun _ => trivial⟩

/-- `CRRState T` is finite. -/
instance instFintypeCRRState (T : ℕ) : Fintype (CRRState T) := inferInstance

/-- `CRRState T` is nonempty (the all-down path is a state). -/
instance instNonemptyCRRState (T : ℕ) : Nonempty (CRRState T) := inferInstance

/-! ### Numeraire -/

/-- The CRR numeraire (risk-free bond): `B t = (1 + r) ^ t`. -/
def crrNumeraire (T : ℕ) (r : ℝ) (t : Fin (T + 1)) : ℝ := (1 + r) ^ (t : ℕ)

/-- The numeraire is strictly positive whenever `-1 < r`. -/
lemma crrNumeraire_pos {T : ℕ} {r : ℝ} (hr : -1 < r) (t : Fin (T + 1)) :
    0 < crrNumeraire T r t :=
  pow_pos (by linarith) _

/-- The numeraire starts at `1`. -/
lemma crrNumeraire_zero {T : ℕ} {r : ℝ} :
    crrNumeraire T r ⟨0, Nat.zero_lt_succ T⟩ = 1 := by
  simp [crrNumeraire]

/-! ### Up-count and the risky-asset price -/

/-- `ups t ω` is the number of up-moves strictly before time `t`. -/
def ups {T : ℕ} (t : ℕ) (ω : CRRState T) : ℕ :=
  (Finset.univ.filter (fun j : Fin T => (j : ℕ) < t ∧ ω j = true)).card

/-- The up-count never exceeds the elapsed time: `ups t ω ≤ t`. Needed downstream (O2/O3)
for `crrPrice` positivity and the one-step price recursion: the up-moves before time `t`
inject into `{0, …, t-1}` via `Fin.val`. -/
lemma ups_le_time {T : ℕ} (t : ℕ) (ω : CRRState T) : ups t ω ≤ t := by
  unfold ups
  have h : (Finset.univ.filter (fun j : Fin T => (j : ℕ) < t ∧ ω j = true)).card
      ≤ (Finset.range t).card := by
    refine Finset.card_le_card_of_injOn (fun j : Fin T => (j : ℕ)) ?_ ?_
    · intro j hj
      rw [Finset.mem_coe, Finset.mem_filter] at hj
      exact Finset.mem_coe.mpr (Finset.mem_range.mpr hj.2.1)
    · intro j _ k _ hjk
      exact Fin.ext hjk
  rwa [Finset.card_range] at h

/-- The risky-asset price at time `t`:
`S₀ * u ^ (#up-moves before t) * d ^ (#down-moves before t)`. -/
def crrPrice (T : ℕ) (S₀ u d : ℝ) (t : Fin (T + 1)) (ω : CRRState T) : ℝ :=
  S₀ * u ^ (ups (t : ℕ) ω) * d ^ ((t : ℕ) - ups (t : ℕ) ω)

/-! ### The natural filtration generated by the first `t` coordinates -/

/-- The "truncate to the first `t` moves" map `Ω → (Fin t → Bool)`. The information
available at time `t` is exactly the σ-algebra making this map measurable. -/
def truncate {T : ℕ} (t : ℕ) (ω : CRRState T) : Fin (min t T) → Bool :=
  fun j => ω (Fin.castLE (min_le_right t T) j)

/-- We endow each truncation codomain with the discrete σ-algebra, so the only content of
the measurability arguments below is the factor-through structure, not σ-algebra bookkeeping. -/
instance instMeasurableSpaceTruncCodomain (t T : ℕ) :
    MeasurableSpace (Fin (min t T) → Bool) := ⊤

/-- The CRR filtration: at time `t`, the σ-algebra generated by the first `t` coordinates,
i.e. the σ-algebra making `truncate t` measurable. Monotone in `t` because a longer
truncation determines a shorter one. -/
def crrFiltration (T : ℕ) :
    MeasureTheory.Filtration (Fin (T + 1)) (instMeasurableSpaceCRRState T) where
  seq t := MeasurableSpace.comap (truncate (t : ℕ)) ⊤
  mono' s t hst := by
    -- The shorter truncation factors through the longer one: `truncate s = k ∘ truncate t`,
    -- where `k f j = f (Fin.castLE _ j)`.
    have hle : (s : ℕ) ≤ (t : ℕ) := hst
    have hk : truncate (T := T) (s : ℕ) =
        (fun (f : Fin (min (t : ℕ) T) → Bool) (j : Fin (min (s : ℕ) T)) =>
          f (Fin.castLE (by omega) j)) ∘ truncate (t : ℕ) := by
      funext ω; rfl
    -- `comap (truncate s) ⊤ = comap (k ∘ truncate t) ⊤ = (comap k ⊤).comap (truncate t)`,
    -- which is `≤ comap (truncate t) ⊤` since `comap k ⊤ ≤ ⊤` and `comap (truncate t) ·` is monotone.
    show MeasurableSpace.comap (truncate (s : ℕ)) ⊤ ≤ MeasurableSpace.comap (truncate (t : ℕ)) ⊤
    rw [hk, ← MeasurableSpace.comap_comp]
    exact MeasurableSpace.comap_mono le_top
  le' _ := le_top

/-! ### Adaptedness of the risky asset -/

/-- `ups t` factors through `truncate t`: it depends only on the first `t` coordinates.
This is the heart of adaptedness. -/
lemma ups_truncate {T : ℕ} (t : ℕ) :
    ∃ h : (Fin (min t T) → Bool) → ℕ, (ups (T := T) t) = h ∘ (truncate t) := by
  classical
  -- On the domain `Fin (min t T)`, the constraint `↑j < t` is automatic, so the count
  -- of up-moves before `t` is exactly the number of `true` entries of `truncate t ω`.
  refine ⟨fun f => (Finset.univ.filter (fun j : Fin (min t T) => f j = true)).card, ?_⟩
  funext ω
  simp only [Function.comp_apply, ups, truncate]
  -- Bijection `Fin T ∩ {· < t}  ≃  Fin (min t T)` given by `↑·`, with inverse `castLE`.
  refine Finset.card_bij'
    (fun (j : Fin T) (hj : j ∈ _) => (⟨(j : ℕ), by
        simp only [Finset.mem_filter] at hj; omega⟩ : Fin (min t T)))
    (fun (j : Fin (min t T)) (_ : j ∈ _) => Fin.castLE (min_le_right t T) j)
    ?_ ?_ ?_ ?_
  · intro j hj
    simp only [Finset.mem_filter] at hj ⊢
    refine ⟨Finset.mem_univ _, ?_⟩
    simpa using hj.2.2
  · intro j hj
    simp only [Finset.mem_filter] at hj ⊢
    refine ⟨Finset.mem_univ _, ?_, ?_⟩
    · have : ((Fin.castLE (min_le_right t T) j : Fin T) : ℕ) = (j : ℕ) := rfl
      omega
    · simpa using hj
  · intro j hj
    exact Fin.ext rfl
  · intro j hj
    exact Fin.ext rfl

/-- The risky-asset price is adapted to the CRR filtration: `crrPrice t` is
`ℱ_t`-measurable. It factors through `truncate t` because `ups t` does. -/
lemma crrPrice_adapted (T : ℕ) (S₀ u d : ℝ) :
    MeasureTheory.Adapted (crrFiltration T) (crrPrice T S₀ u d) := by
  intro t
  -- Reduce to: `crrPrice t` is `comap (truncate t) ⊤`-measurable, via factor-through.
  obtain ⟨h, hh⟩ := ups_truncate (T := T) (t : ℕ)
  refine Measurable.of_comap_le ?_
  -- `crrPrice t = g ∘ truncate t` where `g f = S₀ * u ^ h f * d ^ (t - h f)`.
  have hg : crrPrice T S₀ u d t =
      (fun (f : Fin (min (t : ℕ) T) → Bool) =>
        S₀ * u ^ (h f) * d ^ ((t : ℕ) - h f)) ∘ truncate (t : ℕ) := by
    funext ω
    simp only [crrPrice, Function.comp_apply]
    rw [show ups (T := T) (t : ℕ) ω = h (truncate (t : ℕ) ω) from congrFun hh ω]
  -- `comap (crrPrice t) _ = (comap g _).comap (truncate t) ≤ comap (truncate t) ⊤`.
  rw [hg, ← MeasurableSpace.comap_comp]
  exact MeasurableSpace.comap_mono le_top

/-! ### Reference probability measure -/

/-- The CRR reference measure: the uniform probability measure on the (finite, nonempty)
state space. Full support, which the no-arbitrage module will use. -/
noncomputable def crrMeasure (T : ℕ) : MeasureTheory.Measure (CRRState T) :=
  (PMF.uniformOfFintype (CRRState T)).toMeasure

/-- The CRR reference measure is a probability measure. -/
instance crrMeasure_prob (T : ℕ) : MeasureTheory.IsProbabilityMeasure (crrMeasure T) := by
  unfold crrMeasure
  infer_instance

/-! ### The assembled CRR market -/

/-- The Cox-Ross-Rubinstein binomial market as a `FtapProofs.FinancialMarket`.

Parameters: horizon `T`, initial price `S₀ > 0`, up/down factors `0 < d < u`, per-period
rate `r > -1`. One risky asset following the binomial tree, the bond `B t = (1 + r) ^ t`,
the natural filtration of the up/down moves, and the uniform reference measure.

The hypotheses `hS₀`, `hd`, `hud`, `hr` are carried for downstream modules; only `hr`
(via `crrNumeraire_pos`) is needed for the structure fields here. -/
noncomputable def crrMarket (T : ℕ) (S₀ u d r : ℝ)
    (_hS₀ : 0 < S₀) (_hd : 0 < d) (_hud : d < u) (hr : -1 < r) :
    FtapProofs.FinancialMarket (CRRState T) where
  T := T
  n := 1
  S := fun _ => crrPrice T S₀ u d
  B := crrNumeraire T r
  𝒻 := crrFiltration T
  S_adapted := fun _ => crrPrice_adapted T S₀ u d
  B_pos := crrNumeraire_pos hr
  B_zero := crrNumeraire_zero
  P := crrMeasure T
  P_prob := crrMeasure_prob T

end OptionsProofs
